import { BankQuestion } from '../questionTypes.js';

/**
 * B2 Level Question Bank - Farh SprachArena
 * Exactly 100 Questions:
 * - 35 SCHNELLANTWORT (Nomen-Verb-Verbindungen, Passiversatz, Konjunktiv I/II, Genitiv-Präpositionen, Partizipialkonstruktionen, Nuancen)
 * - 15 SATZ_RENNEN (Complex connectors je...desto, Partizipien, Subordinate embeddings, Inversions)
 * - 20 WORTSCHATZ_DUELL (Academic and professional vocabulary, Idiomatic idioms, Abstract nouns, Socioeconomic terms)
 * - 15 WAS_BIN_ICH (Complex socioeconomic, technological, philosophical concepts, Inventions, Scientific principles)
 * - 15 TEAM_BATTLE (Debates, Professional negotiations, Formal argumentation, Nuanced register, Rhetorical comprehension)
 *
 * Difficulty: 30 EASY, 50 MEDIUM, 20 HARD
 */
export const B2_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ B2: SCHNELLANTWORT (35 Questions: 10 EASY, 18 MEDIUM, 7 HARD)
  // =========================================================================
  {
    id: 'B2-SA-0001',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Geschäftsführung muss in dieser schwierigen Situation schnell eine weitreichende Entscheidung ___ .',
    options: ['treffen', 'machen', 'tun', 'stellen'],
    correctAnswer: 'treffen',
    explanation: 'Die feste Nomen-Verb-Verbindung lautet "eine Entscheidung treffen" (= sich entscheiden).',
    tags: ['Nomen-Verb-Verbindungen', 'Wirtschaft', 'B2-Grammatik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0002',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Für Fragen und Beratungen ___ Ihnen unser Kundenservice jederzeit gern zur Verfügung.',
    options: ['steht', 'liegt', 'sitzt', 'hält'],
    correctAnswer: 'steht',
    explanation: '"zur Verfügung stehen" bedeutet verfügbar / erreichbar sein ("jemandem etwas zur Verfügung stellen" = bereitstellen).',
    tags: ['Nomen-Verb-Verbindungen', 'Höflichkeit', 'Geschäftssprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0003',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Bei der Planung müssen wir auch mögliche finanzielle Risiken in Betracht ___ .',
    options: ['ziehen', 'nehmen', 'bringen', 'legen'],
    correctAnswer: 'ziehen',
    explanation: '"etwas in Betracht ziehen" bedeutet etwas berücksichtigen / erwägen.',
    tags: ['Nomen-Verb-Verbindungen', 'Gehobene Sprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0004',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Passiversatzformen sein + zu + Infinitiv',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Dieses komplexe grammatische Phänomen ist für Lernende nur schwer ___ .',
    options: ['zu verstehen', 'verstanden werden', 'verstehbar sein', 'verstehen'],
    correctAnswer: 'zu verstehen',
    explanation: '"sein + zu + Infinitiv" drückt eine passive Möglichkeit (kann verstanden werden) oder Notwendigkeit (muss verstanden werden) aus.',
    tags: ['Passiversatz', 'Grammatik', 'Modale Bedeutung'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0005',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Passiversatzformen sich lassen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das Problem mit der Datenbank ___ sich leider nicht ohne Weiteres beheben.',
    options: ['lässt', 'kann', 'wird', 'darf'],
    correctAnswer: 'lässt',
    explanation: '"sich lassen + Infinitiv" ist eine geläufige Passivalternative mit der Bedeutung "kann behoben werden".',
    tags: ['Passiversatz', 'sich lassen', 'Technik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0006',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Doppelkonjunktion je... desto/umso',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Je intensiver man eine Fremdsprache übt, ___ flüssiger kann man sich im Alltag verständigen.',
    options: ['desto', 'dann', 'weil', 'so'],
    correctAnswer: 'desto',
    explanation: 'Auf "je + Komparativ" (Nebensatz) folgt im Hauptsatz obligatorisch "desto / umso + Komparativ".',
    tags: ['Proportionalsatz', 'je-desto', 'Konnektoren'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0007',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativpronomen Genitiv Maskulinum/Neutrum',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir danken dem Autor, ___ neues Fachbuch bereits in zehn Sprachen übersetzt wurde.',
    options: ['dessen', 'deren', 'dem', 'dessenige'],
    correctAnswer: 'dessen',
    explanation: 'Das Relativpronomen im Genitiv für maskuline und neutrale Bezugswörter (der Autor) lautet "dessen".',
    tags: ['Relativsätze', 'Genitiv', 'dessen'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0008',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativpronomen Genitiv Femininum/Plural',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Wissenschaftlerin, ___ bahnbrechende Forschung weltweit beachtet wird, hält heute den Festvortrag.',
    options: ['deren', 'dessen', 'derer', 'die'],
    correctAnswer: 'deren',
    explanation: 'Das Relativpronomen im Genitiv für feminine Bezugswörter (die Wissenschaftlerin) und Plural lautet "deren".',
    tags: ['Relativsätze', 'Genitiv', 'deren'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0009',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Genitiv',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: '___ der drastisch gestiegenen Rohstoffpreise konnte das Unternehmen seinen Gewinn steigern.',
    options: ['Trotz', 'Wegen', 'Dank', 'Mittels'],
    correctAnswer: 'Trotz',
    explanation: '"Trotz" drückt einen konzessiven Gegensatz aus und verlangt standardsprachlich den Genitiv ("trotz der Preise").',
    tags: ['Präpositionen', 'Genitiv', 'Wirtschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0010',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Genitiv',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ der aktuellen wirtschaftlichen Lage müssen Einsparungen vorgenommen werden.',
    options: ['Angesichts', 'Zufolge', 'Entlang', 'Gemäß'],
    correctAnswer: 'Angesichts',
    explanation: '"Angesichts" (+ Genitiv) bedeutet "im Hinblick auf" oder "in Anbetracht der Tatsache".',
    tags: ['Präpositionen', 'Genitiv', 'Gehobene Sprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0011',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Indirekte Rede Konjunktiv I',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Minister erklärte auf der Pressekonferenz, die Regierung ___ alle notwendigen Reformen unverzüglich umsetzen.',
    options: ['werde', 'wird', 'würde', 'wurde'],
    correctAnswer: 'werde',
    explanation: 'In der formalen indirekten Rede (Pressesprache) wird für die 3. Person Singular der Konjunktiv I ("werde") verwendet.',
    tags: ['Konjunktiv I', 'Indirekte Rede', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0012',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konjunktiv I sein',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Sprecher betonte, die Vorwürfe ___ vollkommen unbegründet.',
    options: ['seien', 'sind', 'wären', 'seiest'],
    correctAnswer: 'seien',
    explanation: 'Der Konjunktiv I in der 3. Person Plural von sein lautet "sie seien".',
    tags: ['Konjunktiv I', 'Indirekte Rede', 'Journalismus'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0013',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Partizip I als Adjektiv',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die ___ Nachfrage nach erneuerbaren Energien stellt die Industrie vor neue Herausforderungen.',
    options: ['steigende', 'gestiegene', 'steigen', 'gestiegenen'],
    correctAnswer: 'steigende',
    explanation: 'Das Partizip I ("steigend" + Adjektivendung -e) drückt einen aktiven, gegenwärtig ablaufenden Vorgang aus.',
    tags: ['Partizip I', 'Adjektivdeklination', 'Wirtschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0014',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Partizip II als Adjektiv',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Alle im Vorfeld ___ Maßnahmen erwiesen sich als äußerst wirksam.',
    options: ['getroffenen', 'treffenden', 'getroffene', 'treffen'],
    correctAnswer: 'getroffenen',
    explanation: 'Das Partizip II ("getroffen" + Dativ/Plural-Endung -en) bezeichnet ein abgeschlossenes Resultat.',
    tags: ['Partizip II', 'Adjektivdeklination'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0015',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Irrealer Konjunktiv II der Vergangenheit',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn wir früher losgefahren wären, ___ wir den Zug nicht verpasst.',
    options: ['hätten', 'haben', 'waren', 'würden'],
    correctAnswer: 'hätten',
    explanation: 'Der irreale Konditionalsatz der Vergangenheit wird mit "hätte / wäre + Partizip II" gebildet ("hätten wir ... verpasst").',
    tags: ['Konjunktiv II', 'Vergangenheit', 'Hypothesen'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0016',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Adversative Konnektoren während / wohingegen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'In den Städten steigen die Mieten rasant, ___ auf dem Land viele Wohnungen leer stehen.',
    options: ['während / wohingegen', 'trotzdem', 'deshalb', 'infolgedessen'],
    correctAnswer: 'während / wohingegen',
    explanation: '"während / wohingegen" drückt einen direkten adversativen Kontrast zwischen zwei Sachverhalten aus.',
    tags: ['Konnektoren', 'Kontrast', 'Soziologie'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0017',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektor indem (Modalsatz)',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Man kann seinen CO2-Fußabdruck wirksam reduzieren, ___ man öfter mit der Bahn fährt.',
    options: ['indem', 'sodass', 'ohne dass', 'anstatt dass'],
    correctAnswer: 'indem',
    explanation: '"indem" beantwortet die Frage "Auf welche Art und Weise?" (Instrumentalsatz/Modalsatz).',
    tags: ['Modalsatz', 'indem', 'Umwelt'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0018',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektor sodass (Konsekutivsatz)',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Schneesturm war so heftig, ___ viele Straßen unpassierbar wurden.',
    options: ['sodass / dass', 'weil', 'obwohl', 'damit'],
    correctAnswer: 'sodass / dass',
    explanation: '"so ... dass / sodass" leitet einen Konsekutivsatz ein, der die tatsächliche Folge beschreibt.',
    tags: ['Konsekutivsatz', 'sodass', 'Wetter'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0019',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektor ohne dass',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er verließ die Besprechung vorzeitig, ___ jemand davon Notiz nahm.',
    options: ['ohne dass', 'anstatt dass', 'damit', 'nachdem'],
    correctAnswer: 'ohne dass',
    explanation: '"ohne dass" drückt das Ausbleiben einer erwarteten Begleiterscheinung aus.',
    tags: ['Modalsatz', 'ohne dass', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0020',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nominalisierung',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Formuliere im Nominalstil: "Weil die Gebühren erhöht wurden..." -> "Wegen der ___ der Gebühren..."',
    options: ['Erhöhung', 'Erhebung', 'Erholung', 'Erfahrung'],
    correctAnswer: 'Erhöhung',
    explanation: 'Das Nomen zum Verb "erhöhen" lautet "die Erhöhung" (Wegen der Erhöhung der Gebühren).',
    tags: ['Nominalstil', 'Wortbildung', 'Verwaltungssprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0021',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nominalisierung',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '"Wenn man sich regelmäßig bewegt..." -> "Bei regelmäßiger ___ ..."',
    options: ['Bewegung', 'Bewerbung', 'Bewunderung', 'Bewahrung'],
    correctAnswer: 'Bewegung',
    explanation: 'Das Nomen zum Verb "sich bewegen" lautet "die Bewegung".',
    tags: ['Nominalstil', 'Gesundheit'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0022',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich möchte dieses heikle Thema in der Konferenz lieber nicht zur Sprache ___ .',
    options: ['bringen', 'nehmen', 'setzen', 'führen'],
    correctAnswer: 'bringen',
    explanation: '"etwas zur Sprache bringen" bedeutet ein Thema ansprechen oder zur Diskussion stellen.',
    tags: ['Nomen-Verb-Verbindungen', 'Kommunikation'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0023',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wer im Straßenverkehr unterwegs ist, muss auf Kinder besondere Rücksicht ___ .',
    options: ['nehmen', 'machen', 'geben', 'tragen'],
    correctAnswer: 'nehmen',
    explanation: '"Rücksicht nehmen auf (+ Akk.)" bedeutet rücksichtsvoll und vorsichtig sein.',
    tags: ['Nomen-Verb-Verbindungen', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0024',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Bundesregierung will erneuerbare Energietechnologien gezielt in Schutz ___ .',
    options: ['nehmen', 'stellen', 'bringen', 'führen'],
    correctAnswer: 'nehmen',
    explanation: '"jemanden/etwas in Schutz nehmen" bedeutet verteidigen oder schützen.',
    tags: ['Nomen-Verb-Verbindungen', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0025',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Für diesen gravierenden Fehler müssen die Verantwortlichen die volle Verantwortung ___ .',
    options: ['tragen / übernehmen', 'machen', 'tun', 'legen'],
    correctAnswer: 'tragen / übernehmen',
    explanation: '"die Verantwortung tragen / übernehmen" ist die korrekte formale Kollokation.',
    tags: ['Nomen-Verb-Verbindungen', 'Ethik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0026',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Adjektivendungen mit Partizipialattribut',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die von Experten vor wenigen Wochen ___ Studie liefert alarmierende Ergebnisse zum Artensterben.',
    options: ['veröffentlichte', 'veröffentlichten', 'veröffentlichende', 'veröffentlicht'],
    correctAnswer: 'veröffentlichte',
    explanation: '"die ... veröffentlichte Studie" (Nominativ Singular feminin mit bestimmtem Artikel -> Endung -e).',
    tags: ['Partizipialattribute', 'Adjektive', 'Wissenschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0027',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektor es sei denn',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Konferenz findet wie geplant statt, ___ , die Fluggesellschaften streiken.',
    options: ['es sei denn', 'obwohl', 'insofern', 'trotzdem'],
    correctAnswer: 'es sei denn',
    explanation: '"es sei denn" schließt eine Ausnahme ein und bedeutet "außer wenn".',
    tags: ['Konnektoren', 'Ausnahme'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0028',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Feste Wendungen & Argumentation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Es liegt auf der ___ , dass Künstliche Intelligenz den Arbeitsmarkt grundlegend verändern wird.',
    options: ['Hand', 'Zunge', 'Nase', 'Schulter'],
    correctAnswer: 'Hand',
    explanation: '"auf der Hand liegen" ist eine feste Redewendung für "offensichtlich / klar sein".',
    tags: ['Redewendungen', 'Argumentation'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0029',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Zustandspassiv',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Tür des Tresors ___ seit gestern Abend fest verschlossen.',
    options: ['ist', 'wird', 'hat', 'wurde'],
    correctAnswer: 'ist',
    explanation: 'Das Zustandspassiv ("sein + Partizip II") beschreibt einen bestehenden Zustand als Resultat eines Vorgangs.',
    tags: ['Zustandspassiv', 'Grammatik'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0030',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Passiv mit Modalverben im Präteritum',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die beschädigte Brücke ___ unverzüglich für den Schwerlastverkehr gesperrt werden.',
    options: ['musste', 'wurde', 'hätte', 'durfte'],
    correctAnswer: 'musste',
    explanation: 'Passiv mit Modalverb im Präteritum: "musste ... gesperrt werden".',
    tags: ['Passiv', 'Modalverben', 'Präteritum'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0031',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wortbildung Suffixe -bar vs -lich',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ein Text, den man problemlos lesen und entziffern kann, ist ___ .',
    options: ['lesbar', 'leslich', 'lesend', 'gelesen'],
    correctAnswer: 'lesbar',
    explanation: 'Das Suffix "-bar" drückt die passive Machbarkeit aus (kann gelesen werden = lesbar).',
    tags: ['Wortbildung', 'Adjektive', 'Passiversatz'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0032',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Formelle Textbausteine & Bewerbung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Über eine Einladung zu einem persönlichen Vorstellungsgespräch würde ich mich sehr ___ .',
    options: ['freuen', 'bedanken', 'erwarten', 'hoffen'],
    correctAnswer: 'freuen',
    explanation: '"Über eine Einladung ... würde ich mich sehr freuen" ist der stilistisch elegante Schlusssatz eines Anschreibens.',
    tags: ['Bewerbung', 'Formeller Stil'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0033',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektor infolgedessen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Lieferketten brachen zusammen; ___ kam es zu massiven Produktionsausfällen.',
    options: ['infolgedessen', 'obgleich', 'dennoch', 'anstelle'],
    correctAnswer: 'infolgedessen',
    explanation: '"infolgedessen" (= folglich, als Konsequenz daraus) leitet die logische Folge ein.',
    tags: ['Konnektoren', 'Wirtschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0034',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präposition bezüglich (+ Genitiv)',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: '___ Ihrer Rückfrage vom 12. Mai teilen wir Ihnen mit, dass die Ware versandt wurde.',
    options: ['Bezüglich', 'Anlässlich', 'Inmitten', 'Ungeachtet'],
    correctAnswer: 'Bezüglich',
    explanation: '"Bezüglich" (+ Genitiv) bedeutet "hinsichtlich / in Bezug auf" und ist typisch für die Korrespondenz.',
    tags: ['Präpositionen', 'Genitiv', 'Geschäftsbrief'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0035',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Verhandlungen sind ins Stocken ___ , da sich beide Seiten uneinig sind.',
    options: ['geraten', 'gekommen', 'gefallen', 'getreten'],
    correctAnswer: 'geraten',
    explanation: '"ins Stocken geraten" bedeutet nicht mehr flüssig vorankommen / blockiert sein.',
    tags: ['Nomen-Verb-Verbindungen', 'Diplomatie'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 B2: SATZ-RENNEN (15 Questions: 5 EASY, 7 MEDIUM, 3 HARD)
  // =========================================================================
  {
    id: 'B2-SR-0001',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Doppelkonnektor je... desto',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde das komplexe Proportionalgefüge mit "je ... desto":',
    words: ['Je höher die Qualifikation ist,', 'desto', 'bessere Chancen', 'hat man', 'auf dem Arbeitsmarkt.'],
    correctOrder: ['Je höher die Qualifikation ist,', 'desto', 'bessere Chancen', 'hat man', 'auf dem Arbeitsmarkt.'],
    correctAnswer: ['Je höher die Qualifikation ist,', 'desto', 'bessere Chancen', 'hat man', 'auf dem Arbeitsmarkt.'],
    explanation: 'Nach "je ... ist" (Verb am Ende) folgt "desto + Komparativ + Substantiv + finites Verb (hat) + Subjekt (man)".',
    tags: ['je-desto', 'Satzbau', 'Arbeit'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0002',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Erweitertes Partizipialattribut',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Ordne das erweiterte Partizipialattribut korrekt an:',
    words: ['Die', 'von führenden Wissenschaftlern', 'entwickelte', 'Technologie', 'wird weltweit eingesetzt.'],
    correctOrder: ['Die', 'von führenden Wissenschaftlern', 'entwickelte', 'Technologie', 'wird weltweit eingesetzt.'],
    correctAnswer: ['Die', 'von führenden Wissenschaftlern', 'entwickelte', 'Technologie', 'wird weltweit eingesetzt.'],
    explanation: 'Artikel (Die) -> Partizipiale Erweiterung (von ... Wissenschaftlern) -> Partizip II (entwickelte) -> Bezugsnomen (Technologie).',
    tags: ['Partizipialattribute', 'Satzbau', 'Wissenschaft'],
    timeLimit: 30,
  },
  {
    id: 'B2-SR-0003',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Konjunktiv II Vergangenheit irreal',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den irrealen Bedingungssatz der Vergangenheit:',
    words: ['Hätten wir früher reagiert,', 'wäre', 'dieser folgenschwere Fehler', 'verhindert', 'worden.'],
    correctOrder: ['Hätten wir früher reagiert,', 'wäre', 'dieser folgenschwere Fehler', 'verhindert', 'worden.'],
    correctAnswer: ['Hätten wir früher reagiert,', 'wäre', 'dieser folgenschwere Fehler', 'verhindert', 'worden.'],
    explanation: 'Uneingeleiteter Konditionalsatz an der Spitze -> Passiv Konjunktiv II der Vergangenheit ("wäre ... verhindert worden").',
    tags: ['Konjunktiv II', 'Passiv', 'Vergangenheit'],
    timeLimit: 30,
  },
  {
    id: 'B2-SR-0004',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Nomen-Verb-Verbindung im Satz',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit der Nomen-Verb-Verbindung "in Betracht ziehen":',
    words: ['Wir', 'müssen', 'alle verfügbaren Optionen', 'sorgfältig in Betracht', 'ziehen.'],
    correctOrder: ['Wir', 'müssen', 'alle verfügbaren Optionen', 'sorgfältig in Betracht', 'ziehen.'],
    correctAnswer: ['Wir', 'müssen', 'alle verfügbaren Optionen', 'sorgfältig in Betracht', 'ziehen.'],
    explanation: 'Modalverb "müssen" an Position 2, Nomen-Verb-Verbindung ("in Betracht ziehen") schließt am Satzende ab.',
    tags: ['Nomen-Verb-Verbindungen', 'Satzbau'],
    timeLimit: 20,
  },
  {
    id: 'B2-SR-0005',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Relativsatz mit Genitiv und Präposition',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den komplexen Relativsatz:',
    words: ['Das ist die Forscherin,', 'mit deren Unterstützung', 'das Projekt', 'erfolgreich abgeschlossen', 'wurde.'],
    correctOrder: ['Das ist die Forscherin,', 'mit deren Unterstützung', 'das Projekt', 'erfolgreich abgeschlossen', 'wurde.'],
    correctAnswer: ['Das ist die Forscherin,', 'mit deren Unterstützung', 'das Projekt', 'erfolgreich abgeschlossen', 'wurde.'],
    explanation: '"mit deren Unterstützung" leitet das Passivgefüge im Relativsatz ein.',
    tags: ['Relativsätze', 'Genitiv', 'Passiv'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0006',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Konzessiv ungeachtet dessen',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Konzessivadverb:',
    words: ['Es gab heftige Kritik,', 'ungeachtet dessen', 'hielt', 'der Vorstand', 'an den Plänen fest.'],
    correctOrder: ['Es gab heftige Kritik,', 'ungeachtet dessen', 'hielt', 'der Vorstand', 'an den Plänen fest.'],
    correctAnswer: ['Es gab heftige Kritik,', 'ungeachtet dessen', 'hielt', 'der Vorstand', 'an den Plänen fest.'],
    explanation: '"ungeachtet dessen" steht im Vorfeld, gefolgt vom Prädikat "hielt".',
    tags: ['Konnektoren', 'Gehobene Sprache'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0007',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Passiversatz sein + zu + Infinitiv',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die Passiversatzkonstruktion:',
    words: ['Die Sicherheitsvorschriften', 'sind', 'von allen Mitarbeitern', 'strikt', 'einzuhalten.'],
    correctOrder: ['Die Sicherheitsvorschriften', 'sind', 'von allen Mitarbeitern', 'strikt', 'einzuhalten.'],
    correctAnswer: ['Die Sicherheitsvorschriften', 'sind', 'von allen Mitarbeitern', 'strikt', 'einzuhalten.'],
    explanation: '"sind ... einzuhalten" ersetzt die passive Notwendigkeit "müssen eingehalten werden".',
    tags: ['Passiversatz', 'Vorschriften'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0008',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Modalsatz anstatt dass',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Nebensatz mit "anstatt dass":',
    words: ['Er handelte eigenmächtig,', 'anstatt dass', 'er', 'zuvor', 'Rücksprache hielt.'],
    correctOrder: ['Er handelte eigenmächtig,', 'anstatt dass', 'er', 'zuvor', 'Rücksprache hielt.'],
    correctAnswer: ['Er handelte eigenmächtig,', 'anstatt dass', 'er', 'zuvor', 'Rücksprache hielt.'],
    explanation: '"anstatt dass" leitet den adversativen Modalsatz ein (Verb "hielt" am Ende).',
    tags: ['Modalsatz', 'anstatt dass'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0009',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Indirekte Rede Konjunktiv I',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den journalistischen Bericht in indirekter Rede:',
    words: ['Der Gutachter erklärte,', 'dass', 'die bestehenden Mängel', 'zeitnah behoben', 'werden müssten.'],
    correctOrder: ['Der Gutachter erklärte,', 'dass', 'die bestehenden Mängel', 'zeitnah behoben', 'werden müssten.'],
    correctAnswer: ['Der Gutachter erklärte,', 'dass', 'die bestehenden Mängel', 'zeitnah behoben', 'werden müssten.'],
    explanation: 'Im Nebensatz mit Passiv und Modalverb im Konjunktiv steht das finite Modalverb "müssten" ganz am Schluss.',
    tags: ['Indirekte Rede', 'Konjunktiv', 'Gutachten'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0010',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Genitiv-Präposition anlässlich',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit temporaler Genitiv-Präposition:',
    words: ['Anlässlich des Firmenjubiläums', 'hielt', 'der Gründer', 'eine bewegende Rede.'],
    correctOrder: ['Anlässlich des Firmenjubiläums', 'hielt', 'der Gründer', 'eine bewegende Rede.'],
    correctAnswer: ['Anlässlich des Firmenjubiläums', 'hielt', 'der Gründer', 'eine bewegende Rede.'],
    explanation: '"Anlässlich (+ Genitiv)" bildet das Vorfeld, finites Verb "hielt" an Position 2.',
    tags: ['Präpositionen', 'Genitiv', 'Feier'],
    timeLimit: 20,
  },
  {
    id: 'B2-SR-0011',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Partizip I Adverbial',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit adverbialem Partizip I:',
    words: ['Laut lachend', 'betraten', 'die Absolventen', 'den Festsaal der Universität.'],
    correctOrder: ['Laut lachend', 'betraten', 'die Absolventen', 'den Festsaal der Universität.'],
    correctAnswer: ['Laut lachend', 'betraten', 'die Absolventen', 'den Festsaal der Universität.'],
    explanation: 'Das Partizip I "Laut lachend" beschreibt als Modalangabe die Art und Weise des Eintretens.',
    tags: ['Partizip I', 'Gehobener Stil'],
    timeLimit: 20,
  },
  {
    id: 'B2-SR-0012',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Einschränkung insofern... als',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die restriktive Gefügestruktur:',
    words: ['Das Ergebnis überrascht,', 'insofern', 'als', 'niemand', 'damit gerechnet hatte.'],
    correctOrder: ['Das Ergebnis überrascht,', 'insofern', 'als', 'niemand', 'damit gerechnet hatte.'],
    correctAnswer: ['Das Ergebnis überrascht,', 'insofern', 'als', 'niemand', 'damit gerechnet hatte.'],
    explanation: '"insofern als" schränkt die Aussage des Hauptsatzes präzisierend ein.',
    tags: ['Konnektoren', 'Einschränkung'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0013',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Passiv Zustand vs Vorgang',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Zustandspassiv-Satz:',
    words: ['Alle wichtigen Dokumente', 'sind', 'bereits', 'sorgfältig archiviert.'],
    correctOrder: ['Alle wichtigen Dokumente', 'sind', 'bereits', 'sorgfältig archiviert.'],
    correctAnswer: ['Alle wichtigen Dokumente', 'sind', 'bereits', 'sorgfältig archiviert.'],
    explanation: 'Zustandspassiv: "sein" + Partizip II ("sind ... archiviert").',
    tags: ['Zustandspassiv', 'Büro'],
    timeLimit: 20,
  },
  {
    id: 'B2-SR-0014',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Argumentation Strukturierung',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Einleitungssatz einer formalen Argumentation:',
    words: ['Ein zentraler Aspekt', 'dieser Debatte', 'besteht', 'in der nachhaltigen Finanzierung.'],
    correctOrder: ['Ein zentraler Aspekt', 'dieser Debatte', 'besteht', 'in der nachhaltigen Finanzierung.'],
    correctAnswer: ['Ein zentraler Aspekt', 'dieser Debatte', 'besteht', 'in der nachhaltigen Finanzierung.'],
    explanation: '"bestehen in + Dativ" führt die wesentliche Komponente des Themas an.',
    tags: ['Argumentation', 'Debatte'],
    timeLimit: 20,
  },
  {
    id: 'B2-SR-0015',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Nominalstil Umformung',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz im gehobenen Nominalstil:',
    words: ['Die kontinuierliche Steigerung der Produktivität', 'steht', 'im Mittelpunkt der Strategie.'],
    correctOrder: ['Die kontinuierliche Steigerung der Produktivität', 'steht', 'im Mittelpunkt der Strategie.'],
    correctAnswer: ['Die kontinuierliche Steigerung der Produktivität', 'steht', 'im Mittelpunkt der Strategie.'],
    explanation: 'Subjekt im Nominalstil mit Genitivattribut ("der Produktivität") -> Prädikat "steht im Mittelpunkt".',
    tags: ['Nominalstil', 'Management'],
    timeLimit: 20,
  },

  // =========================================================================
  // 🧠 B2: WORTSCHATZ-DUELL (20 Questions: 6 EASY, 10 MEDIUM, 4 HARD)
  // =========================================================================
  {
    id: 'B2-WD-0001',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wissenschaft & Innovation',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'bahnbrechend',
    focusWord: 'bahnbrechend',
    question: 'Was bedeutet das Adjektiv "bahnbrechend" (z.B. eine bahnbrechende Entdeckung)?',
    options: ['Groundbreaking / Revolutionary / Pioneering', 'Destructive (zerstörerisch)', 'Traditional (herkömmlich)', 'Boring and insignificant'],
    correctAnswer: 'Groundbreaking / Revolutionary / Pioneering',
    explanation: '"bahnbrechend" beschreibt Neuerungen, die völlig neue Wege und Erkenntnisse eröffnen.',
    tags: ['Wissenschaft', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0002',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Soziologie & Wandel',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der demografische Wandel',
    focusWord: 'der demografische Wandel',
    question: 'Was bezeichnet der Begriff "demografischer Wandel"?',
    options: ['Changes in population age structure and birth rates', 'Climate fluctuation', 'Technological changeover', 'Currency devaluation'],
    correctAnswer: 'Changes in population age structure and birth rates',
    explanation: 'Demografischer Wandel beschreibt die Veränderung der Altersstruktur (Überalterung) einer Gesellschaft.',
    tags: ['Gesellschaft', 'Demografie'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0003',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Arbeitsmarkt',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Fachkräftemangel',
    focusWord: 'der Fachkräftemangel',
    question: 'Was versteht man unter "Fachkräftemangel"?',
    options: ['Shortage of skilled labor / qualified workers', 'High unemployment', 'Lack of office materials', 'Surplus of graduates'],
    correctAnswer: 'Shortage of skilled labor / qualified workers',
    explanation: 'Fachkräftemangel herrscht, wenn Unternehmen offene Stellen nicht mit qualifiziertem Personal besetzen können.',
    tags: ['Wirtschaft', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0004',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Technik & KI',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Algorithmus',
    focusWord: 'der Algorithmus',
    question: 'Was ist "ein Algorithmus"?',
    options: ['A step-by-step computational procedure or set of rules', 'A hardware cable', 'A computer monitor', 'A physical hard drive'],
    correctAnswer: 'A step-by-step computational procedure or set of rules',
    explanation: 'Ein Algorithmus ist eine eindeutige Handlungsvorschrift zur automatisierten Lösung von Problemen.',
    tags: ['Informatik', 'Technologie'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0005',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Finanzen',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Konjunktur',
    focusWord: 'die Konjunktur',
    question: 'Was beschreibt "die Konjunktur" in der Volkswirtschaft?',
    options: ['The cyclical economic situation and business cycle phase', 'Bank bankruptcy', 'Personal savings rate', 'Stock exchange building'],
    correctAnswer: 'The cyclical economic situation and business cycle phase',
    explanation: 'Die Konjunktur spiegelt die gesamtwirtschaftliche Lage (Aufschwung, Boom, Rezession, Tief) wider.',
    tags: ['Wirtschaft', 'Finanzen'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0006',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Recht & Ethik',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Integrität',
    focusWord: 'die Integrität',
    question: 'Was bedeutet persönliche oder berufliche "Integrität"?',
    options: ['Moral uprightness / Honesty / Adherence to ethical values', 'Aggressive ambition', 'Financial wealth', 'Physical fitness'],
    correctAnswer: 'Moral uprightness / Honesty / Adherence to ethical values',
    explanation: 'Integrität bedeutet moralische Unbestechlichkeit und Übereinstimmung von Werten und Handeln.',
    tags: ['Ethik', 'Persönlichkeit'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0007',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Medien & Kommunikation',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Zensur',
    focusWord: 'die Zensur',
    question: 'Was bedeutet staatliche "Zensur"?',
    options: ['Suppression or control of speech, public communication, or information', 'Educational grading system', 'Publishing promotion', 'Journalistic award'],
    correctAnswer: 'Suppression or control of speech, public communication, or information',
    explanation: 'Zensur ist die behördliche Kontrolle und Unterdrückung von Medien, Meinungen oder Kunst.',
    tags: ['Medien', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0008',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Philosophie & Argumentation',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'plausibel',
    focusWord: 'plausibel',
    question: 'Was bedeutet das Adjektiv "plausibel" (z.B. eine plausible Erklärung)?',
    options: ['Reasonable / Comprehensible / Credible', 'Completely absurd', 'Extremely complicated', 'Factually proven false'],
    correctAnswer: 'Reasonable / Comprehensible / Credible',
    explanation: '"plausibel" bedeutet einleuchtend, nachvollziehbar und glaubhaft.',
    tags: ['Argumentation', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0009',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Umwelt & Klima',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Biodiversität',
    focusWord: 'die Biodiversität',
    question: 'Was ist "die Biodiversität / Artenvielfalt"?',
    options: ['Biological diversity / Variety of life species and ecosystems', 'Genetically modified food', 'Chemical soil degradation', 'Greenhouse gas emissions'],
    correctAnswer: 'Biological diversity / Variety of life species and ecosystems',
    explanation: 'Biodiversität umfasst die Vielfalt aller Tier- und Pflanzenarten sowie Ökosysteme.',
    tags: ['Umwelt', 'Biologie'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0010',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Bildung & Forschung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Dissertation',
    focusWord: 'die Dissertation',
    question: 'Was ist "die Dissertation / Doktorarbeit"?',
    options: ['Scholarly doctoral thesis required for PhD degree', 'High school diploma exam', 'Short homework essay', 'Class attendance record'],
    correctAnswer: 'Scholarly doctoral thesis required for PhD degree',
    explanation: 'Eine Dissertation ist die wissenschaftliche Forschungsarbeit zur Erlangung des Doktortitels.',
    tags: ['Universität', 'Wissenschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0011',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Psychologie & Gesundheit',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Burnout-Syndrom',
    focusWord: 'das Burnout-Syndrom',
    question: 'Was kennzeichnet das "Burnout-Syndrom"?',
    options: ['State of chronic emotional and physical workplace exhaustion', 'A temporary headache', 'High athletic performance', 'Joyful motivation'],
    correctAnswer: 'State of chronic emotional and physical workplace exhaustion',
    explanation: 'Burnout ist ein Zustand tiefer beruflicher und psychischer Erschöpfung.',
    tags: ['Gesundheit', 'Arbeit', 'Psychologie'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0012',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Handel',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Monopol',
    focusWord: 'das Monopol',
    question: 'Was ist ein wirtschaftliches "Monopol"?',
    options: ['Exclusive control of the supply or trade in a good by a single provider', 'Free fair competition among many sellers', 'Government tax deduction', 'Consumer cooperative'],
    correctAnswer: 'Exclusive control of the supply or trade in a good by a single provider',
    explanation: 'Ein Monopolist beherrscht als einziger Anbieter den gesamten Markt ohne Wettbewerb.',
    tags: ['Wirtschaft', 'Markt'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0013',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kommunikation & Rhetorik',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'eloquent',
    focusWord: 'eloquent',
    question: 'Wie drückt sich eine Person aus, die "eloquent" ist?',
    options: ['Fluent, persuasive, and articulate in speech', 'Hesitant, stuttering, and insecure', 'Rude and aggressive', 'Silent and introverted'],
    correctAnswer: 'Fluent, persuasive, and articulate in speech',
    explanation: 'Eloquent bedeutet redegewandt, sprachmächtig und ausdrucksstark.',
    tags: ['Rhetorik', 'Persönlichkeit'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0014',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Recht & Justiz',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Urteil',
    focusWord: 'das Urteil',
    question: 'Welches Verb bildet mit "ein Urteil" die feste juristische Kollokation?',
    options: ['fällen / verkünden (to pass/deliver a verdict)', 'kochen', 'backen', 'singen'],
    correctAnswer: 'fällen / verkünden (to pass/deliver a verdict)',
    explanation: 'Vor Gericht heißt es fest: "ein Urteil fällen" oder "ein Urteil verkünden".',
    tags: ['Recht', 'Kollokation'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0015',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Technologie & Fortschritt',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Automatisierung',
    focusWord: 'die Automatisierung',
    question: 'Was bedeutet "die Automatisierung von Prozessen"?',
    options: ['Transfer of tasks to self-operating machines and software', 'Manual hand craftsmanship', 'Reduction of digital tools', 'Complete shutdown'],
    correctAnswer: 'Transfer of tasks to self-operating machines and software',
    explanation: 'Automatisierung überträgt Arbeitsprozesse auf selbsttätig ablaufende Systeme.',
    tags: ['Technologie', 'Industrie'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0016',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Politik & Internationale Beziehungen',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Souveränität',
    focusWord: 'die Souveränität',
    question: 'Was bezeichnet staatliche "Souveränität"?',
    options: ['Supreme independent authority and self-governance of a state', 'Economic dependence on foreign aid', 'Military surrender', 'Border dispute'],
    correctAnswer: 'Supreme independent authority and self-governance of a state',
    explanation: 'Souveränität ist die Unabhängigkeit und Selbstbestimmung eines Staates.',
    tags: ['Politik', 'Recht'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0017',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wissenschaft & Daten',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'empirisch',
    focusWord: 'empirisch',
    question: 'Was bedeutet der Begriff "empirische Forschung"?',
    options: ['Research based on systematic observation and practical experiments', 'Purely theoretical speculation without data', 'Historical fiction', 'Philosophical daydreaming'],
    correctAnswer: 'Research based on systematic observation and practical experiments',
    explanation: 'Empirische Forschung basiert auf gezielten Messungen, Beobachtungen und Datenerhebungen.',
    tags: ['Wissenschaft', 'Methoden'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0018',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Charakter & Haltung',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'akribisch',
    focusWord: 'akribisch',
    question: 'Was bedeutet es, eine Aufgabe "akribisch" zu erledigen?',
    options: ['Meticulously / With extreme precision and attention to detail', 'Carelessly and hurriedly', 'Superficially and poorly', 'Slowly and reluctantly'],
    correctAnswer: 'Meticulously / With extreme precision and attention to detail',
    explanation: 'Akribisch bedeutet überaus sorgfältig, gründlich und detailgenau.',
    tags: ['Adjektive', 'Arbeitsweise'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0019',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Finanzen & Investition',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Rendite',
    focusWord: 'die Rendite',
    question: 'Was ist "die Rendite" bei einer Geldanlage?',
    options: ['The percentage return / profit generated on invested capital', 'The initial investment amount', 'The account management fee', 'A tax penalty'],
    correctAnswer: 'The percentage return / profit generated on invested capital',
    explanation: 'Die Rendite gibt den Gesamtertrag eines eingesetzten Kapitals in Prozent an.',
    tags: ['Finanzen', 'Investition'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0020',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Medien & Fake News',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Desinformation',
    focusWord: 'die Desinformation',
    question: 'Was ist "Desinformation"?',
    options: ['Deliberately false or misleading information spread to deceive', 'Objective news reporting', 'Academic peer review', 'Government transparency portal'],
    correctAnswer: 'Deliberately false or misleading information spread to deceive',
    explanation: 'Desinformation ist die gezielte Verbreitung falscher Angaben zur Täuschung der Öffentlichkeit.',
    tags: ['Medien', 'Gesellschaft'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ B2: WAS BIN ICH? (15 Questions: 5 EASY, 8 MEDIUM, 2 HARD)
  // =========================================================================
  {
    id: 'B2-WB-0001',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Zukunftstechnologie & KI',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das moderne technologische System:',
    clues: [
      'Hinweis 1: Ich basiere auf künstlichen neuronalen Netzen und riesigen Text- und Datenmengen.',
      'Hinweis 2: Ich kann eigenständig Software-Code schreiben, komplexe Texte zusammenfassen und Bilder generieren.',
      'Hinweis 3: Bekannte Vertreter von mir sind ChatGPT, Claude und Gemini.',
    ],
    options: ['Generative Künstliche Intelligenz (Large Language Model)', 'Ein traditioneller Taschenrechner', 'Ein BIOS-Chip', 'Ein lokales Textverarbeitungsprogramm'],
    correctAnswer: 'Generative Künstliche Intelligenz (Large Language Model)',
    explanation: 'Generative KI (LLMs) erzeugt auf Basis von Trainingsdaten eigenständig Texte, Code und Medien.',
    tags: ['Technologie', 'KI', 'Innovation'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0002',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Umwelt & Wirtschaft',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das zukunftsweisende Wirtschaftsmodell:',
    clues: [
      'Hinweis 1: Ich stehe im direkten Gegensatz zur traditionellen "Wegwerfgesellschaft".',
      'Hinweis 2: Bei mir werden Rohstoffe repariert, wiederverwendet, aufgearbeitet und recycelt.',
      'Hinweis 3: Mein Ziel ist es, den Abfall und Ressourcenverbrauch gegen null zu senken.',
    ],
    options: ['Die Kreislaufwirtschaft (Circular Economy)', 'Die Planwirtschaft', 'Die Schwerindustrie', 'Der Turbokapitalismus'],
    correctAnswer: 'Die Kreislaufwirtschaft (Circular Economy)',
    explanation: 'Die Kreislaufwirtschaft hält Ressourcen durch Recycling und Wiederverwendung im System.',
    tags: ['Umwelt', 'Wirtschaft', 'Nachhaltigkeit'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0003',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Politik & Verfassung',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das höchste deutsche Verfassungsorgan der Rechtsprechung:',
    clues: [
      'Hinweis 1: Mein Sitz ist in Karlsruhe und meine Richter tragen rote Roben.',
      'Hinweis 2: Ich wache streng über die Einhaltung des deutschen Grundgesetzes.',
      'Hinweis 3: Wenn ein Gesetz verfassungswidrig ist, kann ich es für nichtig erklären.',
    ],
    options: ['Das Bundesverfassungsgericht', 'Der Bundesgerichtshof', 'Das Bundesverwaltungsgericht', 'Das Europäische Parlament'],
    correctAnswer: 'Das Bundesverfassungsgericht',
    explanation: 'Das Bundesverfassungsgericht in Karlsruhe ist der oberste Hüter der deutschen Verfassung.',
    tags: ['Recht', 'Verfassung', 'Landeskunde'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0004',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Sozialwissenschaft & Ungleichheit',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das soziologische Phänomen am Arbeitsmarkt:',
    clues: [
      'Hinweis 1: Ich bin eine unsichtbare, aber sehr wirksame Barriere in Unternehmen.',
      'Hinweis 2: Ich verhindere, dass qualifizierte Frauen oder Minderheiten in die obersten Führungsetagen aufsteigen.',
      'Hinweis 3: Im Englischen und Deutschen nennt man mich die "gläserne ...".',
    ],
    options: ['Die gläserne Decke (Glass Ceiling)', 'Der Fachkräftemangel', 'Die Probezeit', 'Die Abfindung'],
    correctAnswer: 'Die gläserne Decke (Glass Ceiling)',
    explanation: 'Die gläserne Decke beschreibt informelle Aufstiegsbarrieren für Frauen in Führungspositionen.',
    tags: ['Gesellschaft', 'Arbeitsmarkt', 'Gleichberechtigung'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0005',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Energiewende & Chemie',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Energieträger der Zukunft:',
    clues: [
      'Hinweis 1: Ich bin das chemische Element mit dem Symbol H und der Ordnungszahl 1.',
      'Hinweis 2: Wenn ich mit erneuerbarem Strom per Elektrolyse erzeugt werde, nennt man mich "grün".',
      'Hinweis 3: Bei meiner Verbrennung mit Sauerstoff entsteht als einziges Abfallprodukt reines Wasser.',
    ],
    options: ['Der Wasserstoff (Green Hydrogen)', 'Das Erdgas (Methan)', 'Das Rohöl', 'Das Kohlenstoffdioxid'],
    correctAnswer: 'Der Wasserstoff (Green Hydrogen)',
    explanation: 'Grüner Wasserstoff gilt als Schlüsselenergieträger für die Dekarbonisierung der Industrie.',
    tags: ['Energie', 'Klimaschutz', 'Wissenschaft'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0006',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Arbeitswelt & New Work',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das moderne Arbeitsmodell:',
    clues: [
      'Hinweis 1: Die Mitarbeiter teilen ihre Arbeitszeit flexibel zwischen Büro und Homeoffice auf.',
      'Hinweis 2: Es kombiniert die Vorteile von persönlicher Team-Zusammenarbeit und konzentriertem Arbeiten daheim.',
      'Hinweis 3: Viele moderne Firmen haben seit der Pandemie dieses duale Modell dauerhaft eingeführt.',
    ],
    options: ['Das hybride Arbeiten (Hybrid Work)', 'Die Schichtarbeit', 'Die Kurzarbeit', 'Die Zeitarbeit'],
    correctAnswer: 'Das hybride Arbeiten (Hybrid Work)',
    explanation: 'Hybrides Arbeiten verbindet Präsenzpflicht im Büro mit mobiler Heimarbeit.',
    tags: ['Arbeit', 'New Work'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0007',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Psychologie & Kognition',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das psychologische Denkphänomen:',
    clues: [
      'Hinweis 1: Ich führe dazu, dass Menschen nur Informationen wahrnehmen, die ihre bestehende Meinung bestätigen.',
      'Hinweis 2: Widersprüchliche Fakten und Gegenargumente werden unbewusst ignoriert oder abgewertet.',
      'Hinweis 3: In der Kognitionspsychologie nennt man mich den "Bestätigungsfehler".',
    ],
    options: ['Der Bestätigungsfehler (Confirmation Bias)', 'Das Stockholm-Syndrom', 'Der Placebo-Effekt', 'Die Amnesie'],
    correctAnswer: 'Der Bestätigungsfehler (Confirmation Bias)',
    explanation: 'Der Bestätigungsfehler beschreibt die Neigung, eigene Hypothesen selektiv zu stützen.',
    tags: ['Psychologie', 'Kritisches Denken'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0008',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Finanzen & Kryptografie',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Technologie:',
    clues: [
      'Hinweis 1: Ich bin eine dezentrale, manipulationssichere digitale Datenbankstruktur.',
      'Hinweis 2: Datensätze werden in chronologischen, kryptografisch verknüpften Blöcken gespeichert.',
      'Hinweis 3: Ich bilde das technologische Fundament für Kryptowährungen wie Bitcoin und Ethereum.',
    ],
    options: ['Die Blockchain-Technologie', 'Ein USB-Stick', 'Ein FTP-Server', 'Ein lokales Excel-Dokument'],
    correctAnswer: 'Die Blockchain-Technologie',
    explanation: 'Die Blockchain ist ein verteiltes Register, das Transaktionen manipulationssicher speichert.',
    tags: ['Technologie', 'Finanzen'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0009',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Bildung & Globalisierung',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das bekannte europäische Bildungsprogramm:',
    clues: [
      'Hinweis 1: Ich wurde nach einem berühmten niederländischen Renaissance-Humanisten benannt.',
      'Hinweis 2: Ich ermögliche es europäischen Universitätsstudenten, ein oder zwei Semester im Ausland zu studieren.',
      'Hinweis 3: Meine Stipendien fördern den interkulturellen Austausch und das Erlernen von Fremdsprachen.',
    ],
    options: ['Das Erasmus+-Programm', 'Das Abitur', 'Das DAAD-Alumnitreffen', 'Der Numerus Clausus'],
    correctAnswer: 'Das Erasmus+-Programm',
    explanation: 'Erasmus+ fördert europaweite Mobilität und Auslandsaufenthalte von Studierenden.',
    tags: ['Bildung', 'Europa', 'Universität'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0010',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Stadtplanung & Mobilität',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das moderne Stadtplanungskonzept:',
    clues: [
      'Hinweis 1: Alle wichtigen Ziele des täglichen Bedarfs (Arbeit, Einkaufen, Arzt, Schule, Freizeit) liegen in unmittelbarer Nähe.',
      'Hinweis 2: Man kann sie alle innerhalb einer Viertelstunde bequem zu Fuß oder mit dem Fahrrad erreichen.',
      'Hinweis 3: Es reduziert Autoverkehr und verbessert die Lebensqualität in Großstädten.',
    ],
    options: ['Die 15-Minuten-Stadt (15-Minute City)', 'Die reine Schlafstadt', 'Das Gewerbegebiet', 'Die Autogerechte Stadt'],
    correctAnswer: 'Die 15-Minuten-Stadt (15-Minute City)',
    explanation: 'Das 15-Minuten-Stadt-Konzept garantiert Nahversorgung und kurze Wege ohne Auto.',
    tags: ['Stadtplanung', 'Nachhaltigkeit'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0011',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Medien & Manipulation',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das täuschend echte Medienphänomen:',
    clues: [
      'Hinweis 1: Mit Künstlicher Intelligenz werden Gesichter und Stimmen von Politikern oder Prominenten fotorealistisch imitiert.',
      'Hinweis 2: In gefälschten Videos sagen diese Personen Dinge, die sie in der Realität nie gesagt haben.',
      'Hinweis 3: Sie stellen eine erhebliche Gefahr für Wahlen, Demokratie und das Vertrauen in Medien dar.',
    ],
    options: ['Das Deepfake', 'Der Screenshot', 'Das Fotoalbum', 'Der Zeitungsartikel'],
    correctAnswer: 'Das Deepfake',
    explanation: 'Deepfakes sind KI-generierte Medienmanipulationen, die menschliches Aussehen und Stimme fälschen.',
    tags: ['Medien', 'KI', 'Ethik'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0012',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Medizin & Genetik',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das molekularbiologische Präzisionswerkzeug:',
    clues: [
      'Hinweis 1: In der Wissenschaft nennt man mich die "Genschere".',
      'Hinweis 2: Mit mir können Forscher gezielt einzelne Gene im Erbgut von Pflanzen, Tieren und Menschen verändern.',
      'Hinweis 3: Die Entdeckerinnen Emmanuelle Charpentier und Jennifer Doudna erhielten dafür den Nobelpreis.',
    ],
    options: ['CRISPR/Cas9', 'Das Mikroskop', 'Das Stethoskop', 'Das Ultraschallgerät'],
    correctAnswer: 'CRISPR/Cas9',
    explanation: 'CRISPR/Cas9 ist eine revolutionäre molekularbiologische Methode zum Genome Editing.',
    tags: ['Wissenschaft', 'Biologie', 'Medizin'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0013',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Wirtschaft & Unternehmensgründung',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die Art des neu gegründeten Unternehmens:',
    clues: [
      'Hinweis 1: Ich bin ein junges, innovatives Unternehmen mit einem hochgradig skalierbaren Geschäftsmodell.',
      'Hinweis 2: Ich suche oft nach Risikokapital (Venture Capital) von Investoren, um extrem schnell zu wachsen.',
      'Hinweis 3: Wenn mein Marktwert über eine Milliarde US-Dollar steigt, nennt man mich ein "Einhorn" (Unicorn).',
    ],
    options: ['Das Start-up', 'Das Handwerksunternehmen', 'Die Behörde', 'Das Staatsunternehmen'],
    correctAnswer: 'Das Start-up',
    explanation: 'Ein Start-up ist eine technologie- oder innovationsgetriebene Neugründung mit starkem Wachstumspotenzial.',
    tags: ['Wirtschaft', 'Innovation'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0014',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Klima & Geowissenschaften',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das arktische Naturphänomen:',
    clues: [
      'Hinweis 1: Ich bin arktischer Boden in Sibirien oder Alaska, der seit vielen Jahrtausenden durchgehend tiefgefroren ist.',
      'Hinweis 2: In mir sind gigantische Mengen an organischem Kohlenstoff und Methangas gebunden.',
      'Hinweis 3: Wenn ich durch die Erderwärmung auftaue, beschleunige ich den globalen Klimawandel drastisch.',
    ],
    options: ['Der Permafrostboden', 'Die Wüste', 'Der Regenwald', 'Das Korallenriff'],
    correctAnswer: 'Der Permafrostboden',
    explanation: 'Das Auftauen des Permafrostbodens setzt erhebliche Mengen an Treibhausgasen (Methan) frei.',
    tags: ['Klima', 'Geowissenschaften'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0015',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Gesellschaft & Alter',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das ethische und soziologische Konzept:',
    clues: [
      'Hinweis 1: Es fordert faire Lebensbedingungen und den Schutz von Ressourcen für heute und morgen.',
      'Hinweis 2: Die heutige Generation darf nicht auf Kosten künftiger Kinder und Enkelkinder leben.',
      'Hinweis 3: Im Grundgesetz und im Klimarecht ist dieser Grundsatz als Schutzpflicht verankert.',
    ],
    options: ['Die Generationengerechtigkeit', 'Die Altersdiskriminierung', 'Der Generationenkonflikt', 'Die Rente mit 63'],
    correctAnswer: 'Die Generationengerechtigkeit',
    explanation: 'Generationengerechtigkeit verlangt ein faires Gleichgewicht zwischen den Interessen heutiger und zukünftiger Generationen.',
    tags: ['Ethik', 'Recht', 'Nachhaltigkeit'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ B2: TEAM BATTLE (15 Questions: 9 EASY, 5 MEDIUM, 1 HARD)
  // =========================================================================
  {
    id: 'B2-TB-0001',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Rhetorik & Debatte',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Wendung signalisiert in einer anspruchsvollen Diskussion eine differenzierte Abwägung?',
    options: ['Man muss hierbei allerdings sorgfältig zwischen Ursache und Wirkung differenzieren.', 'Das ist totaler Blödsinn.', 'Ich diskutiere nicht weiter.', 'Du liegst absolut falsch.'],
    correctAnswer: 'Man muss hierbei allerdings sorgfältig zwischen Ursache und Wirkung differenzieren.',
    explanation: '"differenzieren zwischen..." zeugt von hohem sprachlichen Register und analytischer Tiefe.',
    tags: ['Debatte', 'Rhetorik'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0002',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Formelle Einwände',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie formulieren Sie in einer geschäftlichen Verhandlung einen fundierten Einwand?',
    options: ['Gegen diesen Vorschlag hege ich gravierende Bedenken, weil...', 'Ich will das einfach nicht.', 'Schlechter Vorschlag!', 'Hören Sie auf damit.'],
    correctAnswer: 'Gegen diesen Vorschlag hege ich gravierende Bedenken, weil...',
    explanation: '"Bedenken hegen gegen..." ist eine stilistisch elegante, gehobene Formulierung.',
    tags: ['Verhandlung', 'Gehobener Stil'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0003',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Wissenschaftssprache',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches Verb passt in wissenschaftlichen Texten zu "eine Hypothese"?',
    options: ['eine Hypothese aufstellen und überprüfen', 'eine Hypothese kochen', 'eine Hypothese reparieren', 'eine Hypothese kaufen'],
    correctAnswer: 'eine Hypothese aufstellen und überprüfen',
    explanation: 'In der Wissenschaft lautet die Kollokation: "eine Hypothese aufstellen / überprüfen / verifizieren / falsifizieren".',
    tags: ['Wissenschaft', 'Kollokation'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0004',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Soziale Marktwirtschaft',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ist das Leitprinzip der "Sozialen Marktwirtschaft" in Deutschland?',
    options: ['Die Verknüpfung von freiem wirtschaftlichen Wettbewerb mit staatlichem sozialem Ausgleich', 'Reiner unregulierter Kapitalismus', 'Vollständige staatliche Planwirtschaft', 'Abschaffung aller Steuern'],
    correctAnswer: 'Die Verknüpfung von freiem wirtschaftlichen Wettbewerb mit staatlichem sozialem Ausgleich',
    explanation: 'Die Soziale Marktwirtschaft verbindet freie Marktinitiative mit sozialer Sicherung und Chancengleichheit.',
    tags: ['Wirtschaft', 'Landeskunde', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0005',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Pressefreiheit & Demokratie',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Warum werden freie Medien und Journalismus in einer Demokratie oft als "vierte Gewalt" bezeichnet?',
    options: ['Weil sie Missstände aufdecken und Politik und Wirtschaft kritisch kontrollieren', 'Weil Journalisten die Gesetze schreiben', 'Weil Medien über der Verfassung stehen', 'Weil sie von der Regierung bezahlt werden'],
    correctAnswer: 'Weil sie Missstände aufdecken und Politik und Wirtschaft kritisch kontrollieren',
    explanation: 'Als "vierte Gewalt" üben freie Medien eine unverzichtbare Kontrollfunktion gegenüber Staat und Institutionen aus.',
    tags: ['Demokratie', 'Medien'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0006',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Berufliche Verhandlung & Taktik',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was versteht man in Verhandlungen unter einer "Win-Win-Situation"?',
    options: ['Eine Einigung, bei der beide Verhandlungspartner messbare Vorteile und Nutzen erzielen', 'Dass eine Partei die andere komplett besiegt', 'Dass die Verhandlung abgebrochen wird', 'Dass beide Seiten Geld verlieren'],
    correctAnswer: 'Eine Einigung, bei der beide Verhandlungspartner messbare Vorteile und Nutzen erzielen',
    explanation: 'Eine Win-Win-Lösung schafft für alle beteiligten Parteien einen spürbaren Mehrwert.',
    tags: ['Verhandlung', 'Arbeitswelt'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0007',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Ethik & Künstliche Intelligenz',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches ethische Hauptproblem diskutieren Experten beim Einsatz autonomer KI-Entscheidungssysteme?',
    options: ['Die Gefahr von diskriminierenden Verzerrungen (Biases) und mangelnder Nachvollziehbarkeit (Blackbox)', 'Dass Computer zu viel Strom im Schlafmodus verbrauchen', 'Dass Roboter zu schnell tippen', 'Dass Algorithmen keine Pausen machen'],
    correctAnswer: 'Die Gefahr von diskriminierenden Verzerrungen (Biases) und mangelnder Nachvollziehbarkeit (Blackbox)',
    explanation: 'Verzerrte Trainingsdaten und mangelnde Transparenz bergen gravierende ethische und rechtliche Risiken.',
    tags: ['KI', 'Ethik', 'Technologie'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0008',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Arbeitsrecht Deutschland',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Was regelt das deutsche "Kündigungsschutzgesetz (KSchG)"?',
    options: ['Es schützt Arbeitnehmer in Betrieben mit mehr als 10 Mitarbeitern vor willkürlichen und ungerechtfertigten Kündigungen.', 'Es verbietet jede Kündigung für immer.', 'Es regelt die Urlaubszeiten in der Schule.', 'Es bestimmt die Preise im Supermarkt.'],
    correctAnswer: 'Es schützt Arbeitnehmer in Betrieben mit mehr als 10 Mitarbeitern vor willkürlichen und ungerechtfertigten Kündigungen.',
    explanation: 'Das KSchG verlangt soziale Rechtfertigung (personen-, verhaltens- oder betriebsbedingt) für Kündigungen.',
    tags: ['Arbeitsrecht', 'Recht'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0009',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Redewendungen gehoben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet die Redewendung: "den Teufelskreis durchbrechen"?',
    options: ['Eine Kette von sich gegenseitig verstärkenden negativen Ereignissen erfolgreich beenden', 'In die Hölle reisen', 'Einen Vertrag kündigen', 'Ein Bild malen'],
    correctAnswer: 'Eine Kette von sich gegenseitig verstärkenden negativen Ereignissen erfolgreich beenden',
    explanation: 'Ein Teufelskreis (Circulus vitiosus) ist eine Abwärtsspirale; ihn zu durchbrechen stoppt das Problem.',
    tags: ['Redewendungen', 'Gehobener Stil'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0010',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Europäische Union Institutionen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Institution vertritt die direkt von den Bürgern der Mitgliedstaaten gewählten Abgeordneten der Europäischen Union?',
    options: ['Das Europäische Parlament', 'Die Europäische Kommission', 'Der Europäische Rat', 'Der Europäische Gerichtshof'],
    correctAnswer: 'Das Europäische Parlament',
    explanation: 'Das Europäische Parlament in Straßburg und Brüssel wird alle fünf Jahre direkt von den EU-Bürgern gewählt.',
    tags: ['Europa', 'Politik', 'Institutionen'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0011',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Energiewende & Atomausstieg',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches fundamentale energiepolitische Ziel verfolgt Deutschland mit der "Energiewende"?',
    options: ['Die vollständige Umstellung der Energieversorgung auf erneuerbare Quellen und Klimaneutralität', 'Den Bau neuer Kohlekraftwerke', 'Die Verdopplung des Ölverbrauchs', 'Den Import von Atomstrom aus Übersee'],
    correctAnswer: 'Die vollständige Umstellung der Energieversorgung auf erneuerbare Quellen und Klimaneutralität',
    explanation: 'Die Energiewende transformiert das Energiesystem hin zu Sonne, Wind, Wasser und Biomasse.',
    tags: ['Klima', 'Energie', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0012',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Diplomatie & Register',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Formulierung eignet sich am besten, um Kritik auf Führungsebene diplomatisch zu äußern?',
    options: ['Hier besteht meines Erachtens noch erhebliches Optimierungspotenzial.', 'Das habt ihr komplett ruiniert.', 'Eure Arbeit ist unbrauchbar.', 'Macht das gefälligst neu!'],
    correctAnswer: 'Hier besteht meines Erachtens noch erhebliches Optimierungspotenzial.',
    explanation: '"Optimierungspotenzial" ist der klassische diplomatische Ausdruck für verbesserungswürdige Ergebnisse.',
    tags: ['Diplomatie', 'Beruf', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0013',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Literatur & Kulturgeschichte',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Epoche der deutschen Literaturgeschichte ist untrennbar mit Johann Wolfgang von Goethe und Friedrich Schiller in Weimar verbunden?',
    options: ['Die Weimarer Klassik (ca. 1786–1805)', 'Die Romantik', 'Der Naturalismus', 'Die Postmoderne'],
    correctAnswer: 'Die Weimarer Klassik (ca. 1786–1805)',
    explanation: 'Die Weimarer Klassik prägte das humanistische Bildungsideal durch Goethe und Schiller.',
    tags: ['Literatur', 'Kultur', 'Geschichte'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0014',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Unternehmensethik & CSR',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was versteht man unter "Corporate Social Responsibility (CSR)"?',
    options: ['Die freiwillige gesellschaftliche und ökologische Verantwortung von Unternehmen über gesetzliche Vorgaben hinaus', 'Die Steuervermeidung in Offshore-Zentren', 'Die maximale Ausschüttung von Dividenden an Aktionäre', 'Die Reduzierung von Mitarbeiterlöhnen'],
    correctAnswer: 'Die freiwillige gesellschaftliche und ökologische Verantwortung von Unternehmen über gesetzliche Vorgaben hinaus',
    explanation: 'CSR bezeichnet nachhaltiges Wirtschaften in ökologischer, ökonomischer und sozialer Verantwortung.',
    tags: ['Wirtschaft', 'Ethik', 'CSR'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0015',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Redewendungen & Metaphern',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet die Metapher: "in den sauren Apfel beißen"?',
    options: ['Eine unvermeidbare, unangenehme Pflicht oder Notwendigkeit überwinden und tun', 'Ungesundes Obst essen', 'Einen Streit anfangen', 'Aus dem Fenster schauen'],
    correctAnswer: 'Eine unvermeidbare, unangenehme Pflicht oder Notwendigkeit überwinden und tun',
    explanation: '"In den sauren Apfel beißen" heißt, etwas Unangenehmes zu tun, weil es unvermeidlich ist.',
    tags: ['Redewendungen', 'Sprache'],
    timeLimit: 15,
  },
];
