import { BankQuestion } from '../questionTypes.js';

/**
 * B2 Level Question Bank - Farh SprachArena
 * Levels: B2
 * Categories: Gesellschaft, Wirtschaft, Wissenschaft, Technologie, Umwelt, Politik, Bildung, Beruf, Medien, Argumentation, Redemittel, Komplexe Grammatik
 * Games: SCHNELLANTWORT, SATZ_RENNEN, WORTSCHATZ_DUELL, WAS_BIN_ICH, TEAM_BATTLE
 */
export const B2_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ B2: SCHNELLANTWORT
  // =========================================================================
  {
    id: 'B2-SA-0001',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Verbindungen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Nach intensiver Beratung hat der Vorstand eine folgenschwere Entscheidung ___.',
    options: ['getroffen', 'gemacht', 'genommen', 'gestellt'],
    correctAnswer: 'getroffen',
    explanation: 'Feste Nomen-Verb-Verbindung: "eine Entscheidung treffen" (beschließen).',
    tags: ['Nomen-Verb-Verbindung', 'Gehobene Sprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0002',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Passiv-Ersatzformen (sein + zu + Infinitiv)',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Diese streng vertraulichen Daten sind unverzüglich ___ .',
    options: ['zu löschen', 'löschend', 'gelöscht haben', 'zu gelöscht'],
    correctAnswer: 'zu löschen',
    explanation: '"sein + zu + Infinitiv" drückt eine Notwendigkeit im Passivsinn aus (müssen gelöscht werden).',
    tags: ['Passiv-Ersatzform', 'Modalfaktor'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0003',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Doppelkonnektoren (je...desto)',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Je intensiver man sich auf die Verhandlung vorbereitet, ___ souveräner tritt man auf.',
    options: ['desto', 'als', 'wie', 'umso mehr'],
    correctAnswer: 'desto',
    explanation: 'Proportionale Konnektoren: "je + Komparativ (Nebensatz) ... desto/umso + Komparativ (Hauptsatz)".',
    tags: ['Konnektoren', 'Proportionalität'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0004',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nomen-Verb-Gefüge mit Präposition',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Bei der strategischen Planung müssen wir auch unvorhersehbare Risiken in Betracht ___ .',
    options: ['ziehen', 'nehmen', 'setzen', 'legen'],
    correctAnswer: 'ziehen',
    explanation: '"etwas in Betracht ziehen" = etwas berücksichtigen / erwägen.',
    tags: ['Nomen-Verb-Verbindung', 'Wirtschaftssprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0005',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Partizip I als Adjektiv',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die stetig ___ Nachfrage nach erneuerbaren Energien stellt die Netze vor Herausforderungen.',
    options: ['steigende', 'gestiegene', 'steigernde', 'gestiegen'],
    correctAnswer: 'steigende',
    explanation: 'Partizip I ("steigend") drückt einen aktiven, andauernden Prozess aus und wird als Adjektiv dekliniert.',
    tags: ['Partizip I', 'Attribut'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0006',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konzessivkonnektoren (ungeachtet)',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ungeachtet ___ anhaltenden wirtschaftlichen Krisen expandiert das Technologieunternehmen.',
    options: ['der', 'den', 'des', 'dem'],
    correctAnswer: 'der',
    explanation: '"Ungeachtet" verlangt den Genitiv Plural: "ungeachtet der Krisen".',
    tags: ['Präpositionen', 'Genitiv', 'Konzessiv'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0007',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konjunktiv I in der Presse',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Laut Regierungsbericht ___ die Inflation im kommenden Quartal deutlich abnehmen.',
    options: ['werde', 'wird', 'würde', 'geworden'],
    correctAnswer: 'werde',
    explanation: 'Indirekte Rede im journalistischen Stil: Konjunktiv I 3. Person ("werde").',
    tags: ['Konjunktiv I', 'Mediensprache'],
    timeLimit: 15,
  },
  {
    id: 'B2-SA-0008',
    level: 'B2',
    gameType: 'SCHNELLANTWORT',
    category: 'Redemittel zur Argumentation',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Aus diesem Grund ist die Behauptung des Gutachters ___ .',
    options: ['stichhaltig', 'stichlos', 'gestochen', 'stichend'],
    correctAnswer: 'stichhaltig',
    explanation: '"stichhaltig" = fundiert, überzeugend und logisch begründet.',
    tags: ['Wortschatz', 'Argumentation'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 B2: SATZ-RENNEN
  // =========================================================================
  {
    id: 'B2-SR-0001',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Erweitertes Partizipialattribut',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bringe das erweiterte Partizipialattribut in die korrekte Satzstruktur:',
    words: ['Der von Experten', 'sorgfältig ausgearbeitete', 'Sanierungsplan', 'wurde gestern', 'einstimmig beschlossen.'],
    correctOrder: ['Der von Experten', 'sorgfältig ausgearbeitete', 'Sanierungsplan', 'wurde gestern', 'einstimmig beschlossen.'],
    correctAnswer: ['Der von Experten', 'sorgfältig ausgearbeitete', 'Sanierungsplan', 'wurde gestern', 'einstimmig beschlossen.'],
    explanation: 'Erweiterte Attribute stehen direkt zwischen Artikel ("Der") und Nomen ("Sanierungsplan").',
    tags: ['Partizipialattribut', 'Komplexe Syntax'],
    timeLimit: 30,
  },
  {
    id: 'B2-SR-0002',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Modalsatz mit indem',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit der modalen Konjunktion "indem" in die richtige Ordnung:',
    words: ['Man spart Energie,', 'indem man', 'elektrische Geräte', 'vollständig abschaltet.'],
    correctOrder: ['Man spart Energie,', 'indem man', 'elektrische Geräte', 'vollständig abschaltet.'],
    correctAnswer: ['Man spart Energie,', 'indem man', 'elektrische Geräte', 'vollständig abschaltet.'],
    explanation: '"indem" leitet einen Modalsatz (Mittel / Methode) mit finitem Verb am Ende ein.',
    tags: ['Modalsatz', 'Nebensatz'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0003',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Passiv mit Modalverb im Perfekt',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde das Passiv mit Modalverb im Perfekt (Ersatzinfinitiv):',
    words: ['Der Vertrag', 'hat gestern', 'fristgerecht', 'unterzeichnet werden', 'müssen.'],
    correctOrder: ['Der Vertrag', 'hat gestern', 'fristgerecht', 'unterzeichnet werden', 'müssen.'],
    correctAnswer: ['Der Vertrag', 'hat gestern', 'fristgerecht', 'unterzeichnet werden', 'müssen.'],
    explanation: 'Perfekt Passiv mit Modalverb: "hat + Partizip II + werden + Modalverb im Infinitiv (Ersatzinfinitiv)".',
    tags: ['Passiv', 'Ersatzinfinitiv'],
    timeLimit: 30,
  },
  {
    id: 'B2-SR-0004',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Redemittel für Diskussionen',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe das gehobene Redemittel zur Meinungsäußerung in die richtige Form:',
    words: ['Ich stehe auf dem Standpunkt,', 'dass diese Maßnahme', 'unumgänglich ist.'],
    correctOrder: ['Ich stehe auf dem Standpunkt,', 'dass diese Maßnahme', 'unumgänglich ist.'],
    correctAnswer: ['Ich stehe auf dem Standpunkt,', 'dass diese Maßnahme', 'unumgänglich ist.'],
    explanation: '"Auf dem Standpunkt stehen, dass ..." drückt eine fundierte persönliche Überzeugung aus.',
    tags: ['Redemittel', 'Argumentation'],
    timeLimit: 25,
  },
  {
    id: 'B2-SR-0005',
    level: 'B2',
    gameType: 'SATZ_RENNEN',
    category: 'Konsekutivsatz mit sodass',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Konsekutivsatz in die richtige Reihenfolge:',
    words: ['Der Vortrag war sehr lehrreich,', 'sodass alle Zuhörer', 'begeistert applaudierten.'],
    correctOrder: ['Der Vortrag war sehr lehrreich,', 'sodass alle Zuhörer', 'begeistert applaudierten.'],
    correctAnswer: ['Der Vortrag war sehr lehrreich,', 'sodass alle Zuhörer', 'begeistert applaudierten.'],
    explanation: '"sodass" leitet einen Nebensatz ein, der die logische Folge ausdrückt.',
    tags: ['Konsekutivsatz', 'Syntax'],
    timeLimit: 25,
  },

  // =========================================================================
  // 🧠 B2: WORTSCHATZ-DUELL
  // =========================================================================
  {
    id: 'B2-WD-0001',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Finanzen',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Nachhaltigkeit',
    focusWord: 'die Nachhaltigkeit',
    question: 'Was bezeichnet der Begriff "die Nachhaltigkeit"?',
    options: ['Sustainability / Ecological balance', 'Short-term profitability', 'Tax exemption', 'Industrial manufacturing'],
    correctAnswer: 'Sustainability / Ecological balance',
    explanation: 'Nachhaltigkeit ist die zukunftsfähige Nutzung von Ressourcen.',
    tags: ['Wirtschaft', 'Umwelt'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0002',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wissenschaft & Forschung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Hypothese aufstellen',
    focusWord: 'die Hypothese aufstellen',
    question: 'Was bedeutet das wissenschaftliche Redemittel "eine Hypothese aufstellen"?',
    options: ['To formulate / put forward a research hypothesis', 'To refute scientific evidence', 'To publish research results', 'To conduct laboratory tests'],
    correctAnswer: 'To formulate / put forward a research hypothesis',
    explanation: 'Eine Hypothese aufstellen = eine begründete Annahme formulieren.',
    tags: ['Wissenschaft', 'Fachwortschatz'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0003',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Verträge',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Rahmenbedingungen',
    focusWord: 'die Rahmenbedingungen',
    question: 'Was versteht man unter "den Rahmenbedingungen"?',
    options: ['General framework / prevailing parameters & conditions', 'Strict budgetary restrictions', 'Building window structures', 'Hardware architecture'],
    correctAnswer: 'General framework / prevailing parameters & conditions',
    explanation: 'Rahmenbedingungen sind die grundlegenden rechtlichen, gesellschaftlichen oder wirtschaftlichen Voraussetzungen.',
    tags: ['Politik', 'Wirtschaft'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0004',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Redewendungen & Nuancen',
    difficulty: 'HARD',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'To take into consideration / account (أخذ بعين الاعتبار)',
    focusWord: 'To take into consideration / account (أخذ بعين الاعتبار)',
    question: 'Welches gehobene Nomen-Verb-Gefüge bedeutet "berücksichtigen"?',
    options: ['in Betracht ziehen / Rechnung tragen', 'zur Verfügung stehen', 'infrage kommen', 'außer Acht lassen'],
    correctAnswer: 'in Betracht ziehen / Rechnung tragen',
    explanation: '"In Betracht ziehen" und "Rechnung tragen" bedeuten berücksichtigen.',
    tags: ['Nomen-Verb-Gefüge', 'Gehobenes Deutsch'],
    timeLimit: 15,
  },
  {
    id: 'B2-WD-0005',
    level: 'B2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Politik & Gesellschaft',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der gesellschaftliche Zusammenhalt',
    focusWord: 'der gesellschaftliche Zusammenhalt',
    question: 'Was bedeutet "der gesellschaftliche Zusammenhalt"?',
    options: ['Social cohesion / Solidarity in society', 'Political polarization', 'Economic inflation', 'Demographic stagnation'],
    correctAnswer: 'Social cohesion / Solidarity in society',
    explanation: 'Gesellschaftlicher Zusammenhalt ist das Miteinander und die Solidarität in der Gesellschaft.',
    tags: ['Gesellschaft', 'Soziologie'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ B2: WAS BIN ICH?
  // =========================================================================
  {
    id: 'B2-WB-0001',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Globale Umwelt & Politik',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Phänomen / Konzept:',
    clues: [
      'Hinweis 1: Ich bezeichne den menschengemachten Wandel der globalen Durchschnittstemperaturen.',
      'Hinweis 2: Ich werde durch Treibhausgase wie CO2 und Methan in der Atmosphäre verstärkt.',
      'Hinweis 3: Das Pariser Abkommen zielt darauf ab, meine Erwärmung auf 1,5 Grad zu begrenzen.',
    ],
    options: ['Der Klimawandel', 'Das Ozonloch', 'Die Kontinentaldrift', 'Die Urbanisierung'],
    correctAnswer: 'Der Klimawandel',
    explanation: 'Der Klimawandel und Treibhauseffekt sind zentrale globale Themen.',
    tags: ['Umwelt', 'Politik'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0002',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Wirtschaftswissenschaften',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten ökonomischen Begriff:',
    clues: [
      'Hinweis 1: Ich bezeichne den kontinuierlichen Anstieg des allgemeinen Preisniveaus.',
      'Hinweis 2: Infolge meiner Wirkung sinkt die reale Kaufkraft des Geldes.',
      'Hinweis 3: Zentralbanken wie die EZB versuchen, mich bei etwa 2 Prozent zu stabilisieren.',
    ],
    options: ['Die Inflation', 'Die Rezession', 'Die Deflation', 'Der Zinssatz'],
    correctAnswer: 'Die Inflation',
    explanation: 'Inflation bezeichnet die Geldentwertung durch steigende Verbraucherpreise.',
    tags: ['Wirtschaft', 'Geldpolitik'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0003',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Gesellschaft & Technologie',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Transformationsprozess:',
    clues: [
      'Hinweis 1: Ich beschreibe den Übergang von analogen Prozessen zu softwarebasierten Systemen.',
      'Hinweis 2: Cloud Computing, Big Data und Künstliche Intelligenz sind meine treibenden Kräfte.',
      'Hinweis 3: Ich revolutioniert die moderne Arbeitswelt, Verwaltung und Bildung nachhaltig.',
    ],
    options: ['Die Digitalisierung', 'Die Globalisierung', 'Die Industrialisierung', 'Die Säkularisierung'],
    correctAnswer: 'Die Digitalisierung',
    explanation: 'Digitalisierung bezeichnet die digitale Transformation in Wirtschaft und Gesellschaft.',
    tags: ['Technologie', 'Transformation'],
    timeLimit: 24,
  },
  {
    id: 'B2-WB-0004',
    level: 'B2',
    gameType: 'WAS_BIN_ICH',
    category: 'Wissenschaft & Philosophie',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten wissenschaftlichen Grundsatz:',
    clues: [
      'Hinweis 1: Ich bin ein moralisches Prinzip in Wissenschaft und Medizin.',
      'Hinweis 2: Ich untersuche, welche Handlungen und Technologien sittlich vertretbar sind.',
      'Hinweis 3: In Fragen von Gentechnik, KI und Sterbehilfe bin ich von entscheidender Bedeutung.',
    ],
    options: ['Die Ethik', 'Die Ästhetik', 'Die Logik', 'Die Rhetorik'],
    correctAnswer: 'Die Ethik',
    explanation: 'Die Ethik befasst sich mit moralischem Handeln und Verantwortung.',
    tags: ['Wissenschaft', 'Philosophie'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ B2: TEAM BATTLE
  // =========================================================================
  {
    id: 'B2-TB-0001',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Indirekte Rede (Konjunktiv I)',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Regierungssprecher teilte mit, der Minister ___ die Vorwürfe zurück.',
    options: ['weise', 'weist', 'wies', 'gewiesen'],
    correctAnswer: 'weise',
    explanation: 'In der indirekten Rede verwendet man den Konjunktiv I der 3. Person Singular ("er weise").',
    tags: ['Konjunktiv I', 'Indirekte Rede'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0002',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Stilistik & Synonyme',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches gehobene Synonym passt am besten zu "beschleunigen"?',
    options: ['vorantreiben', 'verzögern', 'unterbinden', 'verwerfen'],
    correctAnswer: 'vorantreiben',
    explanation: '"Vorantreiben" bedeutet einen Prozess aktiv beschleunigen.',
    tags: ['Wortschatz', 'Stilistik'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0003',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Präpositionen mit Genitiv',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ der unerwarteten Lieferengpässe konnte der Fertigstellungstermin eingehalten werden.',
    options: ['Trotz', 'Wegen', 'Infolge', 'Aufgrund'],
    correctAnswer: 'Trotz',
    explanation: '"Trotz + Genitiv" drückt einen Gegensatz/Widerspruch aus (konzessorisch).',
    tags: ['Genitiv', 'Konzessiv'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0004',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Passiv-Ersatzform (sich lassen + Infinitiv)',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Dieses komplexe mathematische Problem ___ sich verblüffend einfach lösen.',
    options: ['lässt', 'kann', 'wird', 'ist'],
    correctAnswer: 'lässt',
    explanation: '"sich lassen + Infinitiv" bedeutet: kann gelöst werden (Passiv-Ersatzform).',
    tags: ['Passiv-Ersatz', 'Grammatik'],
    timeLimit: 15,
  },
  {
    id: 'B2-TB-0005',
    level: 'B2',
    gameType: 'TEAM_BATTLE',
    category: 'Gehobene Redewendungen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet die Wendung "etwas ins Leben rufen"?',
    options: ['etwas gründen / initiieren', 'etwas beenden', 'etwas zerstören', 'jemanden retten'],
    correctAnswer: 'etwas gründen / initiieren',
    explanation: '"Ins Leben rufen" = ein Projekt oder eine Organisation ins Dasein bringen.',
    tags: ['Redewendungen', 'Gehobene Sprache'],
    timeLimit: 15,
  },
];
