import { BankQuestion } from '../questionTypes.js';

/**
 * A2 Level Question Bank - Farh SprachArena
 * Exactly 100 Questions:
 * - 35 SCHNELLANTWORT (Grammar, Everyday Communication, Dialogues, Intermediate Foundations)
 * - 15 SATZ_RENNEN (Sentence construction, Nebensätze, Perfekt, Modalverben)
 * - 20 WORTSCHATZ_DUELL (Practical vocabulary, Work, Health, Travel, City life)
 * - 15 WAS_BIN_ICH (Deductive clues, Situations, Modern items, Professions)
 * - 15 TEAM_BATTLE (Team Challenges, Daily Situations, Travel, Doctor & Work)
 *
 * Difficulty: 30 EASY, 50 MEDIUM, 20 HARD
 */
export const A2_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ A2: SCHNELLANTWORT (35 Questions: 10 EASY, 18 MEDIUM, 7 HARD)
  // =========================================================================
  {
    id: 'A2-SA-0001',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Perfekt mit haben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich ___ gestern Abend lange ferngesehen.',
    options: ['habe', 'bin', 'werde', 'hatte'],
    correctAnswer: 'habe',
    explanation: 'Das Verb "fernsehen" bildet das Perfekt mit dem Hilfsverb haben: "ich habe ferngesehen".',
    tags: ['Perfekt', 'Verben', 'Vergangenheit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0002',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Perfekt mit sein',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir ___ am Wochenende mit dem Zug nach München gefahren.',
    options: ['sind', 'haben', 'waren', 'wurden'],
    correctAnswer: 'sind',
    explanation: 'Verben der Ortsveränderung (fahren, gehen, fliegen, reisen) bilden das Perfekt mit sein.',
    tags: ['Perfekt', 'Ortsveränderung', 'sein'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0003',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Modalverben im Präteritum',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Gestern war ich krank, deshalb ___ ich nicht zur Arbeit gehen.',
    options: ['konnte', 'kann', 'könnte', 'gekonnt'],
    correctAnswer: 'konnte',
    explanation: 'Im Präteritum lautet die 1. Person Singular von können: "ich konnte".',
    tags: ['Modalverben', 'Präteritum', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0004',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nebensätze mit weil',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Thomas bleibt heute zu Hause, weil er sich erkältet ___ .',
    options: ['hat', 'ist', 'haben', 'wird'],
    correctAnswer: 'hat',
    explanation: 'In einem Nebensatz mit der Kausal-Konjunktion "weil" steht das finite Verb ganz am Ende.',
    tags: ['Nebensätze', 'weil', 'Verbposition'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0005',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nebensätze mit dass',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Lehrerin freut sich, dass alle Schüler pünktlich gekommen ___ .',
    options: ['sind', 'haben', 'waren', 'werden'],
    correctAnswer: 'sind',
    explanation: 'Im Nebensatz mit "dass" steht das finite Hilfsverb ("sind" für kommen) am Satzende.',
    tags: ['Nebensätze', 'dass', 'Perfekt'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0006',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wechselpräpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Er stellt das neue Bild an ___ Wand.',
    options: ['die', 'der', 'den', 'dem'],
    correctAnswer: 'die',
    explanation: 'Richtung / Ziel einer Handlung (Wohin?) verlangt bei Wechselpräpositionen den Akkusativ: "an die Wand" (feminin).',
    tags: ['Wechselpräpositionen', 'Akkusativ', 'Wohin'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0007',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wechselpräpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Das Bild hängt jetzt schon seit zwei Wochen an ___ Wand.',
    options: ['der', 'die', 'den', 'dem'],
    correctAnswer: 'der',
    explanation: 'Lage / Ort (Wo?) verlangt bei Wechselpräpositionen den Dativ: "an der Wand" (feminin: die -> der).',
    tags: ['Wechselpräpositionen', 'Dativ', 'Wo'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0008',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Komparativ & Superlativ',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ein ICE-Zug fährt ___ als ein normales Regionalauto.',
    options: ['schneller', 'schnellste', 'am schnellsten', 'schnell'],
    correctAnswer: 'schneller',
    explanation: 'Für den Vergleich zweier Dinge mit "als" wird der Komparativ mit der Endung -er verwendet.',
    tags: ['Komparativ', 'Vergleich', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0009',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Superlativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Mount Everest ist der ___ Berg der ganzen Welt.',
    options: ['höchste', 'hohe', 'höher', 'höchster'],
    correctAnswer: 'höchste',
    explanation: 'Der Superlativ von "hoch" vor einem maskulinen Nomen mit bestimmtem Artikel lautet "der höchste".',
    tags: ['Superlativ', 'Adjektive', 'Deklination'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0010',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Reflexive Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich muss mich nach dem langen Sportunterricht erst einmal ___ .',
    options: ['ausruhen', 'ausruht', 'ausruhe', 'ausgeruht'],
    correctAnswer: 'ausruhen',
    explanation: 'Nach dem Modalverb "muss" steht das reflexive Verb im Infinitiv am Satzende ("sich ausruhen").',
    tags: ['Reflexive Verben', 'Modalverben'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0011',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Reflexivpronomen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Freust du ___ schon auf deinen nächsten Sommerurlaub?',
    options: ['dich', 'dir', 'sich', 'mich'],
    correctAnswer: 'dich',
    explanation: 'Das Verb "sich freuen" verlangt das Reflexivpronomen im Akkusativ: "du freust dich".',
    tags: ['Reflexivpronomen', 'Akkusativ', 'Reisen'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0012',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konditionalsätze mit wenn',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn das Wetter morgen schön ist, ___ wir einen Ausflug an den See.',
    options: ['machen', 'wir machen', 'gemacht', 'machten'],
    correctAnswer: 'machen',
    explanation: 'Wenn der Nebensatz vorangestellt ist, beginnt der folgende Hauptsatz sofort mit dem Verb (Position 1 im Hauptsatz).',
    tags: ['Nebensätze', 'wenn', 'Inversion'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0013',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Temporalsätze mit als',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ ich ein Kind war, habe ich viel auf der Straße gespielt.',
    options: ['Als', 'Wenn', 'Wann', 'Weil'],
    correctAnswer: 'Als',
    explanation: '"Als" verwendet man für ein einmaliges Ereignis oder einen zusammenhängenden Zeitraum in der Vergangenheit.',
    tags: ['Temporalsätze', 'als-wenn', 'Vergangenheit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0014',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Infinitiv mit zu',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich habe heute überhaupt keine Lust, die Wohnung ___ .',
    options: ['aufzuräumen', 'aufräumen', 'zu aufräumen', 'aufgeräumt'],
    correctAnswer: 'aufzuräumen',
    explanation: 'Bei trennbaren Verben wird "zu" zwischen Vorsilbe und Verbstamm eingefügt: "auf-zu-räumen".',
    tags: ['Infinitiv mit zu', 'Trennbare Verben'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0015',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Adjektivdeklination Akkusativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Er kauft sich einen ___ Pullover für den kalten Winter.',
    options: ['warmen', 'warmer', 'warmes', 'warme'],
    correctAnswer: 'warmen',
    explanation: 'Maskulines Nomen im Akkusativ nach unbestimmtem Artikel erhält die Adjektivendung -en ("einen warmen Pullover").',
    tags: ['Adjektivdeklination', 'Akkusativ', 'Kleidung'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0016',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Adjektivdeklination Dativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Sie wohnt in einer sehr ___ Wohnung mitten im Zentrum.',
    options: ['schönen', 'schöne', 'schöner', 'schönes'],
    correctAnswer: 'schönen',
    explanation: 'Im Dativ enden Adjektive nach bestimmtem oder unbestimmtem Artikel immer auf -en ("in einer schönen Wohnung").',
    tags: ['Adjektivdeklination', 'Dativ', 'Wohnen'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0017',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präteritum sein/haben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Letztes Jahr ___ wir im Sommer zwei Wochen in Italien.',
    options: ['waren', 'hatten', 'sind', 'wurden'],
    correctAnswer: 'waren',
    explanation: 'Präteritum 1. Person Plural von sein lautet "wir waren".',
    tags: ['Präteritum', 'Reisen'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0018',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präteritum haben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Als Student ___ ich leider nicht viel Geld.',
    options: ['hatte', 'habe', 'hätte', 'hattest'],
    correctAnswer: 'hatte',
    explanation: 'Präteritum 1. Person Singular von haben lautet "ich hatte".',
    tags: ['Präteritum', 'haben'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0019',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Futur I mit werden',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Im nächsten Monat ___ mein Kollege eine neue Stelle anfangen.',
    options: ['wird', 'werde', 'werden', 'wirst'],
    correctAnswer: 'wird',
    explanation: 'Das Hilfsverb "werden" in der 3. Person Singular ("er / mein Kollege") lautet "wird".',
    tags: ['Futur', 'Zukunft', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0020',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Dativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich gehe heute nach der Arbeit ___ meiner Ärztin.',
    options: ['zu', 'bei', 'nach', 'an'],
    correctAnswer: 'zu',
    explanation: 'Wenn man zu Personen oder Institutionen geht, verwendet man "zu" + Dativ ("zu meiner Ärztin").',
    tags: ['Präpositionen', 'Dativ', 'Gesundheit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0021',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Dativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er wohnt schon seit ___ Jahr in dieser wunderschönen Stadt.',
    options: ['einem', 'einen', 'eines', 'einer'],
    correctAnswer: 'einem',
    explanation: '"Seit" verlangt immer Dativ: "das Jahr" (neutral) wird im Dativ zu "einem Jahr".',
    tags: ['Präpositionen', 'Dativ', 'Zeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0022',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Akkusativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir spazieren am Nachmittag durch ___ grünen Park.',
    options: ['den', 'dem', 'der', 'des'],
    correctAnswer: 'den',
    explanation: 'Die Präposition "durch" steht immer mit dem Akkusativ ("durch den grünen Park").',
    tags: ['Präpositionen', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0023',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Akkusativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Dieses schöne Geschenk ist ___ meine liebe Großmutter.',
    options: ['für', 'von', 'zu', 'mit'],
    correctAnswer: 'für',
    explanation: '"für" verlangt den Akkusativ und drückt den Empfänger/Zweck aus ("für meine Großmutter").',
    tags: ['Präpositionen', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0024',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektoren deshalb / trotzdem',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Es regnet in Strömen, ___ gehen wir ohne Schirm spazieren.',
    options: ['trotzdem', 'deshalb', 'weil', 'denn'],
    correctAnswer: 'trotzdem',
    explanation: '"trotzdem" drückt einen unerwarteten Gegensatz aus (Konzessiv-Adverb) und steht vor dem Verb ("trotzdem gehen wir").',
    tags: ['Konnektoren', 'trotzdem', 'Adverbien'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0025',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektoren deshalb',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er hat viel gelernt, ___ hat er die Deutschprüfung bestanden.',
    options: ['deshalb', 'weil', 'obwohl', 'dass'],
    correctAnswer: 'deshalb',
    explanation: '"deshalb" drückt eine logische Folge aus und zieht das Verb an Position 2 ("deshalb hat er").',
    tags: ['Konnektoren', 'deshalb', 'Folge'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0026',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektoren denn vs weil',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich trinke keinen Kaffee, ___ ich mag lieber Pfefferminztee.',
    options: ['denn', 'weil', 'deshalb', 'trotzdem'],
    correctAnswer: 'denn',
    explanation: '"denn" steht auf Position 0 und verändert die normale Hauptsatz-Wortstellung nicht ("denn ich mag...").',
    tags: ['Konnektoren', 'denn', 'Hauptsatz'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0027',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Gesundheit & Ratschläge',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Du hast hohes Fieber. Du ___ unbedingt zum Arzt gehen.',
    options: ['solltest', 'musstest', 'wolltest', 'durftest'],
    correctAnswer: 'solltest',
    explanation: '"solltest" (Konjunktiv II von sollen) wird für höfliche Ratschläge und Empfehlungen genutzt.',
    tags: ['Gesundheit', 'Ratschläge', 'Konjunktiv'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0028',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Höfliche Bitten',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Entschuldigung, ___ Sie mir bitte sagen, wo der Bahnhof ist?',
    options: ['könnten', 'konnten', 'können Sie', 'kann'],
    correctAnswer: 'könnten',
    explanation: '"Könnten Sie...?" ist die typische, sehr höfliche Form für Anfragen im Alltag.',
    tags: ['Höflichkeit', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0029',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Termine vereinbaren',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Passt es Ihnen am Donnerstag um 15 Uhr? — Ja, das ___ mir sehr gut.',
    options: ['passt', 'steht', 'geht', 'sieht'],
    correctAnswer: 'passt',
    explanation: 'Die idiomatische Redewendung für Termine lautet: "Das passt mir gut".',
    tags: ['Termine', 'Kommunikation', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0030',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Präposition von... bis / ab',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Praxis von Dr. Farh ist montags ___ 8:00 bis 16:00 Uhr geöffnet.',
    options: ['von', 'ab', 'seit', 'um'],
    correctAnswer: 'von',
    explanation: 'Zeitspannen werden mit dem Paar "von ... bis" ausgedrückt.',
    tags: ['Zeit', 'Termine', 'Präpositionen'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0031',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Indirekte Fragesätze mit ob',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Können Sie mir sagen, ___ der Bus nach Berlin schon abgefahren ist?',
    options: ['ob', 'wann', 'dass', 'weil'],
    correctAnswer: 'ob',
    explanation: 'Bei indirekten Ja/Nein-Fragen leitet man den Nebensatz mit "ob" ein (Verb am Ende).',
    tags: ['Indirekte Fragen', 'ob', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0032',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wortbildung Nomen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Nomen mit der Endung "-ung" (wie die Wohnung, die Rechnung) sind immer ___ .',
    options: ['feminin (die)', 'maskulin (der)', 'neutral (das)', 'Plural'],
    correctAnswer: 'feminin (die)',
    explanation: 'Substantive mit den Suffixen -ung, -heit, -keit, -schaft sind immer feminin (die).',
    tags: ['Grammatik', 'Artikelregeln', 'Nomen'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0033',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wohnungsanzeigen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Miete beträgt 600 Euro im Monat ___ Nebenkosten (Strom, Heizung).',
    options: ['zuzüglich / plus', 'ohne alles', 'kostenlos', 'billig'],
    correctAnswer: 'zuzüglich / plus',
    explanation: 'In Wohnungsanzeigen unterscheidet man Kaltmiete und Warmmiete zuzüglich (plus) Nebenkosten.',
    tags: ['Wohnen', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0034',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Reklamation & Kleidung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Jacke ist leider zu eng. Kann ich sie gegen eine größere Nummer ___ ?',
    options: ['umtauschen', 'einkaufen', 'verkaufen', 'bezahlen'],
    correctAnswer: 'umtauschen',
    explanation: '"umtauschen" bedeutet, eine gekaufte Ware im Geschäft gegen eine andere zu wechseln.',
    tags: ['Einkaufen', 'Reklamation'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0035',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Briefe & E-Mails',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie lautet die passende förmliche Grußformel am Ende eines geschäftlichen Briefes?',
    options: ['Mit freundlichen Grüßen', 'Tschüss und bis bald', 'Liebe Grüße', 'Machs gut'],
    correctAnswer: 'Mit freundlichen Grüßen',
    explanation: 'In formellen Briefen und beruflichen E-Mails schließt man standardmäßig mit "Mit freundlichen Grüßen".',
    tags: ['Schreiben', 'Höflichkeit', 'Brief'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 A2: SATZ-RENNEN (15 Questions: 5 EASY, 7 MEDIUM, 3 HARD)
  // =========================================================================
  {
    id: 'A2-SR-0001',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Perfekt Satzklammer',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz im Perfekt:',
    words: ['Ich', 'gestern', 'einen spannenden Film', 'habe', 'gesehen.'],
    correctOrder: ['Ich', 'habe', 'gestern', 'einen spannenden Film', 'gesehen.'],
    correctAnswer: ['Ich', 'habe', 'gestern', 'einen spannenden Film', 'gesehen.'],
    explanation: 'Hilfsverb "habe" steht an Position 2, das Partizip II "gesehen" schließt die Satzklammer am Ende.',
    tags: ['Perfekt', 'Satzklammer'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0002',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Kausalsatz mit weil',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Nebensatz mit "weil":',
    words: ['Er lernt Deutsch,', 'weil', 'er in Deutschland', 'arbeiten', 'möchte.'],
    correctOrder: ['Er lernt Deutsch,', 'weil', 'er in Deutschland', 'arbeiten', 'möchte.'],
    correctAnswer: ['Er lernt Deutsch,', 'weil', 'er in Deutschland', 'arbeiten', 'möchte.'],
    explanation: 'Im weil-Satz steht der Infinitiv vor dem finiten Modalverb ("arbeiten möchte") am Satzende.',
    tags: ['Nebensätze', 'weil', 'Modalverben'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0003',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Konditionalsatz mit wenn',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Wenn-Satz in die richtige Reihenfolge:',
    words: ['Wenn du Zeit hast,', 'können', 'wir', 'ins Kino', 'gehen.'],
    correctOrder: ['Wenn du Zeit hast,', 'können', 'wir', 'ins Kino', 'gehen.'],
    correctAnswer: ['Wenn du Zeit hast,', 'können', 'wir', 'ins Kino', 'gehen.'],
    explanation: 'Nach dem vorgeschalteten Nebensatz folgt im Hauptsatz sofort das finite Verb auf Position 1.',
    tags: ['Konditionalsatz', 'wenn', 'Inversion'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0004',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Infinitiv mit zu',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die Infinitivkonstruktion mit "zu":',
    words: ['Es ist wichtig,', 'jeden Tag', 'neue Vokabeln', 'zu wiederholen.'],
    correctOrder: ['Es ist wichtig,', 'jeden Tag', 'neue Vokabeln', 'zu wiederholen.'],
    correctAnswer: ['Es ist wichtig,', 'jeden Tag', 'neue Vokabeln', 'zu wiederholen.'],
    explanation: 'Die Infinitivgruppe schließt mit "zu" + Infinitiv am Satzende ab.',
    tags: ['Infinitiv mit zu', 'Satzbau'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0005',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Reflexive Verben im Satz',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit dem reflexiven Verb:',
    words: ['Wir', 'freuen', 'uns', 'sehr auf das Wochenende.'],
    correctOrder: ['Wir', 'freuen', 'uns', 'sehr auf das Wochenende.'],
    correctAnswer: ['Wir', 'freuen', 'uns', 'sehr auf das Wochenende.'],
    explanation: 'Subjekt (Wir) -> finites Verb (freuen) -> Reflexivpronomen (uns) -> präpositionales Objekt.',
    tags: ['Reflexive Verben', 'Satzbau'],
    timeLimit: 20,
  },
  {
    id: 'A2-SR-0006',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Dass-Sätze',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit "dass":',
    words: ['Ich weiß genau,', 'dass', 'Farh', 'ein hervorragender Lehrer', 'ist.'],
    correctOrder: ['Ich weiß genau,', 'dass', 'Farh', 'ein hervorragender Lehrer', 'ist.'],
    correctAnswer: ['Ich weiß genau,', 'dass', 'Farh', 'ein hervorragender Lehrer', 'ist.'],
    explanation: 'Im dass-Satz steht das finite Verb "ist" ganz am Ende.',
    tags: ['Nebensätze', 'dass'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0007',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Konnektor deshalb',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Konsekutiv-Konnektor "deshalb":',
    words: ['Er war müde,', 'deshalb', 'ging', 'er', 'früh ins Bett.'],
    correctOrder: ['Er war müde,', 'deshalb', 'ging', 'er', 'früh ins Bett.'],
    correctAnswer: ['Er war müde,', 'deshalb', 'ging', 'er', 'früh ins Bett.'],
    explanation: '"deshalb" besetzt Position 1 des Hauptsatzes, danach folgt direkt das Prädikat "ging".',
    tags: ['Konnektoren', 'deshalb', 'Präteritum'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0008',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Temporalsatz mit als',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit der temporalen Konjunktion "als":',
    words: ['Als ich nach Deutschland kam,', 'konnte', 'ich', 'kein Deutsch', 'sprechen.'],
    correctOrder: ['Als ich nach Deutschland kam,', 'konnte', 'ich', 'kein Deutsch', 'sprechen.'],
    correctAnswer: ['Als ich nach Deutschland kam,', 'konnte', 'ich', 'kein Deutsch', 'sprechen.'],
    explanation: 'Nebensatz mit "als" vorangestellt -> Hauptsatz beginnt mit Modalverb "konnte", Infinitiv "sprechen" am Ende.',
    tags: ['Temporalsätze', 'als', 'Modalverben'],
    timeLimit: 30,
  },
  {
    id: 'A2-SR-0009',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Indirekte W-Frage',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die höfliche indirekte Frage:',
    words: ['Können Sie mir sagen,', 'wann', 'der nächste Zug', 'abfährt', '?'],
    correctOrder: ['Können Sie mir sagen,', 'wann', 'der nächste Zug', 'abfährt', '?'],
    correctAnswer: ['Können Sie mir sagen,', 'wann', 'der nächste Zug', 'abfährt', '?'],
    explanation: 'In der indirekten Frage wandert das trennbare Verb in einem Stück ("abfährt") ans Satzende.',
    tags: ['Indirekte Fragen', 'Verkehr'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0010',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Präpositionalphrase TeKaMoLo',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Ordne die Satzglieder nach der TeKaMoLo-Regel (Temporal vor Lokal):',
    words: ['Wir fahren', 'am Wochenende', 'mit dem Zug', 'nach Hamburg.'],
    correctOrder: ['Wir fahren', 'am Wochenende', 'mit dem Zug', 'nach Hamburg.'],
    correctAnswer: ['Wir fahren', 'am Wochenende', 'mit dem Zug', 'nach Hamburg.'],
    explanation: 'Reihenfolge der Angaben im Deutschen: Temporal (am Wochenende) -> Modal (mit dem Zug) -> Lokal (nach Hamburg).',
    tags: ['TeKaMoLo', 'Satzglieder', 'Reisen'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0011',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Futur I Satzbau',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz in der Zukunftsform (Futur I):',
    words: ['Nächste Woche', 'werden', 'wir', 'eine schwere Prüfung', 'schreiben.'],
    correctOrder: ['Nächste Woche', 'werden', 'wir', 'eine schwere Prüfung', 'schreiben.'],
    correctAnswer: ['Nächste Woche', 'werden', 'wir', 'eine schwere Prüfung', 'schreiben.'],
    explanation: 'Hilfsverb "werden" auf Pos. 2, Vollverb-Infinitiv "schreiben" ganz am Satzende.',
    tags: ['Futur', 'Satzbau'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0012',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Arztbesuch Dialog',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die Erklärung beim Arztbesuch:',
    words: ['Seit gestern', 'habe', 'ich', 'starke Halsschmerzen.'],
    correctOrder: ['Seit gestern', 'habe', 'ich', 'starke Halsschmerzen.'],
    correctAnswer: ['Seit gestern', 'habe', 'ich', 'starke Halsschmerzen.'],
    explanation: 'Temporaladverbial "Seit gestern" auf Pos. 1, finites Verb "habe" auf Pos. 2, Subjekt "ich" auf Pos. 3.',
    tags: ['Gesundheit', 'Arzt', 'Inversion'],
    timeLimit: 20,
  },
  {
    id: 'A2-SR-0013',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Konnektor obwohl',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Nebensatz mit "obwohl":',
    words: ['Er geht spazieren,', 'obwohl', 'es', 'sehr stark', 'regnet.'],
    correctOrder: ['Er geht spazieren,', 'obwohl', 'es', 'sehr stark', 'regnet.'],
    correctAnswer: ['Er geht spazieren,', 'obwohl', 'es', 'sehr stark', 'regnet.'],
    explanation: 'Im Nebensatz mit der Konjunktion "obwohl" steht das konjugierte Verb "regnet" am Ende.',
    tags: ['Nebensätze', 'obwohl'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0014',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Vergleich mit als',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den korrekten Vergleichssatz:',
    words: ['Mein Bruder', 'ist', 'zwei Jahre', 'älter', 'als ich.'],
    correctOrder: ['Mein Bruder', 'ist', 'zwei Jahre', 'älter', 'als ich.'],
    correctAnswer: ['Mein Bruder', 'ist', 'zwei Jahre', 'älter', 'als ich.'],
    explanation: 'Komparativ "älter" steht vor der Vergleichspartikel "als".',
    tags: ['Komparativ', 'Vergleich'],
    timeLimit: 20,
  },
  {
    id: 'A2-SR-0015',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Höfliche Bitte mit Konjunktiv II',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde eine sehr höfliche Bitte:',
    words: ['Würden', 'Sie', 'mir bitte', 'das Salz', 'geben', '?'],
    correctOrder: ['Würden', 'Sie', 'mir bitte', 'das Salz', 'geben', '?'],
    correctAnswer: ['Würden', 'Sie', 'mir bitte', 'das Salz', 'geben', '?'],
    explanation: '"Würden" an Position 1 leitet die höfliche Frage ein, der Infinitiv "geben" steht am Schluss.',
    tags: ['Höflichkeit', 'Konjunktiv II'],
    timeLimit: 20,
  },

  // =========================================================================
  // 🧠 A2: WORTSCHATZ-DUELL (20 Questions: 6 EASY, 10 MEDIUM, 4 HARD)
  // =========================================================================
  {
    id: 'A2-WD-0001',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesundheit & Medizin',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Medikament',
    focusWord: 'das Medikament',
    question: 'Was bedeutet "das Medikament" und wie lautet der Plural?',
    options: ['Medicine / Drug -> die Medikamente', 'Doctor -> die Ärzte', 'Hospital -> die Krankenhäuser', 'Pain -> die Schmerzen'],
    correctAnswer: 'Medicine / Drug -> die Medikamente',
    explanation: 'Das Medikament = medicine/medication, Plural: die Medikamente.',
    tags: ['Gesundheit', 'Wortschatz'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0002',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Reisen & Bahnhof',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Verspätung',
    focusWord: 'die Verspätung',
    question: 'Was bedeutet die Durchsage "Der Zug hat 15 Minuten Verspätung"?',
    options: ['The train is delayed by 15 minutes', 'The train is canceled', 'The train arrives 15 minutes earlier', 'The train is fully booked'],
    correctAnswer: 'The train is delayed by 15 minutes',
    explanation: '"Die Verspätung" bedeutet Verzögerung / delay.',
    tags: ['Reisen', 'Verkehr', 'Bahn'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0003',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeitswelt',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Bewerbung',
    focusWord: 'die Bewerbung',
    question: 'Was ist "die Bewerbung"?',
    options: ['Job application', 'Employment contract (der Arbeitsvertrag)', 'Salary (das Gehalt)', 'Resignation (die Kündigung)'],
    correctAnswer: 'Job application',
    explanation: '"Die Bewerbung" sind Anschreiben und Lebenslauf zur Erlangung einer Stelle.',
    tags: ['Arbeit', 'Beruf'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0004',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeit & Gehalt',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Gehalt',
    focusWord: 'das Gehalt',
    question: 'Was bedeutet "das Gehalt"?',
    options: ['Salary / Monthly wage', 'Working hours (die Arbeitszeit)', 'Boss (der Chef)', 'Colleague (der Kollege)'],
    correctAnswer: 'Salary / Monthly wage',
    explanation: 'Das Gehalt ist die monatliche Bezahlung für Angestellte.',
    tags: ['Arbeit', 'Finanzen'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0005',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wohnen & Umgebung',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Nebenkosten',
    focusWord: 'die Nebenkosten',
    question: 'Was sind bei einer Mietwohnung "die Nebenkosten"?',
    options: ['Utility costs (water, heating, trash collection)', 'The deposit (die Kaution)', 'The furniture price', 'The agency commission'],
    correctAnswer: 'Utility costs (water, heating, trash collection)',
    explanation: 'Nebenkosten umfassen laufende Betriebskosten wie Heizung, Wasser und Müllabfuhr.',
    tags: ['Wohnen', 'Miete'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0006',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Urlaub & Unterkunft',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Unterkunft',
    focusWord: 'die Unterkunft',
    question: 'Was bedeutet "die Unterkunft" auf Reisen?',
    options: ['Accommodation / Lodging', 'Flight ticket (das Flugticket)', 'Luggage (das Gepäck)', 'Sightseeing tour'],
    correctAnswer: 'Accommodation / Lodging',
    explanation: 'Die Unterkunft ist der Ort, an dem man übernachtet (Hotel, Ferienwohnung, Hostel).',
    tags: ['Reisen', 'Urlaub'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0007',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesundheit & Symptome',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Husten',
    focusWord: 'der Husten',
    question: 'Was bedeutet das Krankheitssymptom "der Husten"?',
    options: ['Cough', 'Fever (das Fieber)', 'Runny nose (der Schnupfen)', 'Dizziness (der Schwindel)'],
    correctAnswer: 'Cough',
    explanation: 'Husten = cough; Schnupfen = cold/sniffles.',
    tags: ['Gesundheit', 'Krankheit'],
    timeLimit: 12,
  },
  {
    id: 'A2-WD-0008',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Rezept & Apotheke',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Rezept',
    focusWord: 'das Rezept',
    question: 'Was bedeutet "das Rezept" im medizinischen Kontext beim Arzt?',
    options: ['Doctor\'s prescription for medication', 'Cooking recipe', 'Invoice (die Rechnung)', 'Sick note (die Krankschreibung)'],
    correctAnswer: 'Doctor\'s prescription for medication',
    explanation: 'Beim Arzt ist das Rezept die Verschreibung von Medikamenten für die Apotheke.',
    tags: ['Gesundheit', 'Arzt'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0009',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kaufhaus & Etagen',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Erdgeschoss',
    focusWord: 'das Erdgeschoss',
    question: 'Welches Stockwerk ist "das Erdgeschoss (EG)"?',
    options: ['Ground floor', 'First floor (1. Obergeschoss)', 'Basement (das Untergeschoss / der Keller)', 'Attic (das Dachgeschoss)'],
    correctAnswer: 'Ground floor',
    explanation: 'Das Erdgeschoss (EG) ist die ebenerdige Eingangsetage.',
    tags: ['Einkaufen', 'Gebäude'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0010',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Verkehr & Tickets',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Fahrkarte / das Ticket',
    focusWord: 'die Fahrkarte',
    question: 'Was bedeutet "die Fahrkarte"?',
    options: ['Transit ticket / Fare ticket', 'Timetable (der Fahrplan)', 'Platform (das Gleis)', 'Seat reservation'],
    correctAnswer: 'Transit ticket / Fare ticket',
    explanation: 'Eine Fahrkarte ist der gültige Fahrschein für Bus und Bahn.',
    tags: ['Verkehr', 'Reisen'],
    timeLimit: 12,
  },
  {
    id: 'A2-WD-0011',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gegenteile Adjektive',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'bequem',
    focusWord: 'bequem',
    question: 'Was ist das Gegenteil von "bequem" (comfortable)?',
    options: ['unbequem (uncomfortable)', 'gemütlich', 'weich', 'angenehm'],
    correctAnswer: 'unbequem (uncomfortable)',
    explanation: 'Das Gegenteil von bequem ist unbequem.',
    tags: ['Adjektive', 'Antonyme'],
    timeLimit: 12,
  },
  {
    id: 'A2-WD-0012',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gegenteile Adjektive',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'pünktlich',
    focusWord: 'pünktlich',
    question: 'Was ist das Gegenteil von "pünktlich" (punctual)?',
    options: ['unpünktlich / verspätet', 'schnell', 'fleißig', 'höflich'],
    correctAnswer: 'unpünktlich / verspätet',
    explanation: 'Wer nicht pünktlich ist, ist unpünktlich oder verspätet.',
    tags: ['Adjektive', 'Antonyme'],
    timeLimit: 12,
  },
  {
    id: 'A2-WD-0013',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Stadt & Orientierung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Kreuzung',
    focusWord: 'die Kreuzung',
    question: 'Was bedeutet die Wegbeschreibung: "Biegen Sie an der nächsten Kreuzung rechts ab"?',
    options: ['Intersection / Crossroad', 'Traffic light (die Ampel)', 'Roundabout (der Kreisverkehr)', 'Bridge (die Brücke)'],
    correctAnswer: 'Intersection / Crossroad',
    explanation: 'Die Kreuzung ist der Schnittpunkt von zwei oder mehr Straßen.',
    tags: ['Wegbeschreibung', 'Stadt'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0014',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Umwelt & Wetter',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Gewitter',
    focusWord: 'das Gewitter',
    question: 'Was ist "das Gewitter"?',
    options: ['Thunderstorm with lightning and thunder', 'Gentle breeze', 'Sunny day', 'Snowfall'],
    correctAnswer: 'Thunderstorm with lightning and thunder',
    explanation: 'Ein Gewitter ist ein Unwetter mit Blitz (lightning) und Donner (thunder).',
    tags: ['Wetter', 'Natur'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0015',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Küche & Zubereitung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'kochen vs braten',
    focusWord: 'braten',
    question: 'Was bedeutet das Kochverb "braten"?',
    options: ['To fry / roast in a pan', 'To boil in water (kochen)', 'To bake bread (backen)', 'To cut vegetables (schneiden)'],
    correctAnswer: 'To fry / roast in a pan',
    explanation: '"braten" bedeutet Fleisch oder Gemüse in der Pfanne mit Fett heiß braten.',
    tags: ['Essen', 'Kochen'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0016',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Freizeit & Kultur',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Veranstaltung',
    focusWord: 'die Veranstaltung',
    question: 'Was bedeutet "die Veranstaltung"?',
    options: ['Event / Performance / Function', 'Building (das Gebäude)', 'Exhibition item', 'Ticket booth'],
    correctAnswer: 'Event / Performance / Function',
    explanation: 'Eine Veranstaltung ist ein organisiertes Event (Konzert, Theater, Vortrag).',
    tags: ['Kultur', 'Freizeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0017',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeit & Vertrag',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Kündigung',
    focusWord: 'die Kündigung',
    question: 'Was ist "die Kündigung"?',
    options: ['Termination / Resignation notice', 'Promotion (die Beförderung)', 'Job interview (das Vorstellungsgespräch)', 'Overtime (die Überstunden)'],
    correctAnswer: 'Termination / Resignation notice',
    explanation: 'Die Kündigung beendet offiziell ein Vertragsverhältnis (Arbeitsvertrag, Mietvertrag).',
    tags: ['Arbeit', 'Recht'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0018',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Post & Versand',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Paket',
    focusWord: 'das Paket',
    question: 'Was bedeutet "das Paket" bei der Post?',
    options: ['Parcel / Package', 'Letter (der Brief)', 'Stamp (die Briefmarke)', 'Mailbox (der Briefkasten)'],
    correctAnswer: 'Parcel / Package',
    explanation: 'Ein Paket ist eine Postsendung für größere Gegenstände.',
    tags: ['Post', 'Alltag'],
    timeLimit: 12,
  },
  {
    id: 'A2-WD-0019',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Charaktereigenschaften',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'zuverlässig',
    focusWord: 'zuverlässig',
    question: 'Was bedeutet die Eigenschaft "zuverlässig"?',
    options: ['Reliable / Dependable', 'Lazy (faul)', 'Stubborn (stur)', 'Impatient (ungeduldig)'],
    correctAnswer: 'Reliable / Dependable',
    explanation: 'Wer zuverlässig ist, hält Versprechen und Vereinbarungen immer ein.',
    tags: ['Persönlichkeit', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0020',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Bildung & Schule',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Zeugnis',
    focusWord: 'das Zeugnis',
    question: 'Was ist "das Zeugnis" am Ende des Schuljahres?',
    options: ['Report card / Certificate of grades', 'Homework notebook', 'Textbook', 'School bag'],
    correctAnswer: 'Report card / Certificate of grades',
    explanation: 'Das Zeugnis ist die offizielle Bescheinigung der erbrachten Noten und Leistungen.',
    tags: ['Bildung', 'Schule'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ A2: WAS BIN ICH? (15 Questions: 5 EASY, 8 MEDIUM, 2 HARD)
  // =========================================================================
  {
    id: 'A2-WB-0001',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Medizinische Berufe',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Beruf im Gesundheitswesen:',
    clues: [
      'Hinweis 1: Ich arbeite in der Apotheke.',
      'Hinweis 2: Ich lese die Rezepte der Ärzte und gebe den Kunden Medikamente.',
      'Hinweis 3: Ich erkläre Patienten ganz genau, wie oft und wann sie ihre Tabletten einnehmen müssen.',
    ],
    options: ['Der Apotheker', 'Der Krankenpfleger', 'Der Zahnarzt', 'Der Optiker'],
    correctAnswer: 'Der Apotheker',
    explanation: 'Der Apotheker verkauft und berät über Arzneimittel in der Apotheke.',
    tags: ['Berufe', 'Gesundheit'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0002',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Stadt & Gebäude',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte städtische Einrichtung:',
    clues: [
      'Hinweis 1: Ich bin das wichtigste Gebäude der Stadtverwaltung.',
      'Hinweis 2: Hier arbeitet der Bürgermeister und der Stadtrat.',
      'Hinweis 3: Bürger melden hier ihren neuen Wohnsitz im Bürgeramt an.',
    ],
    options: ['Das Rathaus', 'Das Museum', 'Die Universität', 'Die Bank'],
    correctAnswer: 'Das Rathaus',
    explanation: 'Im Rathaus sitzt die Stadtverwaltung mit Bürgermeister und Bürgerbüro.',
    tags: ['Stadt', 'Verwaltung'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0003',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Haushalt & Technik',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Haushaltsgerät:',
    clues: [
      'Hinweis 1: Man füllt schmutzige Kleidung und Waschpulver in mich hinein.',
      'Hinweis 2: Meine Trommel dreht sich schnell und wäscht alles mit heißem Wasser sauber.',
      'Hinweis 3: Nach dem Schleudern holt man saubere, feuchte Wäsche heraus.',
    ],
    options: ['Die Waschmaschine', 'Die Spülmaschine', 'Der Staubsauger', 'Der Wäschetrockner'],
    correctAnswer: 'Die Waschmaschine',
    explanation: 'Die Waschmaschine reinigt Textilien mit Wasser und Waschmittel.',
    tags: ['Haushalt', 'Geräte'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0004',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Reisen & Gepäck',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Reisegegenstand:',
    clues: [
      'Hinweis 1: Vor dem Urlaub packt man Hosen, T-Shirts und Schuhe in mich hinein.',
      'Hinweis 2: Ich habe Rollen und einen Teleskopgriff zum Ziehen.',
      'Hinweis 3: Am Flughafen gibt man mich am Check-in-Schalter als Reisegepäck ab.',
    ],
    options: ['Der Koffer', 'Die Geldbörse', 'Der Plastikbeutel', 'Der Briefumschlag'],
    correctAnswer: 'Der Koffer',
    explanation: 'Im Koffer transportiert man Kleidung und Reiseutensilien.',
    tags: ['Reisen', 'Gepäck'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0005',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Medizinische Geräte',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten medizinischen Gegenstand:',
    clues: [
      'Hinweis 1: Wenn man sich heiß fühlt und schwitzt, holt man mich aus dem Schrank.',
      'Hinweis 2: Man steckt mich unter die Zunge oder ins Ohr.',
      'Hinweis 3: Ein Display zeigt nach wenigen Sekunden die genaue Körpertemperatur an.',
    ],
    options: ['Das Fieberthermometer', 'Das Pflaster', 'Der Verband', 'Die Spritze'],
    correctAnswer: 'Das Fieberthermometer',
    explanation: 'Mit dem Fieberthermometer misst man die Körpertemperatur.',
    tags: ['Gesundheit', 'Medizin'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0006',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Arbeit & Büro',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Arbeitsdokument:',
    clues: [
      'Hinweis 1: Man schickt mich mit, wenn man sich auf eine freie Arbeitsstelle bewirbt.',
      'Hinweis 2: In mir stehen tabellarisch Schule, Ausbildung, Studium und bisherige Berufserfahrungen.',
      'Hinweis 3: Auf Lateinisch nennt man mich oft "Curriculum Vitae" (CV).',
    ],
    options: ['Der Lebenslauf', 'Der Arbeitsvertrag', 'Das Kündigungsschreiben', 'Die Rechnung'],
    correctAnswer: 'Der Lebenslauf',
    explanation: 'Der Lebenslauf dokumentiert den bisherigen beruflichen Werdegang.',
    tags: ['Arbeit', 'Bewerbung'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0007',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Küche & Backen',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Küchengerät:',
    clues: [
      'Hinweis 1: Ich werde bis zu 250 Grad heiß.',
      'Hinweis 2: Man backt in mir leckere Kuchen, frische Pizza und knuspriges Brot.',
      'Hinweis 3: Ich habe ein Glasfenster und eine Lampe, damit man das Essen beim Backen beobachten kann.',
    ],
    options: ['Der Backofen', 'Der Toaster', 'Der Wasserkocher', 'Die Kaffeemaschine'],
    correctAnswer: 'Der Backofen',
    explanation: 'Im Backofen backt und brät man bei hohen Temperaturen.',
    tags: ['Küche', 'Kochen'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0008',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Bahn & Gleise',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Ort am Bahnhof:',
    clues: [
      'Hinweis 1: Ich bin die erhöhte Fläche neben den Zugschienen.',
      'Hinweis 2: Hier warten die Passagiere mit ihren Koffern auf die Einfahrt des Zuges.',
      'Hinweis 3: Auf der Anzeigetafel steht: "Zug nach Berlin fährt ein auf Gleis 4".',
    ],
    options: ['Der Bahnsteig', 'Der Wartesaal', 'Der Fahrkartenschalter', 'Das Fundbüro'],
    correctAnswer: 'Der Bahnsteig',
    explanation: 'Der Bahnsteig (Gleis) ist der Einstiegsbereich für Passagiere.',
    tags: ['Bahn', 'Verkehr'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0009',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Dienstleistungsberufe',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Beruf im Dienstleistungsbereich:',
    clues: [
      'Hinweis 1: Ich wasche, schneide und färbe Haare.',
      'Hinweis 2: In meinem Salon benutze ich Schere, Kamm und Föhn.',
      'Hinweis 3: Nach dem Besuch bei mir haben die Kunden eine tolle neue Frisur.',
    ],
    options: ['Der Friseur', 'Der Schneider', 'Der Verkäufer', 'Der Kellner'],
    correctAnswer: 'Der Friseur',
    explanation: 'Der Friseur schneidet und pflegt Haare.',
    tags: ['Berufe', 'Alltag'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0010',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Recht & Finanzen',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Begriff aus dem Mietrecht:',
    clues: [
      'Hinweis 1: Ich bin ein Geldbetrag von meist 2 bis 3 Monatskaltmieten.',
      'Hinweis 2: Der Mieter zahlt mich vor dem Einzug als Sicherheit an den Vermieter.',
      'Hinweis 3: Wenn beim Auszug keine Schäden in der Wohnung sind, bekommt der Mieter mich komplett zurück.',
    ],
    options: ['Die Kaution', 'Die Provision', 'Die Nebenkosten', 'Die Mahngebühr'],
    correctAnswer: 'Die Kaution',
    explanation: 'Die Mietkaution dient dem Vermieter als finanzielle Sicherheitsleistung.',
    tags: ['Wohnen', 'Recht', 'Miete'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0011',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Medien & Freizeit',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Medium:',
    clues: [
      'Hinweis 1: Man abonniert mich digital oder bekommt mich morgens in den Briefkasten geworfen.',
      'Hinweis 2: Journalisten schreiben in mir Berichte über Politik, Sport, Kultur und das Weltgeschehen.',
      'Hinweis 3: Ich habe Schlagzeilen, Artikel und Fotos auf Papier.',
    ],
    options: ['Die Zeitung', 'Das Wörterbuch', 'Der Kalender', 'Das Kochbuch'],
    correctAnswer: 'Die Zeitung',
    explanation: 'Die Tageszeitung informiert über aktuelle Nachrichten und Ereignisse.',
    tags: ['Medien', 'Nachrichten'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0012',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Bank & Finanzen',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Maschine:',
    clues: [
      'Hinweis 1: Ich stehe in jeder Bankfiliale und oft auch im Einkaufszentrum.',
      'Hinweis 2: Man steckt seine Bankkarte hinein und tippt seine vierstellige Geheimzahl (PIN) ein.',
      'Hinweis 3: Ich spucke Geldscheine (Bargeld) aus.',
    ],
    options: ['Der Geldautomat (ATM)', 'Der Parkscheinautomat', 'Die Kaffeemaschine', 'Der Drucker'],
    correctAnswer: 'Der Geldautomat (ATM)',
    explanation: 'Am Geldautomaten hebt man Bargeld vom Bankkonto ab.',
    tags: ['Bank', 'Finanzen'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0013',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Gesundheit & Rettung',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Spezialfahrzeug:',
    clues: [
      'Hinweis 1: Ich habe Blaulicht auf dem Dach und eine laute Sirene (Tatütata).',
      'Hinweis 2: Notärzte und Rettungssanitäter fahren mit mir schnell zu verletzten Menschen.',
      'Hinweis 3: Ich transportiere Notfallpatienten mit Höchstgeschwindigkeit ins Krankenhaus.',
    ],
    options: ['Der Krankenwagen / Rettungswagen', 'Das Polizeiauto', 'Das Feuerwehrauto', 'Das Taxi'],
    correctAnswer: 'Der Krankenwagen / Rettungswagen',
    explanation: 'Der Rettungswagen bringt Notfallpatienten ins Krankenhaus.',
    tags: ['Gesundheit', 'Notfall'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0014',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Fahrzeugtechnik',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten amtlichen Nachweis im Straßenverkehr:',
    clues: [
      'Hinweis 1: Ich bin eine Plastikkarte mit Foto, die man nach bestandener Theorie- und Praxisprüfung erhält.',
      'Hinweis 2: Ohne mich darf man in Deutschland kein Auto legal auf öffentlichen Straßen fahren.',
      'Hinweis 3: Die Polizei verlangt mich bei jeder Verkehrskontrolle.',
    ],
    options: ['Der Führerschein', 'Die Fahrkarte', 'Der Personalausweis', 'Der Fahrzeugbrief'],
    correctAnswer: 'Der Führerschein',
    explanation: 'Der Führerschein berechtigt zum Führen eines Kraftfahrzeugs.',
    tags: ['Verkehr', 'Dokumente'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0015',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Wohnen & Erholung',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Bereich einer Wohnung:',
    clues: [
      'Hinweis 1: Ich bin eine kleine Plattform im Freien, die an der Außenwand der Wohnung befestigt ist.',
      'Hinweis 2: Hier stellt man Pflanzen, Blumen, einen kleinen Tisch und Stühle auf.',
      'Hinweis 3: Im Sommer frühstücken viele Menschen hier an der frischen Luft.',
    ],
    options: ['Der Balkon', 'Der Keller', 'Der Flur', 'Der Dachboden'],
    correctAnswer: 'Der Balkon',
    explanation: 'Auf dem Balkon genießt man die frische Luft und die Sonne.',
    tags: ['Wohnen', 'Erholung'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ A2: TEAM BATTLE (15 Questions: 9 EASY, 5 MEDIUM, 1 HARD)
  // =========================================================================
  {
    id: 'A2-TB-0001',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Restaurant & Rechnung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie bittet man im Restaurant höflich um die Rechnung?',
    options: ['Zahlen, bitte! / Wir möchten bitte bezahlen.', 'Geld her!', 'Gib mir die Rechnung!', 'Ich gehe jetzt.'],
    correctAnswer: 'Zahlen, bitte! / Wir möchten bitte bezahlen.',
    explanation: '"Zahlen, bitte!" oder "Wir möchten bitte bezahlen" ist die korrekte und höfliche Formulierung.',
    tags: ['Restaurant', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0002',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Arzt & Krankschreibung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was stellt der Arzt aus, wenn ein Arbeitnehmer wegen Krankheit nicht arbeiten kann?',
    options: ['Eine Arbeitsunfähigkeitsbescheinigung (Krankschreibung)', 'Einen neuen Pass', 'Eine Quittung', 'Einen Arbeitsvertrag'],
    correctAnswer: 'Eine Arbeitsunfähigkeitsbescheinigung (Krankschreibung)',
    explanation: 'Die Krankschreibung (AU-Bescheinigung) belegt die Arbeitsunfähigkeit für den Arbeitgeber.',
    tags: ['Gesundheit', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0003',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Wegbeschreibung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet die Anweisung: "Gehen Sie geradeaus bis zur Ampel"?',
    options: ['Go straight ahead until the traffic light', 'Turn left immediately', 'Go backwards', 'Stop and wait'],
    correctAnswer: 'Go straight ahead until the traffic light',
    explanation: '"geradeaus" = straight ahead; "bis zur Ampel" = until the traffic light.',
    tags: ['Stadt', 'Orientierung'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0004',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Einladung & Zusage',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Dein Freund lädt dich zu seiner Geburtstagsparty ein. Wie sagst du begeistert zu?',
    options: ['Vielen Dank für die Einladung! Ich komme sehr gerne.', 'Ich habe keine Lust.', 'Vielleicht, wenn ich nichts Besseres finde.', 'Warum feierst du?'],
    correctAnswer: 'Vielen Dank für die Einladung! Ich komme sehr gerne.',
    explanation: '"Vielen Dank für die Einladung! Ich komme sehr gerne" ist die freundliche Standardzusage.',
    tags: ['Kommunikation', 'Feier'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0005',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Hotel & Buchung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ist der Unterschied zwischen einem Einzelzimmer (EZ) und einem Doppelzimmer (DZ)?',
    options: ['Das EZ ist für 1 Person, das DZ für 2 Personen.', 'Das EZ hat kein Bad.', 'Das DZ ist immer billiger.', 'Das EZ hat zwei Betten.'],
    correctAnswer: 'Das EZ ist für 1 Person, das DZ für 2 Personen.',
    explanation: 'Einzelzimmer = 1 Person (1 Bett), Doppelzimmer = 2 Personen (Doppelbett).',
    tags: ['Hotel', 'Reisen'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0006',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Telefongespräch',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was sagt man am Telefon, wenn man den Gesprächspartner akustisch nicht verstanden hat?',
    options: ['Könnten Sie das bitte noch einmal wiederholen?', 'Halt den Mund!', 'Warum sprichst du?', 'Auf Wiederhören!'],
    correctAnswer: 'Könnten Sie das bitte noch einmal wiederholen?',
    explanation: 'Die höfliche Nachfrage lautet: "Könnten Sie das bitte wiederholen?".',
    tags: ['Telefon', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0007',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Verkehrsmittel Vergleich',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches Verkehrsmittel gilt in Deutschland als das umweltfreundlichste für Fernreisen?',
    options: ['Die Bahn (Elektrozug)', 'Das Flugzeug', 'Der Sportwagen', 'Das Kreuzfahrtschiff'],
    correctAnswer: 'Die Bahn (Elektrozug)',
    explanation: 'Die elektrische Eisenbahn hat die geringsten CO2-Emissionen pro Personenkilometer.',
    tags: ['Umwelt', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0008',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Einkaufen & Trinkgeld',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Rechnung im Café beträgt 8,40 Euro. Du gibst 10 Euro und sagst: "Stimmt so!". Wie viel Trinkgeld gibst du?',
    options: ['1,60 Euro Trinkgeld', '10 Euro Trinkgeld', 'Kein Trinkgeld', '8,40 Euro Trinkgeld'],
    correctAnswer: '1,60 Euro Trinkgeld',
    explanation: '"Stimmt so!" bedeutet, dass die Bedienung den Restbetrag (10,00 - 8,40 = 1,60 €) als Trinkgeld behalten darf.',
    tags: ['Geld', 'Kultur', 'Restaurant'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0009',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Mülltrennung in Deutschland',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wohin gehören leere Zeitungen, Hefte und Pappkartons in Deutschland?',
    options: ['In die blaue Papiertonne (Altpapier)', 'In den Biomüll', 'In den Glascontainer', 'In den Sondermüll'],
    correctAnswer: 'In die blaue Papiertonne (Altpapier)',
    explanation: 'Papier und Pappe werden in Deutschland in der blauen Papiertonne gesammelt und recycelt.',
    tags: ['Landeskunde', 'Umwelt', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0010',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Pünktlichkeit & Kultur',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Du hast um 10:00 Uhr ein Vorstellungsgespräch. Wann solltest du idealerweise eintreffen?',
    options: ['Um 09:50 bis 09:55 Uhr (etwa 5 bis 10 Minuten vorher)', 'Um 10:30 Uhr', 'Um 08:00 Uhr', 'Um 10:15 Uhr'],
    correctAnswer: 'Um 09:50 bis 09:55 Uhr (etwa 5 bis 10 Minuten vorher)',
    explanation: 'In Deutschland gilt ein Eintreffen 5-10 Minuten vor dem vereinbarten Termin als ideal pünktlich.',
    tags: ['Arbeit', 'Kultur'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0011',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Glückwünsche & Feste',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was wünscht man jemandem am 31. Dezember bzw. zum neuen Jahr?',
    options: ['Einen guten Rutsch! / Frohes neues Jahr!', 'Frohe Ostern!', 'Herzliches Beileid!', 'Gute Reise!'],
    correctAnswer: 'Einen guten Rutsch! / Frohes neues Jahr!',
    explanation: 'Vor Silvester wünscht man "Einen guten Rutsch!", am Neujahrstag "Frohes neues Jahr!".',
    tags: ['Feste', 'Bräuche'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0012',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Geografie & Nachbarländer',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie viele direkte Nachbarländer grenzen an die Bundesrepublik Deutschland?',
    options: ['9 Nachbarländer', '5 Nachbarländer', '12 Nachbarländer', '3 Nachbarländer'],
    correctAnswer: '9 Nachbarländer',
    explanation: 'Deutschland grenzt an 9 Länder: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande.',
    tags: ['Geografie', 'Landeskunde'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0013',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Berufsberatung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was macht ein "Mechatroniker"?',
    options: ['Er repariert und wartet Fahrzeuge und Maschinen (Mechanik & Elektronik).', 'Er kocht im Hotel.', 'Er pflanzt Bäume im Wald.', 'Er malt Bilder im Museum.'],
    correctAnswer: 'Er repariert und wartet Fahrzeuge und Maschinen (Mechanik & Elektronik).',
    explanation: 'Der Mechatroniker verbindet Mechanik, Elektronik und Informatik.',
    tags: ['Berufe', 'Technik'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0014',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Ruhezeiten & Nachbarschaft',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'In deutschen Mietshäusern gilt die gesetzliche Nachtruhe ab wann?',
    options: ['Ab 22:00 Uhr abends', 'Ab 18:00 Uhr', 'Ab 01:00 Uhr nachts', 'Es gibt keine Nachtruhe'],
    correctAnswer: 'Ab 22:00 Uhr abends',
    explanation: 'Ab 22:00 Uhr gilt in Deutschland Zimmerlautstärke (Nachtruhe).',
    tags: ['Wohnen', 'Kultur', 'Regeln'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0015',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Feste & Geburtstag',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was singt und wünscht man in Deutschland zum Geburtstag?',
    options: ['Zum Geburtstag viel Glück! / Herzlichen Glückwunsch!', 'Frohes Fest!', 'Gute Besserung!', 'Guten Appetit!'],
    correctAnswer: 'Zum Geburtstag viel Glück! / Herzlichen Glückwunsch!',
    explanation: 'Zum Geburtstag gratuliert man mit "Herzlichen Glückwunsch zum Geburtstag!".',
    tags: ['Feste', 'Geburtstag'],
    timeLimit: 15,
  },
];
