import { BankQuestion } from '../questionTypes.js';

/**
 * A2 Level Question Bank - Farh SprachArena
 * Levels: A2
 * Categories: Alltag, Reisen, Gesundheit, Arbeit, Schule, Wohnen, Freizeit, Einkaufen, Perfekt, Modalverben, Präpositionen, Nebensätze
 * Games: SCHNELLANTWORT, SATZ_RENNEN, WORTSCHATZ_DUELL, WAS_BIN_ICH, TEAM_BATTLE
 */
export const A2_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ A2: SCHNELLANTWORT
  // =========================================================================
  {
    id: 'A2-SA-0001',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Perfekt',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich ___ gestern Abend lange ferngesehen.',
    options: ['habe', 'bin', 'werde', 'hatte'],
    correctAnswer: 'habe',
    explanation: 'Das Verb "fernsehen" bildet das Perfekt mit dem Hilfsverb "haben".',
    tags: ['Perfekt', 'Verben'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0002',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Perfekt mit sein',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir ___ am Wochenende nach Hamburg gefahren.',
    options: ['sind', 'haben', 'waren', 'wurden'],
    correctAnswer: 'sind',
    explanation: 'Verben der Ortsveränderung (fahren, gehen, fliegen) bilden das Perfekt mit "sein".',
    tags: ['Perfekt', 'Ortsveränderung'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0003',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Modalverben im Präteritum',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Gestern war ich krank, deshalb ___ ich nicht zur Arbeit gehen.',
    options: ['konnte', 'kann', 'könnte', 'gekonnt'],
    correctAnswer: 'konnte',
    explanation: 'Vergangenheit von "können" ist das Präteritum "konnte".',
    tags: ['Modalverben', 'Präteritum'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0004',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nebensätze mit weil',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er lernt fleißig Deutsch, weil er in Frankfurt arbeiten ___.',
    options: ['möchte', 'möchten', 'mochte', 'gemocht'],
    correctAnswer: 'möchte',
    explanation: 'Im Nebensatz mit "weil" steht das konjugierte Verb am Satzende.',
    tags: ['Nebensätze', 'Kausalsatz'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0005',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Wechselpräpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wohin legst du das Buch? — Ich lege es auf ___ Schreibtisch.',
    options: ['den', 'dem', 'das', 'die'],
    correctAnswer: 'den',
    explanation: 'Frage "Wohin?" (Richtung/Aktion) verlangt den Akkusativ maskulin ("auf den Schreibtisch").',
    tags: ['Präpositionen', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0006',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Dativ-Verben',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die neue Jacke gefällt ___ sehr gut.',
    options: ['mir', 'mich', 'mein', 'ich'],
    correctAnswer: 'mir',
    explanation: 'Das Verb "gefallen" steht immer mit dem Dativ ("mir").',
    tags: ['Verben', 'Dativ'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0007',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Nebensätze mit wenn',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn das Wetter schön ist, ___ wir im Park spazieren.',
    options: ['gehen', 'wir gehen', 'gegangen', 'gingen'],
    correctAnswer: 'gehen',
    explanation: 'Nach einem vorangestellten Wenn-Satz folgt im Hauptsatz sofort das Verb an Position 1.',
    tags: ['Konditionalsatz', 'Inversion'],
    timeLimit: 15,
  },
  {
    id: 'A2-SA-0008',
    level: 'A2',
    gameType: 'SCHNELLANTWORT',
    category: 'Einkaufen & Kleidung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Größe haben Sie? — Ich trage Größe ___ .',
    options: ['M', 'Kilo', 'Liter', 'Meter'],
    correctAnswer: 'M',
    explanation: 'Kleidergrößen werden in S, M, L, XL angegeben.',
    tags: ['Einkaufen', 'Kleidung'],
    timeLimit: 12,
  },

  // =========================================================================
  // 🧩 A2: SATZ-RENNEN
  // =========================================================================
  {
    id: 'A2-SR-0001',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Zeit- und Ortsangaben',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz in die korrekte Reihenfolge:',
    words: ['Ich', 'fahre', 'morgen', 'nach Berlin.'],
    correctOrder: ['Ich', 'fahre', 'morgen', 'nach Berlin.'],
    correctAnswer: ['Ich', 'fahre', 'morgen', 'nach Berlin.'],
    explanation: 'Im Hauptsatz steht die Zeitangabe (morgen) vor der Ortsangabe (nach Berlin).',
    tags: ['Satzbau', 'TeKaMoLo'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0002',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Nebensätze mit weil',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Satzteile in die richtige Reihenfolge:',
    words: ['Ich bleibe zu Hause,', 'weil ich', 'heute', 'krank bin.'],
    correctOrder: ['Ich bleibe zu Hause,', 'weil ich', 'heute', 'krank bin.'],
    correctAnswer: ['Ich bleibe zu Hause,', 'weil ich', 'heute', 'krank bin.'],
    explanation: 'Im Nebensatz mit "weil" wandert das finite Verb ("bin") ganz ans Satzende.',
    tags: ['Nebensatz', 'Kausalsatz'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0003',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Trennbare Verben',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde einen Satz mit dem trennbaren Verb "aufstehen":',
    words: ['Am Wochenende', 'stehe', 'ich', 'erst um neun Uhr', 'auf.'],
    correctOrder: ['Am Wochenende', 'stehe', 'ich', 'erst um neun Uhr', 'auf.'],
    correctAnswer: ['Am Wochenende', 'stehe', 'ich', 'erst um neun Uhr', 'auf.'],
    explanation: 'Bei trennbaren Verben steht die Vorsilbe ("auf") am Satzende (Verbklammer).',
    tags: ['Trennbare Verben', 'Satzklammer'],
    timeLimit: 25,
  },
  {
    id: 'A2-SR-0004',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Nebensätze mit dass',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit "dass" in die richtige Struktur:',
    words: ['Der Lehrer sagt,', 'dass wir', 'die Hausaufgaben', 'machen müssen.'],
    correctOrder: ['Der Lehrer sagt,', 'dass wir', 'die Hausaufgaben', 'machen müssen.'],
    correctAnswer: ['Der Lehrer sagt,', 'dass wir', 'die Hausaufgaben', 'machen müssen.'],
    explanation: 'Im Nebensatz mit Modalverb steht das konjugierte Modalverb ("müssen") ganz am Ende.',
    tags: ['Nebensatz', 'Modalverben'],
    timeLimit: 30,
  },
  {
    id: 'A2-SR-0005',
    level: 'A2',
    gameType: 'SATZ_RENNEN',
    category: 'Reisen & Urlaub',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Urlaubssatz in die richtige Reihenfolge:',
    words: ['Wir', 'haben', 'letzte Woche', 'ein schönes Hotel', 'gebucht.'],
    correctOrder: ['Wir', 'haben', 'letzte Woche', 'ein schönes Hotel', 'gebucht.'],
    correctAnswer: ['Wir', 'haben', 'letzte Woche', 'ein schönes Hotel', 'gebucht.'],
    explanation: 'Perfekt-Satzklammer: Hilfsverb "haben" an Position 2, Partizip II "gebucht" am Satzende.',
    tags: ['Perfekt', 'Reisen'],
    timeLimit: 25,
  },

  // =========================================================================
  // 🧠 A2: WORTSCHATZ-DUELL
  // =========================================================================
  {
    id: 'A2-WD-0001',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Haushalt & Technik',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Kühlschrank',
    focusWord: 'der Kühlschrank',
    question: 'Was bedeutet "der Kühlschrank"?',
    options: ['Refrigerator', 'Washing machine', 'Dishwasher', 'Microwave oven'],
    correctAnswer: 'Refrigerator',
    explanation: '"Der Kühlschrank" kühlt Lebensmittel.',
    tags: ['Haushalt', 'Geräte'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0002',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesundheit & Körper',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Kopfschmerzen',
    focusWord: 'die Kopfschmerzen',
    question: 'Was bedeutet "die Kopfschmerzen"?',
    options: ['Headache', 'Stomach ache', 'Toothache', 'Sore throat'],
    correctAnswer: 'Headache',
    explanation: 'Kopfschmerzen = Schmerzen im Kopf (Headache).',
    tags: ['Gesundheit', 'Arzt'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0003',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Verkehrsmittel',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Train / Railway (قطار)',
    focusWord: 'Train / Railway (قطار)',
    question: 'Wie heißt das deutsche Wort für "Train"?',
    options: ['der Zug', 'das Flugzeug', 'das Schiff', 'die Straßenbahn'],
    correctAnswer: 'der Zug',
    explanation: 'Train = der Zug / die Bahn.',
    tags: ['Reisen', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0004',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeitswelt',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Lebenslauf',
    focusWord: 'der Lebenslauf',
    question: 'Was bedeutet "der Lebenslauf" bei einer Bewerbung?',
    options: ['Curriculum Vitae / Resume (CV)', 'Job interview', 'Employment contract', 'Cover letter'],
    correctAnswer: 'Curriculum Vitae / Resume (CV)',
    explanation: 'Der Lebenslauf ist der tabellarische CV in der Bewerbung.',
    tags: ['Arbeit', 'Bewerbung'],
    timeLimit: 15,
  },
  {
    id: 'A2-WD-0005',
    level: 'A2',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Alltag & Einkaufen',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Quittung / der Kassenbon',
    focusWord: 'die Quittung / der Kassenbon',
    question: 'Was ist eine "Quittung" oder ein "Kassenbon"?',
    options: ['Sales receipt / Payment proof', 'Credit card invoice', 'Price discount tag', 'Shopping voucher'],
    correctAnswer: 'Sales receipt / Payment proof',
    explanation: 'Der Kassenbon / die Quittung ist der Kaufbeleg.',
    tags: ['Einkaufen', 'Alltag'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ A2: WAS BIN ICH?
  // =========================================================================
  {
    id: 'A2-WB-0001',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Berufe',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Person / den Beruf:',
    clues: [
      'Hinweis 1: Ich arbeite meistens im Krankenhaus oder in einer Praxis.',
      'Hinweis 2: Ich trage oft einen weißen Kittel und ein Stethoskop.',
      'Hinweis 3: Ich untersuche Patienten und verschreibe Medikamente.',
    ],
    options: ['Arzt / Ärztin', 'Lehrer / Lehrerin', 'Polizist / Polizistin', 'Koch / Köchin'],
    correctAnswer: 'Arzt / Ärztin',
    explanation: 'Der Arzt / die Ärztin behandelt Patienten im Krankenhaus.',
    tags: ['Berufe', 'Gesundheit'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0002',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Orte & Gebäude',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Ort:',
    clues: [
      'Hinweis 1: Hier gibt es viele Gleise und Züge.',
      'Hinweis 2: Viele Reisende kaufen hier Fahrkarten oder warten auf ihren Zug.',
      'Hinweis 3: ICEs und Regionalbahnen halten hier täglich.',
    ],
    options: ['Der Bahnhof', 'Der Flughafen', 'Die Schule', 'Das Kino'],
    correctAnswer: 'Der Bahnhof',
    explanation: 'Der Bahnhof ist der Ort für Züge und Bahnreisen.',
    tags: ['Orte', 'Reisen'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0003',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Technik & Haushalt',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Gerät:',
    clues: [
      'Hinweis 1: Ich stehe in vielen Küchen oder im Keller.',
      'Hinweis 2: Man füllt schmutzige Kleidung und Waschmittel in meine Trommel.',
      'Hinweis 3: Ich drehe mich schnell und schleudere das Wasser heraus.',
    ],
    options: ['Die Waschmaschine', 'Der Kühlschrank', 'Die Mikrowelle', 'Der Fernseher'],
    correctAnswer: 'Die Waschmaschine',
    explanation: 'Die Waschmaschine wäscht Kleidung mit Trommel und Schleudergang.',
    tags: ['Haushalt', 'Technik'],
    timeLimit: 24,
  },
  {
    id: 'A2-WB-0004',
    level: 'A2',
    gameType: 'WAS_BIN_ICH',
    category: 'Gesundheit & Medizin',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Geschäft / Gebäude:',
    clues: [
      'Hinweis 1: Man erkennt mich oft an einem großen roten "A" als Logo.',
      'Hinweis 2: Hier holt man Schmerztabletten, Pflaster und Vitamine.',
      'Hinweis 3: Man kann hier ärztliche Rezepte einlösen.',
    ],
    options: ['Die Apotheke', 'Die Bäckerei', 'Die Post', 'Die Bank'],
    correctAnswer: 'Die Apotheke',
    explanation: 'In der Apotheke kauft man Medikamente und löst Rezepte ein.',
    tags: ['Gesundheit', 'Stadt'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ A2: TEAM BATTLE
  // =========================================================================
  {
    id: 'A2-TB-0001',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Komparativ & Superlativ',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ein Flugzeug ist ___ als ein Fahrrad.',
    options: ['schneller', 'schnell', 'am schnellsten', 'mehr schnell'],
    correctAnswer: 'schneller',
    explanation: 'Komparativ von schnell mit "als" = "schneller".',
    tags: ['Adjektive', 'Vergleich'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0002',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Modalverben / Regeln',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Hier ist Parkverbot. Man ___ hier nicht parken.',
    options: ['darf', 'muss', 'kann', 'will'],
    correctAnswer: 'darf',
    explanation: 'Ein Verbot wird mit "nicht dürfen" ausgedrückt.',
    tags: ['Modalverben', 'Verbot'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0003',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Präpositionen der Zeit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Deutschkurs beginnt ___ Montag um 9:00 Uhr.',
    options: ['am', 'im', 'um', 'an'],
    correctAnswer: 'am',
    explanation: 'Bei Wochentagen und Tageszeiten steht "am" (an dem).',
    tags: ['Temporale Präpositionen', 'Zeit'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0004',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Reflexive Verben',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich freue mich sehr ___ die Ferien.',
    options: ['auf', 'über', 'an', 'für'],
    correctAnswer: 'auf',
    explanation: '"Sich freuen auf" bezieht sich auf die Zukunft (die kommenden Ferien).',
    tags: ['Reflexive Verben', 'Präpositionalergänzung'],
    timeLimit: 15,
  },
  {
    id: 'A2-TB-0005',
    level: 'A2',
    gameType: 'TEAM_BATTLE',
    category: 'Gesundheit & Ratschläge',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn man Fieber hat, ___ man viel Wasser trinken und sich ausruhen.',
    options: ['sollte', 'wollte', 'durfte', 'konntet'],
    correctAnswer: 'sollte',
    explanation: 'Für Ratschläge und Empfehlungen verwendet man "sollte".',
    tags: ['Modalverben', 'Gesundheit'],
    timeLimit: 15,
  },
];
