import { BankQuestion } from '../questionTypes.js';

/**
 * B1 Level Question Bank - Farh SprachArena
 * Levels: B1
 * Categories: Beruf, Gesellschaft, Umwelt, Medien, Reisen, Bildung, Technologie, Grammatik, Konnektoren, Relativsätze, Passiv, Konjunktiv II
 * Games: SCHNELLANTWORT, SATZ_RENNEN, WORTSCHATZ_DUELL, WAS_BIN_ICH, TEAM_BATTLE
 */
export const B1_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ B1: SCHNELLANTWORT
  // =========================================================================
  {
    id: 'B1-SA-0001',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Konjunktiv II',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn ich mehr Zeit hätte, ___ ich gerne öfter reisen.',
    options: ['würde', 'werde', 'hätte', 'wäre'],
    correctAnswer: 'würde',
    explanation: 'Hypothetische Wünsche mit Vollverben werden mit "würde + Infinitiv" gebildet.',
    tags: ['Konjunktiv II', 'Hypothese'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0002',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Vorgangspassiv',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das neue Rathaus ___ im letzten Jahr eröffnet.',
    options: ['wurde', 'worden', 'hatte', 'ist'],
    correctAnswer: 'wurde',
    explanation: 'Passiv Präteritum: "wurde + Partizip II" (eröffnet).',
    tags: ['Passiv', 'Präteritum'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0003',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativsätze im Dativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist der Kollege, ___ ich gestern beim Umzug geholfen habe.',
    options: ['dem', 'den', 'der', 'dessen'],
    correctAnswer: 'dem',
    explanation: '"Helfen" verlangt den Dativ maskulin: "dem ich geholfen habe".',
    tags: ['Relativsätze', 'Dativ'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0004',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektoren (obwohl vs. trotzdem)',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: '___ es stark regnete, machten wir einen langen Spaziergang.',
    options: ['Obwohl', 'Trotzdem', 'Weil', 'Deshalb'],
    correctAnswer: 'Obwohl',
    explanation: '"Obwohl" leitet einen konzessiven Nebensatz mit Verb am Ende ein.',
    tags: ['Konnektoren', 'Konzessivsatz'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0005',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit festen Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Er nimmt seit zwei Monaten ___ diesem Fortbildungskurs teil.',
    options: ['an', 'bei', 'in', 'auf'],
    correctAnswer: 'an',
    explanation: '"Teilnehmen an" verlangt immer die Präposition "an + Dativ".',
    tags: ['Präpositionalverben', 'Dativ'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0006',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Infinitiv mit zu',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich habe vor, im Sommer eine Prüfung ___ .',
    options: ['abzulegen', 'ablegen zu', 'abzulegend', 'abgelegt'],
    correctAnswer: 'abzulegen',
    explanation: 'Bei trennbaren Verben schiebt sich das "zu" zwischen Vorsilbe und Stamm: "ab-zu-legen".',
    tags: ['Infinitiv', 'Trennbare Verben'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0007',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Plusquamperfekt',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Nachdem er die E-Mail ___ , verließ er das Büro.',
    options: ['abgeschickt hatte', 'abschickt', 'abschicken würde', 'abgeschickt hat'],
    correctAnswer: 'abgeschickt hatte',
    explanation: '"Nachdem" verlangt Vorzeitigkeit: Im Hauptsatz Präteritum ("verließ"), im Nebensatz Plusquamperfekt ("abgeschickt hatte").',
    tags: ['Temporalsatz', 'Plusquamperfekt'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0008',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Genitiv-Attribute',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist das neue Auto ___ Chefs.',
    options: ['des', 'dem', 'den', 'das'],
    correctAnswer: 'des',
    explanation: 'Genitiv maskulin: "des Chefs".',
    tags: ['Genitiv', 'Besitz'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 B1: SATZ-RENNEN
  // =========================================================================
  {
    id: 'B1-SR-0001',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Relativsätze',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Relativsatz in die richtige Reihenfolge:',
    words: ['Das ist der Mann,', 'der mir', 'gestern', 'im Zug', 'geholfen hat.'],
    correctOrder: ['Das ist der Mann,', 'der mir', 'gestern', 'im Zug', 'geholfen hat.'],
    correctAnswer: ['Das ist der Mann,', 'der mir', 'gestern', 'im Zug', 'geholfen hat.'],
    explanation: 'Im Relativsatz steht das Hilfsverb / finite Verb ("hat") ganz am Satzende.',
    tags: ['Relativsatz', 'Nebensatz'],
    timeLimit: 30,
  },
  {
    id: 'B1-SR-0002',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Finalsätze mit um...zu',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Infinitivkonstruktion in die richtige Reihenfolge:',
    words: ['Er lernt jeden Tag,', 'um seine Deutschprüfung', 'erfolgreich', 'zu bestehen.'],
    correctOrder: ['Er lernt jeden Tag,', 'um seine Deutschprüfung', 'erfolgreich', 'zu bestehen.'],
    correctAnswer: ['Er lernt jeden Tag,', 'um seine Deutschprüfung', 'erfolgreich', 'zu bestehen.'],
    explanation: 'Infinitivsatz: "um" am Anfang der Konstruktion, "zu + Infinitiv" ganz am Ende.',
    tags: ['Finalsatz', 'Infinitiv mit zu'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0003',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Zweiteilige Konnektoren (sowohl...als auch)',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit "sowohl ... als auch":',
    words: ['Sie spricht', 'sowohl fließend Deutsch', 'als auch', 'ausgezeichnetes Englisch.'],
    correctOrder: ['Sie spricht', 'sowohl fließend Deutsch', 'als auch', 'ausgezeichnetes Englisch.'],
    correctAnswer: ['Sie spricht', 'sowohl fließend Deutsch', 'als auch', 'ausgezeichnetes Englisch.'],
    explanation: '"Sowohl ... als auch" verbindet zwei gleichwertige Satzglieder oder Objekte.',
    tags: ['Konnektoren', 'Doppelkonnektor'],
    timeLimit: 30,
  },
  {
    id: 'B1-SR-0004',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Temporalsatz mit während',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit "während" in die korrekte Struktur:',
    words: ['Während ich koche,', 'hört meine Schwester', 'gerne', 'klassische Musik.'],
    correctOrder: ['Während ich koche,', 'hört meine Schwester', 'gerne', 'klassische Musik.'],
    correctAnswer: ['Während ich koche,', 'hört meine Schwester', 'gerne', 'klassische Musik.'],
    explanation: 'Beginnt der Nebensatz zuerst, folgt im Hauptsatz sofort das konjugierte Verb an Position 1.',
    tags: ['Temporalsatz', 'Inversion'],
    timeLimit: 30,
  },
  {
    id: 'B1-SR-0005',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Konzessivsatz mit obwohl',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit "obwohl" in die korrekte Reihenfolge:',
    words: ['Obwohl er müde war,', 'hat er', 'die Präsentation', 'fertiggestellt.'],
    correctOrder: ['Obwohl er müde war,', 'hat er', 'die Präsentation', 'fertiggestellt.'],
    correctAnswer: ['Obwohl er müde war,', 'hat er', 'die Präsentation', 'fertiggestellt.'],
    explanation: 'Nach dem vorangestellten Nebensatz folgt das finite Verb ("hat") im Hauptsatz an Position 1.',
    tags: ['Konzessivsatz', 'Satzstruktur'],
    timeLimit: 25,
  },

  // =========================================================================
  // 🧠 B1: WORTSCHATZ-DUELL
  // =========================================================================
  {
    id: 'B1-WD-0001',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeitsmarkt & Karriere',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Bewerbungsunterlagen',
    focusWord: 'die Bewerbungsunterlagen',
    question: 'Was bezeichnet der Begriff "die Bewerbungsunterlagen"?',
    options: ['Application dossier (CV, certificates, cover letter)', 'Tax declaration documents', 'Rental agreement contracts', 'Identity documents'],
    correctAnswer: 'Application dossier (CV, certificates, cover letter)',
    explanation: 'Bewerbungsunterlagen umfassen Anschreiben, Lebenslauf und Zeugnisse.',
    tags: ['Beruf', 'Bewerbung'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0002',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Umweltschutz',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Mülltrennung',
    focusWord: 'die Mülltrennung',
    question: 'Was bedeutet "die Mülltrennung"?',
    options: ['Waste separation / Recycling sorting', 'Trash incineration', 'Street cleaning', 'Plastic production'],
    correctAnswer: 'Waste separation / Recycling sorting',
    explanation: 'Mülltrennung ist das Sortieren von Wertstoffen und Abfall.',
    tags: ['Umwelt', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0003',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kommunikation',
    difficulty: 'HARD',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'To exchange opinions (تبادل الآراء)',
    focusWord: 'To exchange opinions (تبادل الآراء)',
    question: 'Welches Verb bedeutet "Meinungen austauschen"?',
    options: ['diskutieren / sich austauschen', 'widersprechen', 'überzeugen', 'vernachlässigen'],
    correctAnswer: 'diskutieren / sich austauschen',
    explanation: '"Sich austauschen" bedeutet Meinungen oder Erfahrungen teilen.',
    tags: ['Kommunikation', 'Redemittel'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0004',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Technik & Medien',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Datenschutzgesetz',
    focusWord: 'das Datenschutzgesetz',
    question: 'Was ist "das Datenschutzgesetz"?',
    options: ['Data protection law / Privacy legislation', 'Cybersecurity firewall', 'Social media terms', 'Telecommunications tax'],
    correctAnswer: 'Data protection law / Privacy legislation',
    explanation: 'Das Datenschutzgesetz schützt personenbezogene Daten der Bürger.',
    tags: ['Recht', 'Medien'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0005',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesellschaft & Bildung',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Fortbildung',
    focusWord: 'die Fortbildung',
    question: 'Was versteht man unter einer "Fortbildung"?',
    options: ['Further professional training / Skill development', 'Primary school enrolment', 'University graduation ceremony', 'Driver license exam'],
    correctAnswer: 'Further professional training / Skill development',
    explanation: 'Fortbildung ist die berufliche Weiterqualifikation.',
    tags: ['Bildung', 'Beruf'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ B1: WAS BIN ICH?
  // =========================================================================
  {
    id: 'B1-WB-0001',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Digitale Medien & Geräte',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Gerät / Medium:',
    clues: [
      'Hinweis 1: Ich bin flach, rechteckig und bestehe meistens aus Glas und Aluminium.',
      'Hinweis 2: Viele Menschen verbringen täglich mehrere Stunden mit meinen Apps.',
      'Hinweis 3: Mit mir kann man chatten, navigieren, Fotos machen und bargeldlos bezahlen.',
    ],
    options: ['Das Smartphone', 'Das Radio', 'Der Taschenrechner', 'Die Armbanduhr'],
    correctAnswer: 'Das Smartphone',
    explanation: 'Das Smartphone vereint Kommunikation, Internet, Kamera und Apps.',
    tags: ['Medien', 'Technik'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0002',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Bildungseinrichtungen',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Institution:',
    clues: [
      'Hinweis 1: Hier studieren Tausende junge Menschen nach dem Abitur.',
      'Hinweis 2: Professoren halten Vorlesungen in großen Hörsälen.',
      'Hinweis 3: Am Ende erhält man einen Bachelor- oder Master-Abschluss.',
    ],
    options: ['Die Universität', 'Der Kindergarten', 'Die Volkshochschule', 'Die Fahrschule'],
    correctAnswer: 'Die Universität',
    explanation: 'An der Universität studiert man und erlangt akademische Grade.',
    tags: ['Bildung', 'Akademie'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0003',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Recht & Arbeit',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Dokument:',
    clues: [
      'Hinweis 1: Ich werde zwischen einem Arbeitgeber und einem Arbeitnehmer geschlossen.',
      'Hinweis 2: In mir stehen Gehalt, Urlaubstage, Wochenstunden und Kündigungsfristen.',
      'Hinweis 3: Beide Parteien müssen mich handschriftlich oder digital unterschreiben.',
    ],
    options: ['Der Arbeitsvertrag', 'Der Mietvertrag', 'Das Flugticket', 'Der Kassenzettel'],
    correctAnswer: 'Der Arbeitsvertrag',
    explanation: 'Der Arbeitsvertrag regelt die Arbeitsbedingungen und Pflichten.',
    tags: ['Arbeit', 'Recht'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0004',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Umwelt & Energie',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Energiequelle:',
    clues: [
      'Hinweis 1: Ich habe riesige weiße Rotorblätter, die sich im Wind drehen.',
      'Hinweis 2: Man findet mich oft auf Feldern oder im Meer (Offshore-Parks).',
      'Hinweis 3: Ich erzeuge sauberen, erneuerbaren Strom ohne CO2-Ausstoß.',
    ],
    options: ['Die Windkraftanlage / Windrad', 'Das Atomkraftwerk', 'Das Kohlekraftwerk', 'Der Dieselgenerator'],
    correctAnswer: 'Die Windkraftanlage / Windrad',
    explanation: 'Das Windrad erzeugt Strom aus Windenergie.',
    tags: ['Umwelt', 'Energie'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ B1: TEAM BATTLE
  // =========================================================================
  {
    id: 'B1-TB-0001',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Deutsche Geschichte & Landeskunde',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'In welchem Jahr fiel die Berliner Mauer?',
    options: ['1989', '1990', '1985', '1995'],
    correctAnswer: '1989',
    explanation: 'Die Berliner Mauer fiel am 9. November 1989.',
    tags: ['Landeskunde', 'Geschichte'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0002',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Redewendungen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet die Redewendung "jemandem die Daumen drücken"?',
    options: ['Jemandem viel Glück und Erfolg wünschen', 'Jemanden bestrafen', 'Sich vor etwas fürchten', 'Wütend auf jemanden sein'],
    correctAnswer: 'Jemandem viel Glück und Erfolg wünschen',
    explanation: '"Die Daumen drücken" = viel Erfolg wünschen.',
    tags: ['Redewendungen', 'Alltagssprache'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0003',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Genitiv / Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ des starken Schneesturms blieben alle Züge im Bahnhof stehen.',
    options: ['Wegen', 'Trotz', 'Statt', 'Außerhalb'],
    correctAnswer: 'Wegen',
    explanation: '"Wegen + Genitiv" drückt die Ursache/den Grund aus.',
    tags: ['Genitiv', 'Kausal'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0004',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Passiv mit Modalverben',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Rechnungen ___ bis Freitag bezahlt werden.',
    options: ['müssen', 'worden', 'haben', 'wären'],
    correctAnswer: 'müssen',
    explanation: 'Passiv mit Modalverb: "müssen + Partizip II (bezahlt) + werden".',
    tags: ['Passiv', 'Modalverben'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0005',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Geografie & Bundesländer',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie viele Bundesländer hat die Bundesrepublik Deutschland?',
    options: ['16', '14', '18', '12'],
    correctAnswer: '16',
    explanation: 'Deutschland besteht aus 16 Bundesländern.',
    tags: ['Landeskunde', 'Politik'],
    timeLimit: 15,
  },
];
