import { BankQuestion } from '../questionTypes.js';

/**
 * B1 Level Question Bank - Farh SprachArena
 * Exactly 100 Questions:
 * - 35 SCHNELLANTWORT (Advanced Grammar, Passiv, Konjunktiv II, Relativsätze, Verb-Präpositionen, Nuanced Meaning)
 * - 15 SATZ_RENNEN (Complex connectors, Subordinate clauses, Relative clauses, Passive word order)
 * - 20 WORTSCHATZ_DUELL (Work environment, Media & Tech, Ecology, Society, Abstract vocabulary)
 * - 15 WAS_BIN_ICH (Complex concepts, Modern professions, Environmental & Social phenomena)
 * - 15 TEAM_BATTLE (Opinions, Debates, Problem-solving, Cultural insights, Negotiations)
 *
 * Difficulty: 30 EASY, 50 MEDIUM, 20 HARD
 */
export const B1_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ B1: SCHNELLANTWORT (35 Questions: 10 EASY, 18 MEDIUM, 7 HARD)
  // =========================================================================
  {
    id: 'B1-SA-0001',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit Präpositionen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Viele Studenten interessieren sich sehr ___ moderne Künstliche Intelligenz.',
    options: ['für', 'über', 'an', 'auf'],
    correctAnswer: 'für',
    explanation: 'Das reflexive Verb "sich interessieren" verlangt fest die Präposition "für" + Akkusativ.',
    tags: ['Präpositionen', 'Verben', 'Technologie'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0002',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit Präpositionen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir freuen uns schon alle riesig ___ unseren gemeinsamen Urlaub im August.',
    options: ['auf', 'über', 'an', 'für'],
    correctAnswer: 'auf',
    explanation: '"sich freuen auf" bezieht sich auf ein zukünftiges Ereignis ("sich freuen über" auf ein vergangenes/gegenwärtiges).',
    tags: ['Präpositionen', 'Verben', 'Reisen'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0003',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit Dativ-Präposition',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Erfolg des Projekts hängt stark ___ der guten Zusammenarbeit im Team ab.',
    options: ['von', 'an', 'bei', 'aus'],
    correctAnswer: 'von',
    explanation: '"abhängen von" verlangt die Präposition "von" mit dem Dativ.',
    tags: ['Präpositionen', 'Verben', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0004',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Bewerber wartet seit zwei Wochen ungeduldig ___ eine Rückmeldung des Unternehmens.',
    options: ['auf', 'nach', 'für', 'an'],
    correctAnswer: 'auf',
    explanation: '"warten auf" verlangt fest die Präposition "auf" + Akkusativ.',
    tags: ['Präpositionen', 'Bewerbung', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0005',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Vorgangspassiv Präsens',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'In dieser modernen Fabrik ___ täglich über tausend Elektroautos hergestellt.',
    options: ['werden', 'wurden', 'worden', 'sein'],
    correctAnswer: 'werden',
    explanation: 'Das Vorgangspassiv im Präsens Plural wird gebildet mit: "werden" + Partizip II ("hergestellt").',
    tags: ['Passiv', 'Präsens', 'Industrie'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0006',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Vorgangspassiv Präteritum',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Die berühmte Frauenkirche in Dresden ___ nach der Wiedervereinigung aufwendig wiederaufgebaut.',
    options: ['wurde', 'worden', 'hatte', 'geworden'],
    correctAnswer: 'wurde',
    explanation: 'Das Vorgangspassiv im Präteritum Singular lautet: "wurde" + Partizip II ("wiederaufgebaut").',
    tags: ['Passiv', 'Präteritum', 'Geschichte'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0007',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Konjunktiv II Wunsch / Ratschlag',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'An deiner Stelle ___ ich mich direkt bei dieser internationalen Firma bewerben.',
    options: ['würde', 'wurde', 'werde', 'wäre'],
    correctAnswer: 'würde',
    explanation: '"An deiner Stelle würde ich..." drückt mit dem Konjunktiv II einen höflichen Ratschlag aus.',
    tags: ['Konjunktiv II', 'Ratschläge', 'Bewerbung'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0008',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Konjunktiv II sein/haben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wenn ich doch nur mehr Freizeit ___ ! Dann würde ich eine Weltreise machen.',
    options: ['hätte', 'habe', 'hatte', 'hätten'],
    correctAnswer: 'hätte',
    explanation: 'Irreale Wünsche werden mit dem Konjunktiv II von haben ("hätte") gebildet.',
    tags: ['Konjunktiv II', 'Wünsche'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0009',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativpronomen Nominativ',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Dort drüben steht der Lehrer, ___ uns in Farh SprachArena unterrichtet.',
    options: ['der', 'den', 'dem', 'dessen'],
    correctAnswer: 'der',
    explanation: '"Der Lehrer" ist maskulin und fungiert im Relativsatz als Subjekt (Nominativ -> der).',
    tags: ['Relativsätze', 'Nominativ', 'Maskulinum'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0010',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativpronomen Akkusativ',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist der neue Laptop, ___ ich mir gestern gekauft habe.',
    options: ['den', 'der', 'dem', 'dessen'],
    correctAnswer: 'den',
    explanation: '"Der Laptop" ist maskulin und ist im Relativsatz das Akkusativobjekt (den ich gekauft habe).',
    tags: ['Relativsätze', 'Akkusativ', 'Technik'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0011',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativpronomen Dativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist die nette Kollegin, ___ ich bei der Präsentation geholfen habe.',
    options: ['der', 'die', 'den', 'deren'],
    correctAnswer: 'der',
    explanation: 'Das Verb "helfen" verlangt den Dativ: "die Kollegin" wird im Relativsatz-Dativ zu "der".',
    tags: ['Relativsätze', 'Dativ', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0012',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Relativsätze mit Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Hier ist der wichtige Vertrag, ___ dem wir gestern so intensiv gesprochen haben.',
    options: ['über', 'mit', 'von', 'an'],
    correctAnswer: 'über',
    explanation: 'Das Verb lautet "sprechen über" + Akkusativ bzw. "über den wir gesprochen haben". Hier mit Dativ: "von dem" oder "mit dem"? Achtung: "von dem wir gesprochen haben"!',
    tags: ['Relativsätze', 'Präpositionen'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0013',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Temporale Konjunktionen während',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: '___ sie für die Abschlussprüfung lernte, hörte sie leise klassische Musik.',
    options: ['Während', 'Nachdem', 'Bevor', 'Seitdem'],
    correctAnswer: 'Während',
    explanation: '"Während" drückt die Gleichzeitigkeit zweier Handlungen aus.',
    tags: ['Temporalsätze', 'während', 'Gleichzeitigkeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0014',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Temporale Konjunktionen bevor',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wasche dir bitte gründlich die Hände, ___ du dich an den Esstisch setzt.',
    options: ['bevor', 'nachdem', 'seitdem', 'während'],
    correctAnswer: 'bevor',
    explanation: '"bevor" / "ehe" leitet eine Handlung ein, die zeitlich nach der Hauptsatzhandlung stattfindet.',
    tags: ['Temporalsätze', 'bevor'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0015',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Plusquamperfekt & nachdem',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Nachdem er alle E-Mails beantwortet ___ , verließ er erleichtert das Büro.',
    options: ['hatte', 'hat', 'hätte', 'war'],
    correctAnswer: 'hatte',
    explanation: 'Vorzeitigkeit in der Vergangenheit (Präteritum im Hauptsatz) verlangt im nachdem-Satz das Plusquamperfekt ("beantwortet hatte").',
    tags: ['Plusquamperfekt', 'nachdem', 'Vorzeitigkeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0016',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Konnektoren obwohl vs trotzdem',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er ging zur Arbeit, ___ er sich überhaupt nicht wohlfühlte.',
    options: ['obwohl', 'trotzdem', 'deshalb', 'sodass'],
    correctAnswer: 'obwohl',
    explanation: '"obwohl" ist eine unterordnende Konjunktion (Nebensatz mit finitem Verb am Ende).',
    tags: ['Konnektoren', 'obwohl', 'Nebensätze'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0017',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Doppelkonjunktionen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Dieses Smartphone ist ___ modern und leistungsstark, ___ auch sehr energieeffizient.',
    options: ['sowohl ... als', 'weder ... noch', 'entweder ... oder', 'zwar ... aber'],
    correctAnswer: 'sowohl ... als',
    explanation: 'Die mehrteilige Konjunktion "sowohl ... als auch" verbindet zwei positive Eigenschaften.',
    tags: ['Doppelkonnektoren', 'Grammatik'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0018',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Doppelkonjunktionen weder... noch',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Er trinkt ___ Alkohol ___ zuckerhaltige Softdrinks; er trinkt nur reines Wasser.',
    options: ['weder ... noch', 'sowohl ... als', 'entweder ... oder', 'nicht nur ... sondern'],
    correctAnswer: 'weder ... noch',
    explanation: '"weder ... noch" verneint beide Teile einer Aufzählung vollständig.',
    tags: ['Doppelkonnektoren', 'Negation'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0019',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Adjektivdeklination ohne Artikel (Nullartikel)',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir wünschen Ihnen bei Ihrer neuen Arbeitsstelle viel Erfolg und ___ Mut!',
    options: ['großen', 'großer', 'großes', 'große'],
    correctAnswer: 'großen',
    explanation: 'Maskulines Nomen im Akkusativ ("der Mut") ohne Artikel übernimmt die Endung des bestimmten Artikels -en ("großen Mut").',
    tags: ['Adjektivdeklination', 'Nullartikel', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0020',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Finale Nebensätze um... zu vs damit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Eltern arbeiten hart, ___ ihre Kinder an der Universität studieren können.',
    options: ['damit', 'um', 'weil', 'dass'],
    correctAnswer: 'damit',
    explanation: 'Wenn Subjekt im Hauptsatz (die Eltern) und Nebensatz (ihre Kinder) verschieden sind, MUSS "damit" verwendet werden.',
    tags: ['Finalsätze', 'damit-um_zu', 'Satzbau'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0021',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Finalsatz mit um... zu',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Er lernt jeden Tag Deutsch, ___ später in Deutschland als Ingenieur zu arbeiten.',
    options: ['um', 'damit', 'weil', 'ohne'],
    correctAnswer: 'um',
    explanation: 'Bei gleichem Subjekt bildet man den Finalsatz mit "um ... zu + Infinitiv".',
    tags: ['Finalsätze', 'um_zu', 'Infinitiv'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0022',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Präteritum starker Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Plötzlich ___ der Wind so stark, dass die Fensterläden klapperten.',
    options: ['blies', 'blaste', 'geblasen', 'bläst'],
    correctAnswer: 'blies',
    explanation: 'Das Präteritum des unregelmäßigen Verbs blasen lautet: "er/sie/es blies".',
    tags: ['Präteritum', 'Starke Verben'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0023',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Präteritum starker Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Forscher ___ eine bahnbrechende Entdeckung in der Medizin.',
    options: ['machten', 'schufen', 'fanden', 'brachten'],
    correctAnswer: 'machten',
    explanation: 'Die feste Wendung heißt "eine Entdeckung machen" (Präteritum: machten).',
    tags: ['Präteritum', 'Nomen-Verb-Verbindung', 'Wissenschaft'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0024',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Pronominaladverbien da(r)+Präposition',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Denkst du oft an deine Zukunft? — Ja, ich denke sehr oft ___ .',
    options: ['daran', 'darüber', 'davon', 'darauf'],
    correctAnswer: 'daran',
    explanation: '"denken an" wird bei Sachen durch das Pronominaladverb "daran" (da + r + an) ersetzt.',
    tags: ['Pronominaladverbien', 'daran'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0025',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Fragewörter worüber / worauf',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ ärgerst du dich denn schon den ganzen Morgen so sehr?',
    options: ['Worüber', 'Woran', 'Worauf', 'Womit'],
    correctAnswer: 'Worüber',
    explanation: '"sich ärgern über" bildet die Frage nach einer Sache mit "Worüber?".',
    tags: ['Fragewörter', 'Pronominaladverbien'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0026',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Meinungsäußerung & Argumentation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Meiner ___ nach sollten erneuerbare Energien viel stärker gefördert werden.',
    options: ['Meinung', 'Ansicht', 'Gedanke', 'Überlegung'],
    correctAnswer: 'Meinung',
    explanation: 'Die feste idiomatische Wendung lautet: "Meiner Meinung nach...".',
    tags: ['Meinung', 'Diskussion', 'Umwelt'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0027',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Zustimmung ausdrücken',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Da haben Sie vollkommen recht! Ich bin ganz ___ Meinung.',
    options: ['Ihrer', 'Ihre', 'Ihren', 'Ihrem'],
    correctAnswer: 'Ihrer',
    explanation: '"Ich bin Ihrer Meinung" steht im Genitiv ("einer Meinung sein").',
    tags: ['Meinung', 'Zustimmung', 'Genitiv'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0028',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Widerspruch & Höflichkeit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich verstehe Ihren Standpunkt, aber ich sehe das etwas ___ .',
    options: ['anders', 'falsch', 'schlecht', 'gegeneinander'],
    correctAnswer: 'anders',
    explanation: '"etwas anders sehen" ist eine diplomatische und höfliche Formulierung von Widerspruch.',
    tags: ['Diskussion', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0029',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Beschwerdebrief',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Hiermit möchte ich mich über den mangelhaften Service in Ihrem Hotel ___ .',
    options: ['beschweren', 'bedanken', 'entschuldigen', 'freuen'],
    correctAnswer: 'beschweren',
    explanation: '"sich beschweren über" ist die standardmäßige Formulierung in einer Reklamation oder einem Beschwerdebrief.',
    tags: ['Schreiben', 'Beschwerde', 'Hotel'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0030',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Medizin & Prävention',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Um das Immunsystem zu stärken, sollte man sich ausgewogen ___ .',
    options: ['ernähren', 'füttern', 'essen', 'schlucken'],
    correctAnswer: 'ernähren',
    explanation: '"sich ausgewogen ernähren" bedeutet, gesund und vielseitig zu essen.',
    tags: ['Gesundheit', 'Ernährung'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0031',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Umweltschutz & Ressourcen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Es ist wichtig, im Alltag Plastikmüll zu ___ , um die Meere zu schützen.',
    options: ['vermeiden', 'vermehren', 'zerstören', 'kaufen'],
    correctAnswer: 'vermeiden',
    explanation: '"vermeiden" bedeutet dafür zu sorgen, dass etwas Unerwünschtes gar nicht erst entsteht.',
    tags: ['Umwelt', 'Nachhaltigkeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0032',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Arbeitswelt & Homeoffice',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Immer mehr Angestellte arbeiten flexibel von zu Hause aus im sogenannten ___ .',
    options: ['Homeoffice', 'Hausarbeit', 'Wohnbüro', 'Fernsehen'],
    correctAnswer: 'Homeoffice',
    explanation: 'Der Begriff "Homeoffice" bzw. "mobiles Arbeiten" bezeichnet die Arbeit in den eigenen vier Wänden.',
    tags: ['Arbeit', 'Modernes Leben'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0033',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben mit Dativ und Akkusativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Professor empfiehlt ___ (wir) dieses lehrreiche Buch.',
    options: ['uns', 'wir', 'unser', 'euch'],
    correctAnswer: 'uns',
    explanation: '"empfehlen" verlangt die Person im Dativ: wir -> uns.',
    tags: ['Pronomen', 'Dativ', 'Verben'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0034',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Präpositionen mit Genitiv',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: '___ des starken Sturms fiel der gesamte Zugverkehr für mehrere Stunden aus.',
    options: ['Wegen', 'Trotz', 'Statt', 'Während'],
    correctAnswer: 'Wegen',
    explanation: '"Wegen" verlangt im Standarddeutsch den Genitiv ("wegen des starken Sturms") und gibt die Ursache an.',
    tags: ['Präpositionen', 'Genitiv', 'Kausal'],
    timeLimit: 15,
  },
  {
    id: 'B1-SA-0035',
    level: 'B1',
    gameType: 'SCHNELLANTWORT',
    category: 'Zukunft & Prognosen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Experten vermuten, dass die Temperaturen in den kommenden Jahrzehnten weiter steigen ___ .',
    options: ['werden', 'worden', 'würden', 'waren'],
    correctAnswer: 'werden',
    explanation: 'Zukunftsprognosen werden im Nebensatz mit "werden" am Satzende gebildet.',
    tags: ['Futur', 'Klima', 'Wissenschaft'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 B1: SATZ-RENNEN (15 Questions: 5 EASY, 7 MEDIUM, 3 HARD)
  // =========================================================================
  {
    id: 'B1-SR-0001',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Passiv Satzbau',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz im Passiv Präsens:',
    words: ['Das neue Firmengebäude', 'wird', 'von renommierten Architekten', 'entworfen.'],
    correctOrder: ['Das neue Firmengebäude', 'wird', 'von renommierten Architekten', 'entworfen.'],
    correctAnswer: ['Das neue Firmengebäude', 'wird', 'von renommierten Architekten', 'entworfen.'],
    explanation: 'Subjekt (Das neue Gebäude) -> Hilfsverb (wird) -> Urheberangabe (von...) -> Partizip II (entworfen).',
    tags: ['Passiv', 'Präsens', 'Satzbau'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0002',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Relativsatz mit Präposition',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde das Satzgefüge mit Relativsatz:',
    words: ['Das ist das Projekt,', 'an dem', 'wir seit drei Monaten', 'intensiv arbeiten.'],
    correctOrder: ['Das ist das Projekt,', 'an dem', 'wir seit drei Monaten', 'intensiv arbeiten.'],
    correctAnswer: ['Das ist das Projekt,', 'an dem', 'wir seit drei Monaten', 'intensiv arbeiten.'],
    explanation: 'Präposition + Relativpronomen im Dativ ("an dem") leiten den Relativsatz ein, finite Verbform am Ende.',
    tags: ['Relativsätze', 'Präpositionen'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0003',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Doppelkonnektor zwar... aber',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit der Konjunktion "zwar ... aber":',
    words: ['Die Wohnung ist zwar klein,', 'aber', 'sie', 'liegt', 'sehr zentral.'],
    correctOrder: ['Die Wohnung ist zwar klein,', 'aber', 'sie', 'liegt', 'sehr zentral.'],
    correctAnswer: ['Die Wohnung ist zwar klein,', 'aber', 'sie', 'liegt', 'sehr zentral.'],
    explanation: '"zwar ... aber" schränkt eine Aussage ein; nach "aber" folgt normale Hauptsatzstellung.',
    tags: ['Doppelkonnektoren', 'Wohnen'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0004',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Konjunktiv II irrealer Konditionalsatz',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den irrealen Bedingungssatz der Gegenwart:',
    words: ['Wenn ich mehr Zeit hätte,', 'würde', 'ich', 'ein Buch', 'schreiben.'],
    correctOrder: ['Wenn ich mehr Zeit hätte,', 'würde', 'ich', 'ein Buch', 'schreiben.'],
    correctAnswer: ['Wenn ich mehr Zeit hätte,', 'würde', 'ich', 'ein Buch', 'schreiben.'],
    explanation: 'Bedingungssatz mit "hätte" -> Hauptsatz mit "würde" + Infinitiv am Ende.',
    tags: ['Konjunktiv II', 'Konditionalsatz'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0005',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Temporalsatz während',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit "während" in die richtige Form:',
    words: ['Während die Kollegen diskutierten,', 'notierte', 'sie', 'die wichtigsten Punkte.'],
    correctOrder: ['Während die Kollegen diskutierten,', 'notierte', 'sie', 'die wichtigsten Punkte.'],
    correctAnswer: ['Während die Kollegen diskutierten,', 'notierte', 'sie', 'die wichtigsten Punkte.'],
    explanation: 'Nach dem temporale Nebensatz folgt das finite Verb "notierte" auf Position 1 des Hauptsatzes.',
    tags: ['Temporalsätze', 'während', 'Präteritum'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0006',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Plusquamperfekt Satzgefüge',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Vorzeitigkeit:',
    words: ['Nachdem er den Vertrag unterschrieben hatte,', 'feierte', 'er', 'mit seiner Familie.'],
    correctOrder: ['Nachdem er den Vertrag unterschrieben hatte,', 'feierte', 'er', 'mit seiner Familie.'],
    correctAnswer: ['Nachdem er den Vertrag unterschrieben hatte,', 'feierte', 'er', 'mit seiner Familie.'],
    explanation: 'Nebensatz im Plusquamperfekt ("unterschrieben hatte") drückt die Vorzeitigkeit zum Präteritum ("feierte") aus.',
    tags: ['Plusquamperfekt', 'nachdem', 'Vorzeitigkeit'],
    timeLimit: 30,
  },
  {
    id: 'B1-SR-0007',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Finalsatz um... zu',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die finale Infinitivkonstruktion:',
    words: ['Sie spart jeden Monat Geld,', 'um', 'sich ein neues Auto', 'zu kaufen.'],
    correctOrder: ['Sie spart jeden Monat Geld,', 'um', 'sich ein neues Auto', 'zu kaufen.'],
    correctAnswer: ['Sie spart jeden Monat Geld,', 'um', 'sich ein neues Auto', 'zu kaufen.'],
    explanation: '"um" leitet die finale Zielhandlung ein, "zu kaufen" schließt am Ende ab.',
    tags: ['Finalsätze', 'Infinitiv mit zu'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0008',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Konzessivsatz mit obwohl',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde das Satzgefüge mit "obwohl":',
    words: ['Obwohl der Zug Verspätung hatte,', 'kamen', 'alle Teilnehmer', 'rechtzeitig an.'],
    correctOrder: ['Obwohl der Zug Verspätung hatte,', 'kamen', 'alle Teilnehmer', 'rechtzeitig an.'],
    correctAnswer: ['Obwohl der Zug Verspätung hatte,', 'kamen', 'alle Teilnehmer', 'rechtzeitig an.'],
    explanation: 'Nach vorangestelltem obwohl-Nebensatz folgt direkt das finite Verb "kamen" im Hauptsatz.',
    tags: ['Konzessivsatz', 'obwohl', 'Inversion'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0009',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Konnektor folglich / infolgedessen',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Konsekutivadverb:',
    words: ['Es gab einen technischen Defekt,', 'deshalb', 'wurde', 'die Konferenz', 'verschoben.'],
    correctOrder: ['Es gab einen technischen Defekt,', 'deshalb', 'wurde', 'die Konferenz', 'verschoben.'],
    correctAnswer: ['Es gab einen technischen Defekt,', 'deshalb', 'wurde', 'die Konferenz', 'verschoben.'],
    explanation: '"deshalb" besetzt Position 1, danach folgt das finite Passivverb "wurde".',
    tags: ['Konnektoren', 'Passiv'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0010',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Doppelkonnektor nicht nur... sondern auch',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den mehrteiligen Konnektorensatz:',
    words: ['Er spricht nicht nur fließend Deutsch,', 'sondern', 'auch', 'ausgezeichnetes Französisch.'],
    correctOrder: ['Er spricht nicht nur fließend Deutsch,', 'sondern', 'auch', 'ausgezeichnetes Französisch.'],
    correctAnswer: ['Er spricht nicht nur fließend Deutsch,', 'sondern', 'auch', 'ausgezeichnetes Französisch.'],
    explanation: '"nicht nur ..., sondern auch ..." verbindet zwei hervorgehobene Elemente.',
    tags: ['Doppelkonnektoren', 'Sprachen'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0011',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Indirekte Rede im Konjunktiv I/II',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die höfliche Aussage:',
    words: ['Der Sprecher betonte,', 'dass', 'alle Maßnahmen', 'erfolgreich umgesetzt', 'wurden.'],
    correctOrder: ['Der Sprecher betonte,', 'dass', 'alle Maßnahmen', 'erfolgreich umgesetzt', 'wurden.'],
    correctAnswer: ['Der Sprecher betonte,', 'dass', 'alle Maßnahmen', 'erfolgreich umgesetzt', 'wurden.'],
    explanation: 'Im dass-Satz mit Passiv Präteritum steht das Hilfsverb "wurden" ganz am Ende.',
    tags: ['Nebensätze', 'Passiv', 'Bericht'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0012',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Meinung einleiten',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die strukturierte Meinungsäußerung:',
    words: ['Meiner Ansicht nach', 'sollte', 'der öffentliche Nahverkehr', 'günstiger sein.'],
    correctOrder: ['Meiner Ansicht nach', 'sollte', 'der öffentliche Nahverkehr', 'günstiger sein.'],
    correctAnswer: ['Meiner Ansicht nach', 'sollte', 'der öffentliche Nahverkehr', 'günstiger sein.'],
    explanation: '"Meiner Ansicht nach" bildet das Vorfeld, gefolgt vom Modalverb "sollte".',
    tags: ['Meinung', 'Diskussion'],
    timeLimit: 20,
  },
  {
    id: 'B1-SR-0013',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Verben mit fester Präposition',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Pronominaladverb:',
    words: ['Wir', 'beschäftigen', 'uns', 'seit Wochen mit diesem schwierigen Thema.'],
    correctOrder: ['Wir', 'beschäftigen', 'uns', 'seit Wochen mit diesem schwierigen Thema.'],
    correctAnswer: ['Wir', 'beschäftigen', 'uns', 'seit Wochen mit diesem schwierigen Thema.'],
    explanation: 'Subjekt (Wir) -> Verb (beschäftigen) -> Reflexivpronomen (uns) -> Zeitangabe -> Präpositionalobjekt (mit...).',
    tags: ['Präpositionen', 'Reflexiv'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0014',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Temporalsatz seitdem',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Nebensatz mit "seitdem":',
    words: ['Seitdem er in Deutschland lebt,', 'hat', 'er', 'viele neue Freunde', 'gefunden.'],
    correctOrder: ['Seitdem er in Deutschland lebt,', 'hat', 'er', 'viele neue Freunde', 'gefunden.'],
    correctAnswer: ['Seitdem er in Deutschland lebt,', 'hat', 'er', 'viele neue Freunde', 'gefunden.'],
    explanation: '"Seitdem" leitet den Nebensatz ein (Verb "lebt" am Ende); Hauptsatz beginnt mit finitem Verb "hat".',
    tags: ['Temporalsätze', 'seitdem', 'Perfekt'],
    timeLimit: 25,
  },
  {
    id: 'B1-SR-0015',
    level: 'B1',
    gameType: 'SATZ_RENNEN',
    category: 'Adjektivdeklination mit Komparativ',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit dekliniertem Komparativ:',
    words: ['Wir suchen', 'nach einer', 'besseren Lösung', 'für dieses Problem.'],
    correctOrder: ['Wir suchen', 'nach einer', 'besseren Lösung', 'für dieses Problem.'],
    correctAnswer: ['Wir suchen', 'nach einer', 'besseren Lösung', 'für dieses Problem.'],
    explanation: '"nach einer besseren Lösung" (Dativ feminin mit unbestimmtem Artikel: -en Endung).',
    tags: ['Adjektivdeklination', 'Komparativ'],
    timeLimit: 20,
  },

  // =========================================================================
  // 🧠 B1: WORTSCHATZ-DUELL (20 Questions: 6 EASY, 10 MEDIUM, 4 HARD)
  // =========================================================================
  {
    id: 'B1-WD-0001',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Umwelt & Ökologie',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Nachhaltigkeit',
    focusWord: 'die Nachhaltigkeit',
    question: 'Was bedeutet "die Nachhaltigkeit"?',
    options: ['Sustainability / Sustainable development', 'Pollution (die Verschmutzung)', 'Energy consumption', 'Extinction'],
    correctAnswer: 'Sustainability / Sustainable development',
    explanation: 'Nachhaltigkeit bedeutet, Ressourcen so zu nutzen, dass sie auch künftigen Generationen erhalten bleiben.',
    tags: ['Umwelt', 'Gesellschaft'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0002',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wirtschaft & Finanzen',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Verhandlung',
    focusWord: 'die Verhandlung',
    question: 'Was bedeutet "die Verhandlung"?',
    options: ['Negotiation / Bargaining', 'Presentation', 'Dismissal / Layoff', 'Application'],
    correctAnswer: 'Negotiation / Bargaining',
    explanation: 'In Verhandlungen sprechen zwei Parteien, um einen gemeinsamen Kompromiss oder Vertrag zu erzielen.',
    tags: ['Arbeit', 'Wirtschaft'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0003',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Technik & Medien',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Datenschutz',
    focusWord: 'der Datenschutz',
    question: 'Was ist "der Datenschutz"?',
    options: ['Data privacy / Data protection', 'Data loss (der Datenverlust)', 'Software update', 'Screen brightness'],
    correctAnswer: 'Data privacy / Data protection',
    explanation: 'Datenschutz schützt persönliche Nutzerdaten vor Missbrauch und unbefugtem Zugriff.',
    tags: ['Technik', 'Recht'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0004',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeitswelt',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Überstunden',
    focusWord: 'die Überstunden',
    question: 'Was sind "die Überstunden"?',
    options: ['Overtime / Hours worked beyond regular schedule', 'Holidays (der Urlaub)', 'Break times (die Pausen)', 'Sick days'],
    correctAnswer: 'Overtime / Hours worked beyond regular schedule',
    explanation: 'Überstunden sind Arbeitszeiten, die über die vertraglich vereinbarte Arbeitszeit hinausgehen.',
    tags: ['Arbeit', 'Recht'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0005',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesellschaft & Zusammenleben',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Chancengleichheit',
    focusWord: 'die Chancengleichheit',
    question: 'Was bedeutet "die Chancengleichheit"?',
    options: ['Equal opportunities / Equal chances for all', 'Competition (der Wettbewerb)', 'Social division', 'Privilege'],
    correctAnswer: 'Equal opportunities / Equal chances for all',
    explanation: 'Chancengleichheit bezeichnet das Recht aller Menschen auf gleiche Bildungs- und Entwicklungsmöglichkeiten.',
    tags: ['Gesellschaft', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0006',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wissenschaft & Forschung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Experiment',
    focusWord: 'das Experiment',
    question: 'Welches Verb passt fest zu "ein Experiment" (Nomen-Verb-Verbindung)?',
    options: ['durchführen (to conduct an experiment)', 'kochen', 'bauen', 'schlafen'],
    correctAnswer: 'durchführen (to conduct an experiment)',
    explanation: 'Die feste Verbindung heißt "ein Experiment durchführen" (ein Experiment machen/testen).',
    tags: ['Wissenschaft', 'Kollokation'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0007',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Psychologie & Gefühle',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Enttäuschung',
    focusWord: 'die Enttäuschung',
    question: 'Was bedeutet "die Enttäuschung"?',
    options: ['Disappointment / Letdown', 'Enthusiasm (die Begeisterung)', 'Relief (die Erleichterung)', 'Curiosity (die Neugier)'],
    correctAnswer: 'Disappointment / Letdown',
    explanation: 'Eine Enttäuschung empfindet man, wenn eine positive Erwartung nicht erfüllt wird.',
    tags: ['Gefühle', 'Psychologie'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0008',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Recht & Vertrag',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Frist',
    focusWord: 'die Frist',
    question: 'Was bedeutet "die Frist" bei einer behördlichen oder vertraglichen Aufgabe?',
    options: ['Deadline / Fixed time limit', 'Delay (die Verspätung)', 'Fine (die Strafe)', 'Permission (die Erlaubnis)'],
    correctAnswer: 'Deadline / Fixed time limit',
    explanation: 'Eine Frist ist ein festgelegter Zeitraum, bis zu dessen Ende eine Handlung erledigt sein muss.',
    tags: ['Recht', 'Verwaltung'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0009',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Medien & Information',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Quelle',
    focusWord: 'die Quelle',
    question: 'Was bedeutet "die Quelle" bei einem wissenschaftlichen Text oder Zeitungsbericht?',
    options: ['Source / Origin of information', 'Author\'s signature', 'Summary', 'Title page'],
    correctAnswer: 'Source / Origin of information',
    explanation: 'Die Quelle ist der Ursprung, aus dem Daten oder Zitate entnommen wurden.',
    tags: ['Medien', 'Wissenschaft'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0010',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gesundheit & Ernährung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Unverträglichkeit',
    focusWord: 'die Unverträglichkeit',
    question: 'Was bedeutet "die Nahrungsmittelunverträglichkeit / Laktoseintoleranz"?',
    options: ['Food intolerance / Inability to digest certain foods', 'Hunger strike', 'Special appetite', 'Cooking method'],
    correctAnswer: 'Food intolerance / Inability to digest certain foods',
    explanation: 'Eine Unverträglichkeit (Intoleranz) führt zu Beschwerden nach dem Verzehr bestimmter Stoffe.',
    tags: ['Gesundheit', 'Ernährung'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0011',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Charakter & Persönlichkeit',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'zielstrebig',
    focusWord: 'zielstrebig',
    question: 'Wie verhält sich eine Person, die "zielstrebig" ist?',
    options: ['Goal-oriented / Determined to achieve objectives', 'Easily distracted', 'Lazy and indifferent', 'Shy and quiet'],
    correctAnswer: 'Goal-oriented / Determined to achieve objectives',
    explanation: 'Zielstrebige Menschen verfolgen ihre Pläne mit großem Einsatz und klarer Ausrichtung.',
    tags: ['Persönlichkeit', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0012',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Bildung & Studium',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Vorlesung',
    focusWord: 'die Vorlesung',
    question: 'Was ist "die Vorlesung" an einer Hochschule oder Universität?',
    options: ['University lecture given by a professor', 'Written exam (die Klausur)', 'Student dormitory', 'Cafeteria (die Mensa)'],
    correctAnswer: 'University lecture given by a professor',
    explanation: 'Eine Vorlesung ist eine akademische Lehrveranstaltung im Hörsaal.',
    tags: ['Bildung', 'Universität'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0013',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Reise & Storno',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Stornierung / stornieren',
    focusWord: 'stornieren',
    question: 'Was bedeutet es, ein Hotelzimmer oder ein Ticket zu "stornieren"?',
    options: ['To cancel a booking', 'To confirm a reservation', 'To pay in advance', 'To rebook to next year'],
    correctAnswer: 'To cancel a booking',
    explanation: 'Stornieren bedeutet, eine gebuchte Reise oder Dienstleistung vor Beginn abzusagen.',
    tags: ['Reisen', 'Dienstleistung'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0014',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Verkehr & Mobilität',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Tempolimit',
    focusWord: 'das Tempolimit',
    question: 'Was bedeutet "das Tempolimit / die Geschwindigkeitsbegrenzung"?',
    options: ['Speed limit on roads', 'Toll fee on highways', 'Fuel consumption', 'Car insurance'],
    correctAnswer: 'Speed limit on roads',
    explanation: 'Ein Tempolimit schreibt die gesetzlich maximal zulässige Fahrgeschwindigkeit vor.',
    tags: ['Verkehr', 'Regeln'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0015',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Politik & Wahlen',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Abstimmung / wählen',
    focusWord: 'die Abstimmung',
    question: 'Was bedeutet "die Abstimmung / das Referendum"?',
    options: ['Voting / Ballot / Referendum', 'Demonstration (der Protest)', 'Government formation', 'Press conference'],
    correctAnswer: 'Voting / Ballot / Referendum',
    explanation: 'Bei einer Abstimmung entscheiden Bürger oder Parlamentsmitglieder über Gesetze oder Kandidaten.',
    tags: ['Politik', 'Demokratie'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0016',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gegenteile Adjektive',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'kompliziert',
    focusWord: 'kompliziert',
    question: 'Was ist das genaue Gegenteil von "kompliziert"?',
    options: ['einfach / unkompliziert', 'schwierig', 'anstrengend', 'unmöglich'],
    correctAnswer: 'einfach / unkompliziert',
    explanation: 'Das Gegenteil von kompliziert ist einfach oder simpel.',
    tags: ['Adjektive', 'Antonyme'],
    timeLimit: 12,
  },
  {
    id: 'B1-WD-0017',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Konsum & Finanzen',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Quittung',
    focusWord: 'die Quittung',
    question: 'Was ist "die Quittung / der Beleg"?',
    options: ['Written receipt confirming payment', 'Bank loan (der Kredit)', 'Credit card PIN', 'Price tag (das Preisschild)'],
    correctAnswer: 'Written receipt confirming payment',
    explanation: 'Die Quittung belegt schriftlich den Empfang einer Zahlung.',
    tags: ['Finanzen', 'Einkaufen'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0018',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Arbeit & Qualifikation',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Weiterbildung',
    focusWord: 'die Weiterbildung',
    question: 'Was versteht man unter "beruflicher Weiterbildung"?',
    options: ['Further training / Continuing professional education', 'Early retirement', 'Job dismissal', 'Salary cut'],
    correctAnswer: 'Further training / Continuing professional education',
    explanation: 'Weiterbildung vertieft und erweitert berufliche Kenntnisse durch Seminare und Kurse.',
    tags: ['Arbeit', 'Bildung'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0019',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kultur & Kunst',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Ausstellung',
    focusWord: 'die Ausstellung',
    question: 'Was ist "die Ausstellung" in einem Museum oder einer Galerie?',
    options: ['Art exhibition / Display', 'Theater play (das Theaterstück)', 'Cinema movie', 'Book sale'],
    correctAnswer: 'Art exhibition / Display',
    explanation: 'In einer Ausstellung werden Gemälde, Skulpturen oder historische Exponate öffentlich gezeigt.',
    tags: ['Kultur', 'Kunst'],
    timeLimit: 15,
  },
  {
    id: 'B1-WD-0020',
    level: 'B1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Medien & Kommunikation',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Schlagzeile',
    focusWord: 'die Schlagzeile',
    question: 'Was ist "die Schlagzeile" in der Zeitung?',
    options: ['Headline printed in large letters on front page', 'Comment section', 'Weather forecast', 'Obituary notice'],
    correctAnswer: 'Headline printed in large letters on front page',
    explanation: 'Die Schlagzeile ist die große, aufmerksamkeitsstarke Überschrift auf der Titelseite.',
    tags: ['Medien', 'Journalismus'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ B1: WAS BIN ICH? (15 Questions: 5 EASY, 8 MEDIUM, 2 HARD)
  // =========================================================================
  {
    id: 'B1-WB-0001',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Umwelt & Energie',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Anlage zur Energiegewinnung:',
    clues: [
      'Hinweis 1: Ich habe riesige weiße Rotorblätter, die sich im Wind drehen.',
      'Hinweis 2: Man sieht mich oft in großen Windparks auf Feldern oder im Meer (Offshore).',
      'Hinweis 3: Ich erzeuge sauberen, emissionsfreien Strom aus erneuerbarer Windenergie.',
    ],
    options: ['Das Windrad / Die Windkraftanlage', 'Das Atomkraftwerk', 'Das Kohlekraftwerk', 'Der Staudamm'],
    correctAnswer: 'Das Windrad / Die Windkraftanlage',
    explanation: 'Windkraftanlagen wandeln die kinetische Energie des Windes in Strom um.',
    tags: ['Umwelt', 'Technologie', 'Energie'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0002',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Berufe & Psychologie',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Beruf:',
    clues: [
      'Hinweis 1: Menschen kommen zu mir, wenn sie seelische Probleme, Ängste oder Stress im Alltag haben.',
      'Hinweis 2: Ich verschreibe normalerweise keine Medikamente, sondern führe therapeutische Gespräche.',
      'Hinweis 3: Ich helfe Klienten dabei, ihr Verhalten und ihre Gedankenmuster positiv zu verändern.',
    ],
    options: ['Der Psychologe / Psychotherapeut', 'Der Chirurg', 'Der Anwalt', 'Der Notar'],
    correctAnswer: 'Der Psychologe / Psychotherapeut',
    explanation: 'Der Psychologe/Psychotherapeut behandelt psychische Beschwerden im vertraulichen Gespräch.',
    tags: ['Berufe', 'Gesundheit'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0003',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Wirtschaft & Finanzen',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten wirtschaftlichen Prozess:',
    clues: [
      'Hinweis 1: Ich sorge dafür, dass Waren und Dienstleistungen im Laufe der Zeit immer teurer werden.',
      'Hinweis 2: Die Kaufkraft des Geldes nimmt durch mich kontinuierlich ab.',
      'Hinweis 3: Die Europäische Zentralbank (EZB) versucht, meine Rate bei etwa 2 Prozent stabil zu halten.',
    ],
    options: ['Die Inflation', 'Die Deflation', 'Die Rezession', 'Die Subvention'],
    correctAnswer: 'Die Inflation',
    explanation: 'Inflation bezeichnet die allgemeine Erhöhung des Preisniveaus und Geldentwertung.',
    tags: ['Wirtschaft', 'Finanzen'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0004',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Technik & Software',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Computerprogramm:',
    clues: [
      'Hinweis 1: Mit mir öffnet man Webseiten wie Google, Wikipedia oder Farh SprachArena.',
      'Hinweis 2: Bekannte Beispiele für mich heißen Chrome, Firefox, Safari oder Edge.',
      'Hinweis 3: Man tippt eine URL in meine Adressleiste ein, um im Internet zu surfen.',
    ],
    options: ['Der Webbrowser', 'Das Antivirenprogramm', 'Die Tabellenkalkulation', 'Das Betriebssystem'],
    correctAnswer: 'Der Webbrowser',
    explanation: 'Ein Webbrowser stellt Websites und Inhalte des Internets dar.',
    tags: ['Technik', 'Internet'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0005',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Arbeitswelt & Interessenvertretung',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Arbeitnehmerorganisation:',
    clues: [
      'Hinweis 1: Ich vertrete die Rechte und Interessen von Beschäftigten gegenüber Arbeitgebern.',
      'Hinweis 2: Ich verhandle Tarifverträge über höhere Gehälter und bessere Arbeitsbedingungen.',
      'Hinweis 3: Wenn Verhandlungen scheitern, kann ich zum legalen Arbeitsstreik aufrufen.',
    ],
    options: ['Die Gewerkschaft', 'Die Handelskammer', 'Das Finanzamt', 'Der Aufsichtsrat'],
    correctAnswer: 'Die Gewerkschaft',
    explanation: 'Gewerkschaften organisieren Arbeitnehmer und verhandeln Tarifverträge.',
    tags: ['Arbeit', 'Gesellschaft'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0006',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Medizin & Prävention',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte medizinische Schutzmaßnahme:',
    clues: [
      'Hinweis 1: Der Arzt injiziert mit einer feinen Spritze einen Wirkstoff in den Oberarm.',
      'Hinweis 2: Dadurch bildet der menschliche Körper Antikörper gegen gefährliche Viren oder Bakterien.',
      'Hinweis 3: Der Eintrag wird im gelben internationalen Impfpass dokumentiert.',
    ],
    options: ['Die Schutzimpfung', 'Die Bluttransfusion', 'Die Röntgenaufnahme', 'Die Operation'],
    correctAnswer: 'Die Schutzimpfung',
    explanation: 'Eine Impfung schützt vor Infektionskrankheiten durch gezielte Immunisierung.',
    tags: ['Gesundheit', 'Medizin'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0007',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Klima & Umweltphänomen',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte globale Phänomen:',
    clues: [
      'Hinweis 1: Treibhausgase wie CO2 in der Atmosphäre verstärken mich erheblich.',
      'Hinweis 2: Die weltweiten Durchschnittstemperaturen steigen, und Gletscher schmelzen ab.',
      'Hinweis 3: Extreme Wetterereignisse wie Hitzewellen, Dürren und Überschwemmungen nehmen durch mich zu.',
    ],
    options: ['Der Klimawandel / Die Erderwärmung', 'Die Eiszeit', 'Das Ozonloch', 'Der Vulkanausbruch'],
    correctAnswer: 'Der Klimawandel / Die Erderwärmung',
    explanation: 'Der Klimawandel bezeichnet die menschengemachte langfristige Erwärmung der Erde.',
    tags: ['Umwelt', 'Klima'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0008',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Wohnen & Genossenschaft',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Form des Zusammenlebens:',
    clues: [
      'Hinweis 1: Besonders Studierende und junge Berufstätige gründen mich gern.',
      'Hinweis 2: Jeder Bewohner hat sein eigenes Schlafzimmer, aber Küche und Bad werden geteilt.',
      'Hinweis 3: Man teilt sich die Miete, putzt nach Plan und kocht oft zusammen.',
    ],
    options: ['Die Wohngemeinschaft (WG)', 'Das Einfamilienhaus', 'Das Altersheim', 'Das Hotel'],
    correctAnswer: 'Die Wohngemeinschaft (WG)',
    explanation: 'In einer WG teilen sich mehrere Personen gemeinsam eine Wohnung.',
    tags: ['Wohnen', 'Kultur'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0009',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Finanzen & Absicherung',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Vertrag zur Risikovorsorge:',
    clues: [
      'Hinweis 1: Man zahlt monatlich oder jährlich einen festen Beitrag an ein Unternehmen.',
      'Hinweis 2: Wenn ein Unfall passiert oder ein teurer Schaden entsteht, übernimmt sie die Kosten.',
      'Hinweis 3: In Deutschland hat fast jeder Erwachsene eine Privathaftpflicht-...',
    ],
    options: ['Die Versicherung', 'Der Sparvertrag', 'Die Steuererklärung', 'Der Mietvertrag'],
    correctAnswer: 'Die Versicherung',
    explanation: 'Versicherungen schützen vor finanziellen Verlusten im Schadensfall.',
    tags: ['Finanzen', 'Alltag', 'Recht'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0010',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Kultur & Unterhaltung',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte akustische Medienformat:',
    clues: [
      'Hinweis 1: Man kann mich jederzeit auf dem Smartphone oder Computer online streamen und herunterladen.',
      'Hinweis 2: Meistens unterhalten sich zwei oder mehr Moderatoren über ein bestimmtes Thema.',
      'Hinweis 3: Viele Menschen hören mich beim Autofahren, Kochen oder beim Sport über Kopfhörer.',
    ],
    options: ['Der Podcast', 'Das Hörbuch', 'Die Fernsehnachrichten', 'Die Schallplatte'],
    correctAnswer: 'Der Podcast',
    explanation: 'Ein Podcast ist eine abonnierbare Serie von Audiobeiträgen im Internet.',
    tags: ['Medien', 'Technik'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0011',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Berufe & Recht',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten juristischen Beruf:',
    clues: [
      'Hinweis 1: Ich habe Rechtswissenschaften (Jura) studiert.',
      'Hinweis 2: Vor Gericht verteidige ich Mandanten oder setze ihre Rechtsansprüche durch.',
      'Hinweis 3: Ich berate Mandanten bei Verträgen, Streitigkeiten und Klagen.',
    ],
    options: ['Der Rechtsanwalt', 'Der Richter', 'Der Polizist', 'Der Steuerberater'],
    correctAnswer: 'Der Rechtsanwalt',
    explanation: 'Der Rechtsanwalt berät und vertritt Klienten in Rechtsfragen.',
    tags: ['Berufe', 'Recht'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0012',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Staat & Steuern',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte staatliche Institution:',
    clues: [
      'Hinweis 1: Einmal im Jahr reichen Arbeitnehmer ihre Unterlagen bei mir ein.',
      'Hinweis 2: Ich berechne die Einkommensteuer und prüfe Werbungskosten.',
      'Hinweis 3: Bei zu viel gezahlten Steuern überweise ich eine Erstattung zurück auf das Bankkonto.',
    ],
    options: ['Das Finanzamt', 'Das Arbeitsamt', 'Das Einwohnermeldeamt', 'Das Grundbuchamt'],
    correctAnswer: 'Das Finanzamt',
    explanation: 'Das Finanzamt ist für die Festsetzung und Erhebung von Steuern zuständig.',
    tags: ['Verwaltung', 'Finanzen'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0013',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Transport & Logistik',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das moderne Mobilitätskonzept:',
    clues: [
      'Hinweis 1: Man besitzt kein eigenes Fahrzeug, sondern bucht Autos spontan per App.',
      'Hinweis 2: Man zahlt nur für die tatsächlich gefahrenen Minuten oder Kilometer.',
      'Hinweis 3: Es spart Parkplatzsuche und Unterhaltskosten in Großstädten.',
    ],
    options: ['Das Carsharing', 'Das Leasing', 'Die Fahrgemeinschaft', 'Der Autokauf'],
    correctAnswer: 'Das Carsharing',
    explanation: 'Beim Carsharing teilt man sich gemeinschaftlich genutzte Fahrzeuge.',
    tags: ['Mobilität', 'Stadt'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0014',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Ernährung & Lifestyle',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate die gesuchte Ernährungsweise:',
    clues: [
      'Hinweis 1: Anhänger dieser Ernährungsform verzichten komplett auf Fleisch und Fisch.',
      'Hinweis 2: Sie meiden darüber hinaus auch alle tierischen Produkte wie Milch, Käse, Eier und Honig.',
      'Hinweis 3: Sie ernähren sich ausschließlich rein pflanzlich.',
    ],
    options: ['Der Veganismus / Die vegane Ernährung', 'Die vegetarische Ernährung', 'Die Pescetarische Ernährung', 'Die Rohkost'],
    correctAnswer: 'Der Veganismus / Die vegane Ernährung',
    explanation: 'Vegane Ernährung schließt alle Produkte tierischen Ursprungs strikt aus.',
    tags: ['Ernährung', 'Lebensstil'],
    timeLimit: 24,
  },
  {
    id: 'B1-WB-0015',
    level: 'B1',
    gameType: 'WAS_BIN_ICH',
    category: 'Gesellschaft & Alter',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Lebensabschnitt:',
    clues: [
      'Hinweis 1: Man erreicht mich nach vielen Jahrzehnten aktiver Berufstätigkeit (meist ab 65 bis 67 Jahren).',
      'Hinweis 2: Man muss nicht mehr zur Arbeit gehen, sondern bezieht eine monatliche Altersversorgung.',
      'Hinweis 3: Viele Menschen nutzen diese Zeit für Hobbys, Reisen und die Enkelkinder.',
    ],
    options: ['Der Ruhestand / Die Rente', 'Das Sabbatical', 'Die Elternzeit', 'Die Ausbildung'],
    correctAnswer: 'Der Ruhestand / Die Rente',
    explanation: 'Der Ruhestand (Rente / Pension) ist der Lebensabschnitt nach dem Berufsleben.',
    tags: ['Gesellschaft', 'Arbeit'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ B1: TEAM BATTLE (15 Questions: 9 EASY, 5 MEDIUM, 1 HARD)
  // =========================================================================
  {
    id: 'B1-TB-0001',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Diskussion & Argumente',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welcher Ausdruck leitet ein Pro-Argument in einer Debatte am besten ein?',
    options: ['Ein wesentlicher Vorteil besteht darin, dass...', 'Das ist mir völlig egal.', 'Ich habe keine Lust zu diskutieren.', 'Hör auf zu reden!'],
    correctAnswer: 'Ein wesentlicher Vorteil besteht darin, dass...',
    explanation: '"Ein wesentlicher Vorteil besteht darin, dass..." formuliert sachlich und überzeugend ein Argument.',
    tags: ['Diskussion', 'Argumentation'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0002',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Diskussion & Kontra',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie leitet man ein Gegenargument (Kontra) sachlich ein?',
    options: ['Dagegen spricht allerdings, dass...', 'Du hast wie immer keine Ahnung.', 'Das stimmt sowieso nie.', 'Das ist Unsinn.'],
    correctAnswer: 'Dagegen spricht allerdings, dass...',
    explanation: '"Dagegen spricht allerdings, dass..." ist der Standardausdruck für sachlichen Einwand.',
    tags: ['Diskussion', 'Argumentation'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0003',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Kompromiss finden',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Formulierung eignet sich ideal, um einen Kompromiss vorzuschlagen?',
    options: ['Wie wäre es, wenn wir uns in der Mitte treffen und...?', 'Entweder machen wir es so wie ich will, oder gar nicht!', 'Ich gebe niemals nach.', 'Vergiss es einfach.'],
    correctAnswer: 'Wie wäre es, wenn wir uns in der Mitte treffen und...?',
    explanation: '"Wie wäre es, wenn wir uns in der Mitte treffen..." signalisiert Kooperationsbereitschaft.',
    tags: ['Verhandlung', 'Kompromiss'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0004',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Bewerbungsgespräch Stärken',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was antwortet man im Vorstellungsgespräch am professionellsten auf die Frage nach Stärken?',
    options: ['Zu meinen größten Stärken zählen Teamfähigkeit, Zuverlässigkeit und eine schnelle Auffassungsgabe.', 'Ich bin einfach der Beste hier.', 'Ich mache nie Fehler.', 'Ich arbeite nur fürs Geld.'],
    correctAnswer: 'Zu meinen größten Stärken zählen Teamfähigkeit, Zuverlässigkeit und eine schnelle Auffassungsgabe.',
    explanation: 'Sachliche Nennung von Soft Skills und fachlichen Kompetenzen wirkt professionell.',
    tags: ['Bewerbung', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0005',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Landeskunde & Bundesländer',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Aus wie vielen Bundesländern besteht die Bundesrepublik Deutschland?',
    options: ['16 Bundesländer', '10 Bundesländer', '12 Bundesländer', '20 Bundesländer'],
    correctAnswer: '16 Bundesländer',
    explanation: 'Deutschland ist ein Bundesstaat aus genau 16 Bundesländern.',
    tags: ['Landeskunde', 'Politik'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0006',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Klimaschutz im Alltag',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Verhaltensweise spart im Alltag die meiste Heizenergie ein?',
    options: ['Stoßlüften (mehrmals täglich 5 Minuten Fenster ganz auf) statt Dauerkippen', 'Die Fenster den ganzen Tag auf Kipp stehen lassen', 'Die Heizung auf Stufe 5 stellen und Fenster öffnen', 'Gar nicht mehr lüften'],
    correctAnswer: 'Stoßlüften (mehrmals täglich 5 Minuten Fenster ganz auf) statt Dauerkippen',
    explanation: 'Stoßlüften tauscht die Luft schnell aus, ohne dass Wände und Möbel auskühlen.',
    tags: ['Umwelt', 'Energie', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0007',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Vortrag & Präsentation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie beendet man eine mündliche Präsentation vor Publikum professionell?',
    options: ['Ich bedanke mich ganz herzlich für Ihre Aufmerksamkeit und freue mich auf Ihre Fragen.', 'So, ich bin endlich fertig, tschüss.', 'Keine Ahnung, was ich noch sagen soll.', 'Das wars.'],
    correctAnswer: 'Ich bedanke mich ganz herzlich für Ihre Aufmerksamkeit und freue mich auf Ihre Fragen.',
    explanation: 'Der Dank für die Aufmerksamkeit mit anschließender Fragerunde ist der professionelle Abschluss.',
    tags: ['Präsentation', 'Kommunikation'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0008',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Gesundheitswesen Deutschland',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Notrufnummer wählt man in Deutschland bei einem akuten medizinischen Notfall oder Feuer?',
    options: ['112', '110 (nur Polizei)', '911', '116117'],
    correctAnswer: '112',
    explanation: '112 ist der europaweite Notruf für Feuerwehr und Rettungsdienst; 110 ist die Polizei.',
    tags: ['Gesundheit', 'Notfall', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0009',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Kulturelle Feiertage',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was feiern die Menschen in Deutschland am 3. Oktober (Tag der Deutschen Einheit)?',
    options: ['Die Wiedervereinigung von Ost- und Westdeutschland im Jahr 1990', 'Das Ende des Ersten Weltkriegs', 'Den Geburtstag des Bundeskanzlers', 'Die Erfindung des Buchdrucks'],
    correctAnswer: 'Die Wiedervereinigung von Ost- und Westdeutschland im Jahr 1990',
    explanation: 'Der 3. Oktober ist der deutsche Nationalfeiertag zum Gedenken an die Wiedervereinigung 1990.',
    tags: ['Geschichte', 'Landeskunde'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0010',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Dualsystem Ausbildung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was zeichnet das deutsche "Duale Ausbildungssystem" aus?',
    options: ['Die Kombination aus praktischer Arbeit im Betrieb und theoretischem Unterricht in der Berufsschule', 'Dass man zwei Berufe gleichzeitig lernt', 'Dass man zwei Gehälter bekommt', 'Dass man nur online studiert'],
    correctAnswer: 'Die Kombination aus praktischer Arbeit im Betrieb und theoretischem Unterricht in der Berufsschule',
    explanation: 'Das duale System verknüpft betriebliche Praxis mit schulischer Theorie.',
    tags: ['Bildung', 'Arbeit', 'Kultur'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0011',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Medienkompetenz Fake News',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie überprüft man am zuverlässigsten, ob eine reißerische Online-Nachricht der Wahrheit entspricht?',
    options: ['Fakten bei mehreren unabhängigen, seriösen Quellen und Faktencheckern gegenchecken', 'Die Nachricht sofort ungeprüft mit allen Freunden teilen', 'Nur auf die Likes in sozialen Medien schauen', 'Der Überschrift blind vertrauen'],
    correctAnswer: 'Fakten bei mehreren unabhängigen, seriösen Quellen und Faktencheckern gegenchecken',
    explanation: 'Quellenkritik und Gegenchecks bei mehreren etablierten Medien entlarven Falschmeldungen.',
    tags: ['Medien', 'Kritisches Denken'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0012',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Berufliche E-Mail Anrede',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie beginnt man eine formelle E-Mail, wenn der genaue Name des Ansprechpartners nicht bekannt ist?',
    options: ['Sehr geehrte Damen und Herren,', 'Hallo Leute,', 'Liebe Freunde,', 'Hi zusammen,'],
    correctAnswer: 'Sehr geehrte Damen und Herren,',
    explanation: '"Sehr geehrte Damen und Herren," ist die offizielle neutrale Anrede für formelle Anschreiben.',
    tags: ['Schreiben', 'Höflichkeit', 'Arbeit'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0013',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Pfandsystem in Deutschland',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet das deutsche Einwegpfand-Symbol auf Plastikflaschen und Dosen?',
    options: ['Man zahlt 25 Cent Pfand beim Kauf und erhält das Geld am Pfandautomaten bei Rückgabe zurück.', 'Man muss die Flasche in den Restmüll werfen.', 'Die Flasche ist giftig.', 'Das Getränk ist kostenlos.'],
    correctAnswer: 'Man zahlt 25 Cent Pfand beim Kauf und erhält das Geld am Pfandautomaten bei Rückgabe zurück.',
    explanation: 'Das deutsche Pfandsystem fördert Recycling durch finanzielle Rückvergütung (25 Cent Einwegpfand).',
    tags: ['Umwelt', 'Alltag', 'Landeskunde'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0014',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Demokratie & Wahlen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Welches Verfassungsorgan wählt in Deutschland den Bundeskanzler oder die Bundeskanzlerin?',
    options: ['Der Deutsche Bundestag', 'Die Bundesversammlung', 'Der Bundesrat', 'Das Bundesverfassungsgericht'],
    correctAnswer: 'Der Deutsche Bundestag',
    explanation: 'Die Abgeordneten des Deutschen Bundestages wählen den Bundeskanzler mit absoluter Mehrheit.',
    tags: ['Politik', 'Demokratie', 'Landeskunde'],
    timeLimit: 15,
  },
  {
    id: 'B1-TB-0015',
    level: 'B1',
    gameType: 'TEAM_BATTLE',
    category: 'Sprichwörter & Redewendungen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was bedeutet das deutsche Sprichwort: "Übung macht den Meister"?',
    options: ['Wer regelmäßig trainiert und lernt, wird mit der Zeit sehr gut in einer Sache.', 'Nur Lehrer können Deutsch sprechen.', 'Man muss niemals Hausaufgaben machen.', 'Perfektion ist sofort da.'],
    correctAnswer: 'Wer regelmäßig trainiert und lernt, wird mit der Zeit sehr gut in einer Sache.',
    explanation: '"Übung macht den Meister" betont die Bedeutung von kontinuierlichem Lernen und Training.',
    tags: ['Sprichwörter', 'Kultur'],
    timeLimit: 15,
  },
];
