import { BankQuestion } from '../questionTypes.js';

/**
 * A1 Level Question Bank - Farh SprachArena
 * Exactly 100 Questions:
 * - 35 SCHNELLANTWORT (Grammar, Everyday Communication, Dialogues, Basics)
 * - 15 SATZ_RENNEN (Sentence construction & Word order)
 * - 20 WORTSCHATZ_DUELL (Vocabulary & Practical Terminology)
 * - 15 WAS_BIN_ICH (Deductive clues & Context comprehension)
 * - 15 TEAM_BATTLE (Team Challenges, Dialogues & Communication)
 *
 * Difficulty: 30 EASY, 50 MEDIUM, 20 HARD
 */
export const A1_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ A1: SCHNELLANTWORT (35 Questions: 10 EASY, 18 MEDIUM, 7 HARD)
  // =========================================================================
  {
    id: 'A1-SA-0001',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Begrüßung & Höflichkeit',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Guten Morgen! Wie ___ es Ihnen?',
    options: ['geht', 'gehen', 'gehe', 'gehst'],
    correctAnswer: 'geht',
    explanation: 'Die feste Höflichkeitsformel lautet: "Wie geht es Ihnen?" ("geht" ist 3. Person Singular von "es geht").',
    tags: ['Begrüßung', 'Höflichkeit', 'Präsens'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0002',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben & Konjugation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich ___ Deutsch im Unterricht mit Farh.',
    options: ['lerne', 'lernst', 'lernt', 'lernen'],
    correctAnswer: 'lerne',
    explanation: 'Die 1. Person Singular ("ich") der regelmäßigen Verben endet auf -e: "ich lerne".',
    tags: ['Verben', 'Konjugation', 'Präsens'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0003',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Personalpronomen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist mein Bruder. ___ heißt Lukas.',
    options: ['Er', 'Sie', 'Es', 'Du'],
    correctAnswer: 'Er',
    explanation: '"Der Bruder" ist maskulin, daher verwendet man das Personalpronomen "er".',
    tags: ['Pronomen', 'Familie', 'Maskulinum'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0004',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Zahlen & Mathematik',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ist das Ergebnis: zehn plus fünf = ___',
    options: ['fünfzehn', 'fünfzig', 'vierzehn', 'sechzehn'],
    correctAnswer: 'fünfzehn',
    explanation: '10 + 5 = 15 auf Deutsch heißt "fünfzehn".',
    tags: ['Zahlen', 'Grundrechenarten'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0005',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Essen & Trinken',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Zum Frühstück trinke ich immer ___ Kaffee.',
    options: ['einen', 'eine', 'ein', 'einem'],
    correctAnswer: 'einen',
    explanation: '"Kaffee" ist maskulin (der Kaffee) und steht als Akkusativobjekt: "einen Kaffee".',
    tags: ['Akkusativ', 'Essen', 'Artikel'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0006',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wohnen & Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wo ist die Lampe? — Sie steht auf ___ Tisch.',
    options: ['dem', 'den', 'das', 'die'],
    correctAnswer: 'dem',
    explanation: 'Die Frage "Wo?" verlangt bei Wechselpräpositionen den Dativ: "auf dem Tisch" (maskulin: der -> dem).',
    tags: ['Dativ', 'Präpositionen', 'Wohnen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0007',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Uhrzeit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Es ist 14:30 Uhr. Auf Deutsch sagt man im Alltag: Es ist ___ drei.',
    options: ['halb', 'vor', 'nach', 'viertel'],
    correctAnswer: 'halb',
    explanation: '14:30 Uhr bedeutet: eine halbe Stunde bis 15 Uhr, also "halb drei".',
    tags: ['Uhrzeit', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0008',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wetter',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Im Sommer scheint die Sonne und es ist sehr ___ .',
    options: ['warm', 'kalt', 'schneeig', 'frostig'],
    correctAnswer: 'warm',
    explanation: 'Im Sommer ist das Wetter typischerweise warm oder heiß.',
    tags: ['Wetter', 'Jahreszeiten'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0009',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Freizeit & Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Am Samstag ___ meine Freunde und ich Fußball.',
    options: ['spielen', 'spielt', 'spiele', 'spielst'],
    correctAnswer: 'spielen',
    explanation: '"Meine Freunde und ich" entspricht dem Personalpronomen "wir" (1. Person Plural: spielen).',
    tags: ['Verben', 'Plural', 'Sport'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0010',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verkehr & Dativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich fahre jeden Morgen mit ___ Bus zur Sprachschule.',
    options: ['dem', 'den', 'das', 'der'],
    correctAnswer: 'dem',
    explanation: 'Die Präposition "mit" verlangt ausnahmslos den Dativ: "mit dem Bus" (der Bus -> dem Bus).',
    tags: ['Dativ', 'Präpositionen', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0011',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verb haben',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Entschuldigung, ___ du einen Stift für mich?',
    options: ['hast', 'hat', 'haben', 'habe'],
    correctAnswer: 'hast',
    explanation: 'Die 2. Person Singular ("du") vom Verb haben lautet "du hast".',
    tags: ['haben', 'Konjugation', 'Schule'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0012',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verb sein',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Wir ___ heute sehr glücklich.',
    options: ['sind', 'seid', 'ist', 'bin'],
    correctAnswer: 'sind',
    explanation: 'Die 1. Person Plural ("wir") vom unregelmäßigen Verb sein lautet "wir sind".',
    tags: ['sein', 'Verben'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0013',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'W-Fragen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: '___ wohnst du? — In Frankfurt.',
    options: ['Wo', 'Woher', 'Wohin', 'Wer'],
    correctAnswer: 'Wo',
    explanation: 'Nach einem festen Ort fragt man mit dem Fragewort "Wo?". ("Woher" = Herkunft, "Wohin" = Richtung).',
    tags: ['W-Fragen', 'Fragewörter'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0014',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'W-Fragen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: '___ kommst du? — Aus Spanien.',
    options: ['Woher', 'Wohin', 'Wo', 'Was'],
    correctAnswer: 'Woher',
    explanation: 'Nach der Herkunft ("aus...") fragt man immer mit "Woher?".',
    tags: ['W-Fragen', 'Herkunft'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0015',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Negation',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich habe leider ___ Zeit für das Kino.',
    options: ['keine', 'nicht', 'kein', 'keinen'],
    correctAnswer: 'keine',
    explanation: '"Zeit" ist feminin (die Zeit) und ein Nomen ohne bestimmten Artikel; daher wird es mit "keine" negiert.',
    tags: ['Negation', 'kein-nicht', 'Nomen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0016',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Negation',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das Buch ist ___ teuer, es kostet nur fünf Euro.',
    options: ['nicht', 'kein', 'keine', 'keinen'],
    correctAnswer: 'nicht',
    explanation: 'Adjektive wie "teuer" werden im Deutschen immer mit "nicht" verneint.',
    tags: ['Negation', 'Adjektive'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0017',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Possessivartikel',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ist das ___ Tasche, Sarah? — Ja, das ist meine Tasche.',
    options: ['deine', 'dein', 'deinen', 'deinem'],
    correctAnswer: 'deine',
    explanation: '"Tasche" ist feminin (die Tasche). Im Nominativ lautet der Possessivartikel "deine".',
    tags: ['Possessivartikel', 'Femininum'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0018',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Possessivartikel',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Peter sucht ___ Schlüssel. Er kann ihn nicht finden.',
    options: ['seinen', 'seine', 'sein', 'seinem'],
    correctAnswer: 'seinen',
    explanation: '"Schlüssel" ist maskulin (der Schlüssel) und steht im Akkusativ: "seinen Schlüssel".',
    tags: ['Possessivartikel', 'Akkusativ', 'Maskulinum'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0019',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Trennbare Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Deutschkurs ___ um neun Uhr morgens ___ .',
    options: ['fängt ... an', 'steht ... auf', 'kauft ... ein', 'kommt ... mit'],
    correctAnswer: 'fängt ... an',
    explanation: '"anfangen" ist ein trennbares Verb: "Der Kurs fängt ... an".',
    tags: ['Trennbare Verben', 'Präsens'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0020',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Trennbare Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Am Samstag kaufe ich im Supermarkt ___ .',
    options: ['ein', 'auf', 'aus', 'ab'],
    correctAnswer: 'ein',
    explanation: 'Das trennbare Verb heißt "einkaufen" (ich kaufe ... ein).',
    tags: ['Trennbare Verben', 'Einkaufen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0021',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Modalverben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Hier im Krankenhaus ___ man nicht rauchen.',
    options: ['darf', 'muss', 'will', 'kannst'],
    correctAnswer: 'darf',
    explanation: '"nicht dürfen" drückt ein striktes Verbot aus: "Hier darf man nicht rauchen".',
    tags: ['Modalverben', 'Verbot'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0022',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Modalverben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich habe morgen eine Prüfung, ich ___ heute viel lernen.',
    options: ['muss', 'darf', 'mag', 'dürfen'],
    correctAnswer: 'muss',
    explanation: '"müssen" drückt eine Notwendigkeit oder Pflicht aus (ich muss lernen).',
    tags: ['Modalverben', 'Pflicht'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0023',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Unregelmäßige Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Mein Vater ___ jeden Tag die Zeitung.',
    options: ['liest', 'lest', 'lese', 'lesen'],
    correctAnswer: 'liest',
    explanation: 'Das Verb "lesen" hat einen Vokalwechsel in der 2. und 3. Person Singular: er/sie/es liest (e -> ie).',
    tags: ['Vokalwechsel', 'Verben'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0024',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Unregelmäßige Verben',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ___ du heute zu Mittag?',
    options: ['isst', 'esst', 'esse', 'essen'],
    correctAnswer: 'isst',
    explanation: 'Das Verb "essen" wechselt im Präsens für "du": du isst (e -> i).',
    tags: ['Vokalwechsel', 'Essen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0025',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wochentage & Präpositionen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: '___ Montag habe ich keinen Unterricht.',
    options: ['Am', 'Im', 'Um', 'An'],
    correctAnswer: 'Am',
    explanation: 'Bei Wochentagen und Tageszeiten verwendet man die Präposition "am" (an + dem).',
    tags: ['Zeit', 'Präpositionen', 'Wochentage'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0026',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Uhrzeit & Präpositionen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Der Film beginnt genau ___ 20:15 Uhr.',
    options: ['um', 'am', 'im', 'von'],
    correctAnswer: 'um',
    explanation: 'Bei präzisen Uhrzeitangaben steht immer die Präposition "um".',
    tags: ['Uhrzeit', 'Präpositionen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0027',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Monate & Jahreszeiten',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: '___ Juli haben viele Schüler in Deutschland Sommerferien.',
    options: ['Im', 'Am', 'Um', 'Auf'],
    correctAnswer: 'Im',
    explanation: 'Bei Monaten und Jahreszeiten verwendet man die temporale Präposition "im" (in + dem).',
    tags: ['Monate', 'Zeit', 'Präpositionen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0028',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Imperativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Kinder, seid leise und ___ eure Hausaufgaben!',
    options: ['macht', 'machen', 'mache', 'machst'],
    correctAnswer: 'macht',
    explanation: 'Der Imperativ Plural ("ihr") entspricht dem Verbstamm + -t: "macht!".',
    tags: ['Imperativ', 'Aufforderung'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0029',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Imperativ Höflichkeitsform',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Herr Müller, ___ Sie bitte hier Platz!',
    options: ['nehmen', 'nehmt', 'nimm', 'nimmst'],
    correctAnswer: 'nehmen',
    explanation: 'Der Höflichkeits-Imperativ ("Sie") wird mit dem Infinitiv + Sie gebildet: "Nehmen Sie!".',
    tags: ['Imperativ', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0030',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Dativobjekt Verben',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich helfe ___ alten Dame beim Tragen der Taschen.',
    options: ['der', 'die', 'das', 'den'],
    correctAnswer: 'der',
    explanation: 'Das Verb "helfen" verlangt immer den Dativ: "die Dame" (feminin) wird im Dativ zu "der Dame".',
    tags: ['Dativ', 'Verben', 'helfen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0031',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Pluralbildung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Ein Apfel schmeckt gut, aber zwei ___ sind noch besser.',
    options: ['Äpfel', 'Apfeln', 'Äpfele', 'Apfels'],
    correctAnswer: 'Äpfel',
    explanation: 'Der Plural von "der Apfel" ist mit Umlaut "die Äpfel".',
    tags: ['Plural', 'Nomen', 'Essen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0032',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Pluralbildung',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Im Klassenzimmer stehen zwanzig Tische und zwanzig ___ .',
    options: ['Stühle', 'Stuhle', 'Stühlen', 'Stühler'],
    correctAnswer: 'Stühle',
    explanation: 'Der Plural von "der Stuhl" lautet "die Stühle".',
    tags: ['Plural', 'Möbel'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0033',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Alltagskommunikation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Danke schön für Ihre Hilfe! — ___ !',
    options: ['Bitte sehr', 'Guten Tag', 'Auf Wiedersehen', 'Entschuldigung'],
    correctAnswer: 'Bitte sehr',
    explanation: 'Auf "Danke" oder "Danke schön" antwortet man höflich mit "Bitte" oder "Bitte sehr".',
    tags: ['Kommunikation', 'Höflichkeit'],
    timeLimit: 12,
  },
  {
    id: 'A1-SA-0034',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Einkaufen & Preise',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Entschuldigung, was ___ die Tomaten?',
    options: ['kosten', 'kostet', 'koste', 'kostest'],
    correctAnswer: 'kosten',
    explanation: '"Die Tomaten" steht im Plural, daher muss das Verb "kosten" im Plural stehen (3. Person Plural).',
    tags: ['Einkaufen', 'Plural', 'Verben'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0035',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wohnort & Präpositionen',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich wohne ___ Deutschland, aber meine Eltern leben ___ der Schweiz.',
    options: ['in ... in', 'in ... in der', 'nach ... in', 'aus ... bei'],
    correctAnswer: 'in ... in der',
    explanation: 'Länder ohne Artikel nehmen "in Deutschland", aber feminine Länder wie die Schweiz verlangen im Dativ "in der Schweiz".',
    tags: ['Länder', 'Präpositionen', 'Dativ'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 A1: SATZ-RENNEN (15 Questions: 5 EASY, 7 MEDIUM, 3 HARD)
  // =========================================================================
  {
    id: 'A1-SR-0001',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Hauptsatz / Satzbau',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Wörter in die richtige Reihenfolge:',
    words: ['Ich', 'gerne', 'lerne', 'Deutsch.'],
    correctOrder: ['Ich', 'lerne', 'gerne', 'Deutsch.'],
    correctAnswer: ['Ich', 'lerne', 'gerne', 'Deutsch.'],
    explanation: 'Im deutschen Aussagesatz steht das finite Verb immer an Position 2.',
    tags: ['Satzbau', 'Hauptsatz'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0002',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'W-Fragen',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die richtige Frage nach dem Wohnort:',
    words: ['Wo', 'du', 'wohnst', 'in Deutschland', '?'],
    correctOrder: ['Wo', 'wohnst', 'du', 'in Deutschland', '?'],
    correctAnswer: ['Wo', 'wohnst', 'du', 'in Deutschland', '?'],
    explanation: 'In der W-Frage steht das Fragewort an Position 1, danach folgt das konjugierte Verb.',
    tags: ['Fragesatz', 'W-Frage'],
    timeLimit: 20,
  },
  {
    id: 'A1-SR-0003',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Ja/Nein-Fragen',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde eine korrekte Ja/Nein-Frage:',
    words: ['Trinkst', 'einen Kaffee', 'du', 'gerne', '?'],
    correctOrder: ['Trinkst', 'du', 'gerne', 'einen Kaffee', '?'],
    correctAnswer: ['Trinkst', 'du', 'gerne', 'einen Kaffee', '?'],
    explanation: 'In Ja/Nein-Fragen steht das finite Verb an Position 1, gefolgt vom Subjekt.',
    tags: ['Fragesatz', 'Ja/Nein-Frage'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0004',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Modalverben',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit Modalverb in die richtige Reihenfolge:',
    words: ['Wir', 'heute Abend', 'können', 'zusammen kochen.'],
    correctOrder: ['Wir', 'können', 'heute Abend', 'zusammen kochen.'],
    correctAnswer: ['Wir', 'können', 'heute Abend', 'zusammen kochen.'],
    explanation: 'Das konjugierte Modalverb steht an Position 2, der Vollverb-Infinitiv am Satzende (Satzklammer).',
    tags: ['Modalverben', 'Satzklammer'],
    timeLimit: 30,
  },
  {
    id: 'A1-SR-0005',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Inversion / Zeitangabe',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Satzglieder in die korrekte Reihenfolge (Zeit an Pos. 1):',
    words: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    correctOrder: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    correctAnswer: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    explanation: 'Steht die Zeitangabe auf Position 1, steht das Verb auf Position 2 und das Subjekt auf Position 3.',
    tags: ['Inversion', 'Tagesablauf'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0006',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Einkaufen',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde einen höflichen Wunsch beim Einkaufen:',
    words: ['Ich', 'zwei Kilo Äpfel', 'möchte', 'bitte.'],
    correctOrder: ['Ich', 'möchte', 'bitte', 'zwei Kilo Äpfel.'],
    correctAnswer: ['Ich', 'möchte', 'bitte', 'zwei Kilo Äpfel.'],
    explanation: 'Das Verb "möchte" steht auf Position 2.',
    tags: ['Einkaufen', 'Höflichkeit'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0007',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Trennbare Verben',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit dem trennbaren Verb "aufstehen":',
    words: ['Er', 'jeden Tag', 'steht', 'um sechs Uhr', 'auf.'],
    correctOrder: ['Er', 'steht', 'jeden Tag', 'um sechs Uhr', 'auf.'],
    correctAnswer: ['Er', 'steht', 'jeden Tag', 'um sechs Uhr', 'auf.'],
    explanation: 'Der Verbstamm ("steht") steht an Position 2, das trennbare Präfix ("auf") steht ganz am Satzende.',
    tags: ['Trennbare Verben', 'Tagesablauf'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0008',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Trennbare Verben',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit "fernsehen":',
    words: ['Wir', 'am Abend', 'sehen', 'zusammen', 'fern.'],
    correctOrder: ['Wir', 'sehen', 'am Abend', 'zusammen', 'fern.'],
    correctAnswer: ['Wir', 'sehen', 'am Abend', 'zusammen', 'fern.'],
    explanation: '"fernsehen" trennt sich im Hauptsatz: "sehen" auf Pos. 2, "fern" ans Ende.',
    tags: ['Trennbare Verben', 'Freizeit'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0009',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Negation',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde einen verneinten Satz mit "nicht":',
    words: ['Ich', 'heute', 'verstehe', 'die Hausaufgabe', 'nicht.'],
    correctOrder: ['Ich', 'verstehe', 'die Hausaufgabe', 'heute', 'nicht.'],
    correctAnswer: ['Ich', 'verstehe', 'die Hausaufgabe', 'heute', 'nicht.'],
    explanation: 'Das finite Verb steht an Position 2, "nicht" verneint den gesamten Satzinhalt am Ende.',
    tags: ['Negation', 'Satzbau'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0010',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Familie & Vorstellung',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Wörter für eine persönliche Vorstellung in die Reihe:',
    words: ['Mein Name', 'und', 'ist Farh', 'ich bin Lehrer.'],
    correctOrder: ['Mein Name', 'ist Farh', 'und', 'ich bin Lehrer.'],
    correctAnswer: ['Mein Name', 'ist Farh', 'und', 'ich bin Lehrer.'],
    explanation: 'Zwei Hauptsätze werden mit der Konjunktion "und" auf Position 0 verbunden.',
    tags: ['Vorstellung', 'Konnektoren'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0011',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Akkusativobjekt',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde den Satz mit Akkusativobjekt:',
    words: ['Der Schüler', 'einen langen Text', 'schreibt', 'im Heft.'],
    correctOrder: ['Der Schüler', 'schreibt', 'einen langen Text', 'im Heft.'],
    correctAnswer: ['Der Schüler', 'schreibt', 'einen langen Text', 'im Heft.'],
    explanation: 'Subjekt (Der Schüler) -> Verb (schreibt) -> Akkusativobjekt (einen langen Text) -> Ortsangabe.',
    tags: ['Akkusativ', 'Satzbau'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0012',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Dativ mit Präposition',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Ordne die Satzglieder richtig:',
    words: ['Sie', 'mit ihrer Freundin', 'fährt', 'nach Berlin.'],
    correctOrder: ['Sie', 'fährt', 'mit ihrer Freundin', 'nach Berlin.'],
    correctAnswer: ['Sie', 'fährt', 'mit ihrer Freundin', 'nach Berlin.'],
    explanation: 'Verb an Position 2 (fährt), modale Angabe (mit ihrer Freundin), Richtungsangabe (nach Berlin).',
    tags: ['Dativ', 'Präpositionen', 'Reisen'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0013',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Restaurant',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde eine Bestellung im Restaurant:',
    words: ['Wir', 'ein Mineralwasser', 'hätten gerne', 'bitte.'],
    correctOrder: ['Wir', 'hätten gerne', 'ein Mineralwasser', 'bitte.'],
    correctAnswer: ['Wir', 'hätten gerne', 'ein Mineralwasser', 'bitte.'],
    explanation: '"hätten gerne" bildet die höfliche Prädikatsform an Position 2.',
    tags: ['Restaurant', 'Höflichkeit'],
    timeLimit: 20,
  },
  {
    id: 'A1-SR-0014',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Modalverb wollen',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bilde einen Satz mit "wollen":',
    words: ['Meine Schwester', 'im Sommer', 'will', 'Spanisch lernen.'],
    correctOrder: ['Meine Schwester', 'will', 'im Sommer', 'Spanisch lernen.'],
    correctAnswer: ['Meine Schwester', 'will', 'im Sommer', 'Spanisch lernen.'],
    explanation: 'Modalverb "will" steht an Position 2, der Infinitiv "lernen" steht ganz am Satzende.',
    tags: ['Modalverben', 'Satzklammer'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0015',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'W-Fragen mit Präposition',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde eine Frage zur Uhrzeit:',
    words: ['Um wie viel Uhr', 'der Deutschunterricht', 'beginnt', '?'],
    correctOrder: ['Um wie viel Uhr', 'beginnt', 'der Deutschunterricht', '?'],
    correctAnswer: ['Um wie viel Uhr', 'beginnt', 'der Deutschunterricht', '?'],
    explanation: 'Fragewortgruppe ("Um wie viel Uhr") an Position 1, finites Verb ("beginnt") an Position 2, Subjekt danach.',
    tags: ['Fragesatz', 'Uhrzeit'],
    timeLimit: 25,
  },

  // =========================================================================
  // 🧠 A1: WORTSCHATZ-DUELL (20 Questions: 6 EASY, 10 MEDIUM, 4 HARD)
  // =========================================================================
  {
    id: 'A1-WD-0001',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Möbel & Artikel',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Tisch',
    focusWord: 'der Tisch',
    question: 'Welcher Artikel und welche Bedeutung passen zu diesem Wort?',
    options: ['der Tisch (Table)', 'die Tisch (Chair)', 'das Tisch (Bed)', 'die Tische (Cupboard)'],
    correctAnswer: 'der Tisch (Table)',
    explanation: '"Tisch" ist maskulin: der Tisch (Englisch: table).',
    tags: ['Artikel', 'Möbel'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0002',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Obst & Lebensmittel',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Apple',
    focusWord: 'Apple',
    question: 'Wie heißt "Apple" mit dem richtigen Artikel auf Deutsch?',
    options: ['der Apfel', 'die Birne', 'die Banane', 'die Orange'],
    correctAnswer: 'der Apfel',
    explanation: 'Apple heißt auf Deutsch "der Apfel" (maskulin).',
    tags: ['Essen', 'Obst'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0003',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kleidung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Hose',
    focusWord: 'die Hose',
    question: 'Was bedeutet "die Hose"?',
    options: ['Trousers / Pants', 'Shirt / T-Shirt', 'Jacket / Coat', 'Shoes'],
    correctAnswer: 'Trousers / Pants',
    explanation: '"Die Hose" bezeichnet das Kleidungsstück für die Beine (trousers/pants).',
    tags: ['Kleidung', 'Wortschatz'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0004',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Farben',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Red',
    focusWord: 'Red',
    question: 'Wie heißt die Farbe "Red" auf Deutsch?',
    options: ['rot', 'blau', 'gelb', 'grün'],
    correctAnswer: 'rot',
    explanation: 'Red = rot.',
    tags: ['Farben', 'Adjektive'],
    timeLimit: 12,
  },
  {
    id: 'A1-WD-0005',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Körperteile',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Auge',
    focusWord: 'das Auge',
    question: 'Welcher Plural und welche Bedeutung gehören zu "das Auge"?',
    options: ['das Auge (Eye) -> die Augen', 'der Auge (Ear) -> die Augen', 'die Auge (Hand) -> die Augen', 'das Auge (Mouth) -> die Äuger'],
    correctAnswer: 'das Auge (Eye) -> die Augen',
    explanation: '"Auge" ist neutral: das Auge, Plural: die Augen (Englisch: eye/eyes).',
    tags: ['Körper', 'Plural'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0006',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Familie',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Schwester',
    focusWord: 'die Schwester',
    question: 'Was bedeutet "die Schwester"?',
    options: ['Sister', 'Brother', 'Mother', 'Daughter'],
    correctAnswer: 'Sister',
    explanation: '"Die Schwester" bedeutet Schwester (sister).',
    tags: ['Familie', 'Personen'],
    timeLimit: 12,
  },
  {
    id: 'A1-WD-0007',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Küche & Geschirr',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Gabel',
    focusWord: 'die Gabel',
    question: 'Was bedeutet "die Gabel" beim Besteck?',
    options: ['Fork', 'Spoon (der Löffel)', 'Knife (das Messer)', 'Plate (der Teller)'],
    correctAnswer: 'Fork',
    explanation: '"Die Gabel" ist die Fork (Gabel, Messer, Löffel).',
    tags: ['Essen', 'Küche'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0008',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Schule & Büro',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Buch',
    focusWord: 'das Buch',
    question: 'Welcher Artikel und Plural gehören zu "Buch"?',
    options: ['das Buch -> die Bücher', 'der Buch -> die Büchern', 'die Buch -> die Buche', 'das Buch -> die Buchs'],
    correctAnswer: 'das Buch -> die Bücher',
    explanation: '"Buch" ist neutral (das Buch) und bildet den Plural mit Umlaut und -er (die Bücher).',
    tags: ['Schule', 'Plural'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0009',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Berufe',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Arzt / die Ärztin',
    focusWord: 'der Arzt / die Ärztin',
    question: 'Welcher Beruf ist gemeint?',
    options: ['Doctor / Physician', 'Teacher (Lehrer)', 'Driver (Fahrer)', 'Engineer (Ingenieur)'],
    correctAnswer: 'Doctor / Physician',
    explanation: 'Der Arzt / die Ärztin behandelt Kranke (Doctor).',
    tags: ['Berufe', 'Gesundheit'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0010',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Getränke',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Water',
    focusWord: 'Water',
    question: 'Wie heißt "Water" auf Deutsch mit Artikel?',
    options: ['das Wasser', 'der Wasser', 'die Wasser', 'die Wässer'],
    correctAnswer: 'das Wasser',
    explanation: 'Wasser ist neutral: das Wasser.',
    tags: ['Getränke', 'Artikel'],
    timeLimit: 12,
  },
  {
    id: 'A1-WD-0011',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Verkehrsmittel',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Zug',
    focusWord: 'der Zug',
    question: 'Was bedeutet "der Zug"?',
    options: ['Train', 'Airplane (das Flugzeug)', 'Bicycle (das Fahrrad)', 'Ship (das Schiff)'],
    correctAnswer: 'Train',
    explanation: '"Der Zug" ist die Bahn / der Zug (train).',
    tags: ['Verkehr', 'Reisen'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0012',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wohnen & Räume',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Küche',
    focusWord: 'die Küche',
    question: 'Welcher Raum in der Wohnung ist "die Küche"?',
    options: ['Kitchen', 'Bathroom (das Badezimmer)', 'Bedroom (das Schlafzimmer)', 'Living room (das Wohnzimmer)'],
    correctAnswer: 'Kitchen',
    explanation: '"Die Küche" ist der Raum zum Kochen (kitchen).',
    tags: ['Wohnen', 'Räume'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0013',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gegenteile / Adjektive',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'groß',
    focusWord: 'groß',
    question: 'Was ist das genaue Gegenteil (Antonym) von "groß"?',
    options: ['klein', 'alt', 'schwer', 'kurz'],
    correctAnswer: 'klein',
    explanation: 'Das Gegenteil von groß (big) ist klein (small).',
    tags: ['Adjektive', 'Antonyme'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0014',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Gegenteile / Adjektive',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'teuer',
    focusWord: 'teuer',
    question: 'Was ist das Gegenteil von "teuer"?',
    options: ['billig / günstig', 'schnell', 'hell', 'sauber'],
    correctAnswer: 'billig / günstig',
    explanation: 'Teuer (expensive) <-> billig / preiswert / günstig (cheap).',
    tags: ['Adjektive', 'Antonyme', 'Einkaufen'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0015',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Wochentage',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'Mittwoch',
    focusWord: 'Mittwoch',
    question: 'Welcher Wochentag ist "Mittwoch"?',
    options: ['Wednesday', 'Monday (Montag)', 'Tuesday (Dienstag)', 'Thursday (Donnerstag)'],
    correctAnswer: 'Wednesday',
    explanation: 'Mittwoch = Wednesday.',
    tags: ['Zeit', 'Wochentage'],
    timeLimit: 12,
  },
  {
    id: 'A1-WD-0016',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Stadt & Orte',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Bahnhof',
    focusWord: 'der Bahnhof',
    question: 'Was ist "der Bahnhof"?',
    options: ['Train station', 'Airport (der Flughafen)', 'Hospital (das Krankenhaus)', 'Library (die Bibliothek)'],
    correctAnswer: 'Train station',
    explanation: '"Der Bahnhof" ist die Bahnstation für Züge.',
    tags: ['Stadt', 'Orte', 'Verkehr'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0017',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Körper & Gesundheit',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Kopf',
    focusWord: 'der Kopf',
    question: 'Was bedeutet "der Kopf" und wie lautet der Plural?',
    options: ['Head -> die Köpfe', 'Hand -> die Hände', 'Foot -> die Füße', 'Arm -> die Arme'],
    correctAnswer: 'Head -> die Köpfe',
    explanation: 'Der Kopf (head), Plural: die Köpfe.',
    tags: ['Körper', 'Plural'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0018',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Tageszeiten',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Abend',
    focusWord: 'der Abend',
    question: 'Welche Begrüßung passt zur Tageszeit "der Abend"?',
    options: ['Guten Abend!', 'Guten Morgen!', 'Gute Nacht!', 'Guten Tag!'],
    correctAnswer: 'Guten Abend!',
    explanation: 'Am Abend begrüßt man einander mit "Guten Abend!".',
    tags: ['Begrüßung', 'Tageszeiten'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0019',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Schuhe & Kleidung',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Schuhe',
    focusWord: 'die Schuhe',
    question: 'Wie heißt die Einzahl (Singular) von "die Schuhe"?',
    options: ['der Schuh', 'das Schuh', 'die Schuhe', 'der Schuher'],
    correctAnswer: 'der Schuh',
    explanation: 'Der Singular ist maskulin: "der Schuh" (die Schuhe).',
    tags: ['Kleidung', 'Singular'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0020',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Essen & Frühstück',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Brötchen',
    focusWord: 'das Brötchen',
    question: 'Was ist "das Brötchen"?',
    options: ['Bread roll / Small bread', 'Cake (der Kuchen)', 'Butter (die Butter)', 'Egg (das Ei)'],
    correctAnswer: 'Bread roll / Small bread',
    explanation: '"Das Brötchen" ist ein kleines Brot / eine Semmel (bread roll).',
    tags: ['Essen', 'Frühstück'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🕵️ A1: WAS BIN ICH? (15 Questions: 5 EASY, 8 MEDIUM, 2 HARD)
  // =========================================================================
  {
    id: 'A1-WB-0001',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Tiere',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Tier anhand der Hinweise:',
    clues: [
      'Hinweis 1: Ich habe vier Beine und ein weiches Fell.',
      'Hinweis 2: Ich belle und passe auf das Haus auf.',
      'Hinweis 3: Ich bin der treueste Freund des Menschen.',
    ],
    options: ['Der Hund', 'Die Katze', 'Das Pferd', 'Der Elefant'],
    correctAnswer: 'Der Hund',
    explanation: 'Der Hund bellt ("Wau-Wau") und gilt als bester Freund des Menschen.',
    tags: ['Tiere', 'Deduction'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0002',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Möbel & Beleuchtung',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Alltagsgegenstand:',
    clues: [
      'Hinweis 1: Ich stehe meistens auf dem Tisch oder hänge an der Decke.',
      'Hinweis 2: Man kann mich ein- und ausschalten.',
      'Hinweis 3: Ich mache Licht, wenn es dunkel wird.',
    ],
    options: ['Die Lampe', 'Der Stuhl', 'Der Kühlschrank', 'Das Bett'],
    correctAnswer: 'Die Lampe',
    explanation: 'Die Lampe spendet elektrisches Licht.',
    tags: ['Wohnen', 'Möbel'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0003',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Lebensmittel & Bäckerei',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Grundnahrungsmittel:',
    clues: [
      'Hinweis 1: Man kauft mich jeden Tag frisch in der Bäckerei.',
      'Hinweis 2: Ich habe eine braune, knusprige Kruste.',
      'Hinweis 3: Deutsche schneiden mich in Scheiben und belegen mich mit Käse oder Wurst.',
    ],
    options: ['Das Brot', 'Die Suppe', 'Der Apfel', 'Die Schokolade'],
    correctAnswer: 'Das Brot',
    explanation: 'Das deutsche Brot ist weltberühmt und wird in Scheiben geschnitten.',
    tags: ['Essen', 'Kultur'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0004',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Verkehrsmittel',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Verkehrsmittel:',
    clues: [
      'Hinweis 1: Ich habe zwei Räder, aber keinen Benzinmotor.',
      'Hinweis 2: Man muss in die Pedale treten, um zu fahren.',
      'Hinweis 3: Ich habe eine Klingel und einen Lenker.',
    ],
    options: ['Das Fahrrad', 'Das Auto', 'Der Bus', 'Das Flugzeug'],
    correctAnswer: 'Das Fahrrad',
    explanation: 'Das Fahrrad hat Pedale, Lenker und zwei Räder.',
    tags: ['Verkehr', 'Mobilität'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0005',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Wohnen & Geräte',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Küchengerät:',
    clues: [
      'Hinweis 1: Ich stehe in jeder Küche.',
      'Hinweis 2: In meinem Inneren ist es Tag und Nacht sehr kalt (ca. 4 bis 7 Grad).',
      'Hinweis 3: Man lagert Milch, Butter, Käse und Fleisch in mir.',
    ],
    options: ['Der Kühlschrank', 'Der Backofen', 'Die Spülmaschine', 'Die Mikrowelle'],
    correctAnswer: 'Der Kühlschrank',
    explanation: 'Der Kühlschrank kühlt Lebensmittel.',
    tags: ['Küche', 'Haushalt'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0006',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Technik & Kommunikation',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte elektronische Gerät:',
    clues: [
      'Hinweis 1: Ich bin klein und passe in jede Hosentasche.',
      'Hinweis 2: Mit mir kann man telefonieren und Nachrichten schreiben.',
      'Hinweis 3: Ich habe einen Touchscreen und viele Apps.',
    ],
    options: ['Das Smartphone / Handy', 'Der Fernseher', 'Die Waschmaschine', 'Das Radio'],
    correctAnswer: 'Das Smartphone / Handy',
    explanation: 'Das Smartphone / Handy nutzt man zum Telefonieren und für Apps.',
    tags: ['Technik', 'Kommunikation'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0007',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Wetter & Natur',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Wetterphänomen:',
    clues: [
      'Hinweis 1: Ich falle im kalten Winter vom Himmel.',
      'Hinweis 2: Ich bin weiß, weich und sehr kalt.',
      'Hinweis 3: Kinder bauen aus mir einen Mann mit einer Karottennase.',
    ],
    options: ['Der Schnee', 'Der Regen', 'Der Nebel', 'Der Wind'],
    correctAnswer: 'Der Schnee',
    explanation: 'Aus Schnee baut man im Winter einen Schneemann.',
    tags: ['Wetter', 'Winter'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0008',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Kleidung & Wetter',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Zubehör:',
    clues: [
      'Hinweis 1: Man nimmt mich mit, wenn dunkle Wolken am Himmel stehen.',
      'Hinweis 2: Man spannt mich über den Kopf auf.',
      'Hinweis 3: Ich schütze vor Nässe und Regentropfen.',
    ],
    options: ['Der Regenschirm', 'Die Sonnenbrille', 'Der Rucksack', 'Der Gürtel'],
    correctAnswer: 'Der Regenschirm',
    explanation: 'Der Regenschirm schützt vor Regen.',
    tags: ['Kleidung', 'Wetter'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0009',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Schule & Gegenstände',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Gegenstand im Unterricht:',
    clues: [
      'Hinweis 1: Ich bestehe aus vielen Seiten Papier.',
      'Hinweis 2: Schüler schreiben mit Füller oder Bleistift in mich hinein.',
      'Hinweis 3: In mir stehen Notizen und Hausaufgaben.',
    ],
    options: ['Das Heft', 'Das Lineal', 'Die Schere', 'Der Radiergummi'],
    correctAnswer: 'Das Heft',
    explanation: 'In das Schulheft schreibt man Notizen und Aufgaben.',
    tags: ['Schule', 'Lernen'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0010',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Berufe',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Beruf:',
    clues: [
      'Hinweis 1: Ich arbeite in einer Schule oder Sprachschule.',
      'Hinweis 2: Ich stehe vor der Tafel und erkläre Grammatik und Vokabeln.',
      'Hinweis 3: Ich korrigiere Tests und helfe Schülern beim Lernen.',
    ],
    options: ['Der Lehrer', 'Der Koch', 'Der Polizist', 'Der Pilot'],
    correctAnswer: 'Der Lehrer',
    explanation: 'Der Lehrer unterrichtet Schüler in der Schule.',
    tags: ['Berufe', 'Schule'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0011',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Gebäude & Orte',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Ort in der Stadt:',
    clues: [
      'Hinweis 1: Hier gibt es viele Bücher, Zeitungen und Magazine.',
      'Hinweis 2: Man muss hier ganz leise sein.',
      'Hinweis 3: Man kann Bücher kostenlos ausleihen und zum Lesen mitnehmen.',
    ],
    options: ['Die Bibliothek', 'Das Kino', 'Das Kaufhaus', 'Das Restaurant'],
    correctAnswer: 'Die Bibliothek',
    explanation: 'In der Bibliothek (Bücherei) leiht man Bücher aus und liest in Ruhe.',
    tags: ['Stadt', 'Kultur'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0012',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Getränke',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Getränk:',
    clues: [
      'Hinweis 1: Ich bin schwarz oder dunkelbraun und dufte herrlich.',
      'Hinweis 2: Viele Erwachsene trinken mich morgens, um wach zu werden.',
      'Hinweis 3: Man trinkt mich oft mit Milch und Zucker aus einer Tasse.',
    ],
    options: ['Der Kaffee', 'Der Orangensaft', 'Das Bier', 'Das Mineralwasser'],
    correctAnswer: 'Der Kaffee',
    explanation: 'Kaffee ist das beliebteste Heißgetränk am Morgen.',
    tags: ['Getränke', 'Frühstück'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0013',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Körperteile',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Körperteil:',
    clues: [
      'Hinweis 1: Jeder Mensch hat zwei davon am Körper.',
      'Hinweis 2: An jedem Ende befinden sich genau fünf Finger.',
      'Hinweis 3: Man benutzt mich zum Schreiben, Greifen und Klatschen.',
    ],
    options: ['Die Hand', 'Der Fuß', 'Das Knie', 'Das Ohr'],
    correctAnswer: 'Die Hand',
    explanation: 'Die Hand hat 5 Finger und dient zum Schreiben und Greifen.',
    tags: ['Körper', 'Anatomie'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0014',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Möbel & Schlafen',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Möbelstück:',
    clues: [
      'Hinweis 1: Ich stehe im Schlafzimmer.',
      'Hinweis 2: Auf mir liegen eine weiche Matratze, ein Kissen und eine Decke.',
      'Hinweis 3: Man legt sich nachts auf mich, um zu schlafen und zu träumen.',
    ],
    options: ['Das Bett', 'Das Sofa', 'Der Schrank', 'Der Schreibtisch'],
    correctAnswer: 'Das Bett',
    explanation: 'Im Bett schläft man nachts.',
    tags: ['Wohnen', 'Möbel'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0015',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Reisen & Dokumente',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte offizielle Dokument:',
    clues: [
      'Hinweis 1: Ich bin ein kleines Buch mit einem Foto und persönlichen Daten.',
      'Hinweis 2: Man braucht mich unbedingt am Flughafen für Reisen ins Ausland.',
      'Hinweis 3: Die Grenzpolizei stempelt mich bei der Passkontrolle ab.',
    ],
    options: ['Der Reisepass', 'Die Fahrkarte', 'Der Führerschein', 'Die Kreditkarte'],
    correctAnswer: 'Der Reisepass',
    explanation: 'Der Reisepass weist die Identität und Staatsangehörigkeit bei Auslandsreisen nach.',
    tags: ['Reisen', 'Dokumente'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ A1: TEAM BATTLE (15 Questions: 9 EASY, 5 MEDIUM, 1 HARD)
  // =========================================================================
  {
    id: 'A1-TB-0001',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Farben & Natur',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Farbe hat eine frische reife Banane?',
    options: ['Gelb', 'Rot', 'Blau', 'Schwarz'],
    correctAnswer: 'Gelb',
    explanation: 'Reife Bananen sind leuchtend gelb.',
    tags: ['Farben', 'Natur'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0002',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Wochentage & Reihenfolge',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welcher Wochentag kommt direkt nach dem Dienstag?',
    options: ['Mittwoch', 'Donnerstag', 'Montag', 'Freitag'],
    correctAnswer: 'Mittwoch',
    explanation: 'Die Reihenfolge lautet: Montag, Dienstag, Mittwoch.',
    tags: ['Wochentage', 'Zeit'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0003',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Begrüßung & Tageszeit',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was sagt man in Deutschland typischerweise, bevor man schlafen geht?',
    options: ['Gute Nacht!', 'Guten Morgen!', 'Guten Tag!', 'Mahlzeit!'],
    correctAnswer: 'Gute Nacht!',
    explanation: 'Vor dem Zubettgehen wünscht man "Gute Nacht!".',
    tags: ['Begrüßung', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0004',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Zahlen & Alter',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Wie fragt man korrekt nach dem Alter einer Person?',
    options: ['Wie alt bist du?', 'Wie viele Jahre hast du?', 'Wie alt hast du?', 'Wie viel alt bist du?'],
    correctAnswer: 'Wie alt bist du?',
    explanation: 'Auf Deutsch fragt man mit dem Verb sein: "Wie alt bist du?" (nicht mit haben).',
    tags: ['Alter', 'Fragen'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0005',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Familie & Verwandtschaft',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Mutter meiner Mutter ist meine ___ .',
    options: ['Großmutter / Oma', 'Tante', 'Schwester', 'Cousine'],
    correctAnswer: 'Großmutter / Oma',
    explanation: 'Die Mutter der Mutter ist die Großmutter (Oma).',
    tags: ['Familie', 'Verwandtschaft'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0006',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Körperteile',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Mit welchem Körperteil hört man Musik?',
    options: ['Mit den Ohren', 'Mit den Augen', 'Mit der Nase', 'Mit den Händen'],
    correctAnswer: 'Mit den Ohren',
    explanation: 'Hören tut man mit den Ohren.',
    tags: ['Körper', 'Sinne'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0007',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Einkaufen & Bezahlen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was fragt der Verkäufer an der Kasse?',
    options: ['Zahlen Sie bar oder mit Karte?', 'Kochen Sie heute?', 'Wo wohnen Sie?', 'Wie heißen Sie?'],
    correctAnswer: 'Zahlen Sie bar oder mit Karte?',
    explanation: 'An der Kasse wird nach der Zahlungsart gefragt (bar oder Karte).',
    tags: ['Einkaufen', 'Kommunikation'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0008',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Jahreszeiten & Monate',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welcher Monat ist der allererste Monat im Kalenderjahr?',
    options: ['Januar', 'Februar', 'Dezember', 'März'],
    correctAnswer: 'Januar',
    explanation: 'Das Kalenderjahr beginnt mit dem 1. Januar.',
    tags: ['Monate', 'Kalender'],
    timeLimit: 12,
  },
  {
    id: 'A1-TB-0009',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Wetter & Temperatur',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Das Thermometer zeigt minus 10 Grad Celsius. Wie ist das Wetter?',
    options: ['Es ist eiskalt.', 'Es ist sonnig und heiß.', 'Es ist angenehm warm.', 'Es ist schwül.'],
    correctAnswer: 'Es ist eiskalt.',
    explanation: '-10 Grad Celsius bedeutet Frost und eisige Kälte.',
    tags: ['Wetter', 'Temperatur'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0010',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Verkehr & Ampel',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Die Fußgängerampel zeigt Rot. Was musst du tun?',
    options: ['Stehen bleiben und warten', 'Schnell rennen', 'Weitergehen', 'Das Auto anhalten'],
    correctAnswer: 'Stehen bleiben und warten',
    explanation: 'Bei Rot an der Ampel muss man stehen bleiben.',
    tags: ['Verkehr', 'Regeln'],
    timeLimit: 12,
  },
  {
    id: 'A1-TB-0011',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Freizeit & Hobbys',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was macht man typischerweise im Schwimmbad?',
    options: ['Schwimmen', 'Kochen', 'Schlafen', 'Autofahren'],
    correctAnswer: 'Schwimmen',
    explanation: 'Im Schwimmbad geht man schwimmen.',
    tags: ['Freizeit', 'Sport'],
    timeLimit: 12,
  },
  {
    id: 'A1-TB-0012',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Restaurant & Höflichkeit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was sagt man in Deutschland höflich vor dem Essen?',
    options: ['Guten Appetit!', 'Gute Besserung!', 'Herzlichen Glückwunsch!', 'Schönes Wochenende!'],
    correctAnswer: 'Guten Appetit!',
    explanation: 'Vor dem Essen wünscht man sich "Guten Appetit!".',
    tags: ['Essen', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0013',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Gesundheit & Wünsche',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Jemand niest oder ist krank. Was wünscht man der Person?',
    options: ['Gesundheit! / Gute Besserung!', 'Guten Flug!', 'Viel Glück zum Geburtstag!', 'Guten Morgen!'],
    correctAnswer: 'Gesundheit! / Gute Besserung!',
    explanation: 'Beim Niesen sagt man "Gesundheit!", Kranken wünscht man "Gute Besserung!".',
    tags: ['Gesundheit', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0014',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Geografie Deutschland',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ist die offizielle Bundeshauptstadt von Deutschland?',
    options: ['Berlin', 'München', 'Hamburg', 'Frankfurt'],
    correctAnswer: 'Berlin',
    explanation: 'Die Hauptstadt der Bundesrepublik Deutschland ist Berlin.',
    tags: ['Geografie', 'Landeskunde'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0015',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Farben der Flagge',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche drei Farben hat die deutsche Nationalflagge von oben nach unten?',
    options: ['Schwarz - Rot - Gold', 'Schwarz - Weiß - Rot', 'Rot - Weiß - Blau', 'Gold - Rot - Schwarz'],
    correctAnswer: 'Schwarz - Rot - Gold',
    explanation: 'Die Flagge der Bundesrepublik Deutschland ist Schwarz-Rot-Gold.',
    tags: ['Landeskunde', 'Farben'],
    timeLimit: 15,
  },
];
