import { BankQuestion } from '../questionTypes.js';

/**
 * A1 Level Question Bank - Farh SprachArena
 * Levels: A1
 * Categories: Begrüßung, Familie, Zahlen, Uhrzeit, Essen, Trinken, Alltag, Wohnen, Arbeit, Freizeit, Kleidung, Körper, Farben, Verkehr, Wetter
 * Games: SCHNELLANTWORT, SATZ_RENNEN, WORTSCHATZ_DUELL, WAS_BIN_ICH, TEAM_BATTLE
 */
export const A1_QUESTIONS: BankQuestion[] = [
  // =========================================================================
  // ⚡ A1: SCHNELLANTWORT
  // =========================================================================
  {
    id: 'A1-SA-0001',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Begrüßung',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Guten Morgen! Wie ___ es Ihnen?',
    options: ['geht', 'gehen', 'gehe', 'gehst'],
    correctAnswer: 'geht',
    explanation: 'Die feste Höflichkeitsformel lautet: "Wie geht es Ihnen?"',
    tags: ['Begrüßung', 'Höflichkeit'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0002',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verben / Konjugation',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich ___ Deutsch im Unterricht mit Farh.',
    options: ['lerne', 'lernst', 'lernt', 'lernen'],
    correctAnswer: 'lerne',
    explanation: '1. Person Singular ("ich") von lernen ist "lerne".',
    tags: ['Verben', 'Präsens'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0003',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Familie & Personalpronomen',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Das ist mein Bruder. ___ heißt Lukas.',
    options: ['Er', 'Sie', 'Es', 'Du'],
    correctAnswer: 'Er',
    explanation: '"Der Bruder" ist maskulin, daher ist das passende Pronomen "er".',
    tags: ['Familie', 'Pronomen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0004',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Zahlen & Rechnen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was ist das Ergebnis: zehn plus fünf = ___',
    options: ['fünfzehn', 'fünfzig', 'vierzehn', 'sechzehn'],
    correctAnswer: 'fünfzehn',
    explanation: '10 + 5 = 15 ("fünfzehn").',
    tags: ['Zahlen', 'Mathematik'],
    timeLimit: 12,
  },
  {
    id: 'A1-SA-0005',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Essen & Trinken',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Zum Frühstück trinke ich immer ___ Kaffee.',
    options: ['einen', 'eine', 'ein', 'einem'],
    correctAnswer: 'einen',
    explanation: '"Der Kaffee" steht hier im Akkusativ maskulin: "einen Kaffee".',
    tags: ['Essen', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0006',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wohnen & Möbel',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Wo ist die Lampe? — Sie steht auf ___ Tisch.',
    options: ['dem', 'den', 'das', 'die'],
    correctAnswer: 'dem',
    explanation: 'Positionsangabe mit "auf" (Wo?) verlangt Dativ ("auf dem Tisch").',
    tags: ['Wohnen', 'Dativ', 'Präpositionen'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0007',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Uhrzeit',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Es ist 14:30 Uhr. Auf Deutsch sagt man: Es ist ___ drei.',
    options: ['halb', 'vor', 'nach', 'viertel'],
    correctAnswer: 'halb',
    explanation: '14:30 Uhr heißt im Deutschen "halb drei".',
    tags: ['Uhrzeit', 'Alltag'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0008',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Wetter',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Im Sommer ist es draußen sehr ___ .',
    options: ['warm', 'kalt', 'schneeig', 'frostig'],
    correctAnswer: 'warm',
    explanation: 'Im Sommer ist das Wetter warm/heiß.',
    tags: ['Wetter', 'Jahreszeiten'],
    timeLimit: 12,
  },
  {
    id: 'A1-SA-0009',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Freizeit & Hobbys',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Am Samstag ___ meine Freunde und ich Fußball.',
    options: ['spielen', 'spielt', 'spiele', 'spielst'],
    correctAnswer: 'spielen',
    explanation: '"Meine Freunde und ich" = wir (1. Person Plural -> spielen).',
    tags: ['Freizeit', 'Sport'],
    timeLimit: 15,
  },
  {
    id: 'A1-SA-0010',
    level: 'A1',
    gameType: 'SCHNELLANTWORT',
    category: 'Verkehr',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich fahre jeden Morgen mit ___ Bus zur Sprachschule.',
    options: ['dem', 'den', 'das', 'der'],
    correctAnswer: 'dem',
    explanation: '"Mit" steht immer mit dem Dativ: "mit dem Bus" (maskulin).',
    tags: ['Verkehr', 'Dativ'],
    timeLimit: 15,
  },

  // =========================================================================
  // 🧩 A1: SATZ-RENNEN
  // =========================================================================
  {
    id: 'A1-SR-0001',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Hauptsatz / Satzbau',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Wörter in die richtige Reihenfolge:',
    words: ['Ich', 'gerne', 'lerne', 'Deutsch.'],
    correctOrder: ['Ich', 'lerne', 'gerne', 'Deutsch.'],
    correctAnswer: ['Ich', 'lerne', 'gerne', 'Deutsch.'],
    explanation: 'Im deutschen Aussagesatz steht das konjugierte Verb an Position 2.',
    tags: ['Satzbau', 'Hauptsatz'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0002',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'W-Fragen',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde die richtige Frage nach dem Wohnort:',
    words: ['Wo', 'du', 'wohnst', 'in Deutschland', '?'],
    correctOrder: ['Wo', 'wohnst', 'du', 'in Deutschland', '?'],
    correctAnswer: ['Wo', 'wohnst', 'du', 'in Deutschland', '?'],
    explanation: 'Bei W-Fragen: Fragewort auf Position 1, Verb auf Position 2, Subjekt auf Position 3.',
    tags: ['Fragesatz', 'W-Frage'],
    timeLimit: 20,
  },
  {
    id: 'A1-SR-0003',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Ja/Nein-Fragen',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bilde eine korrekte Ja/Nein-Frage:',
    words: ['Trinkst', 'einen Kaffee', 'du', 'gerne', '?'],
    correctOrder: ['Trinkst', 'du', 'gerne', 'einen Kaffee', '?'],
    correctAnswer: ['Trinkst', 'du', 'gerne', 'einen Kaffee', '?'],
    explanation: 'In Ja/Nein-Fragen steht das Verb immer an Position 1.',
    tags: ['Fragesatz', 'Ja/Nein-Frage'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0004',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Modalverben',
    difficulty: 'HARD',
    type: 'SENTENCE_ORDER',
    question: 'Bringe den Satz mit Modalverb in die richtige Reihenfolge:',
    words: ['Wir', 'heute Abend', 'können', 'zusammen kochen.'],
    correctOrder: ['Wir', 'können', 'heute Abend', 'zusammen kochen.'],
    correctAnswer: ['Wir', 'können', 'heute Abend', 'zusammen kochen.'],
    explanation: 'Das konjugierte Modalverb steht an Position 2, der Infinitiv am Satzende (Satzklammer).',
    tags: ['Modalverben', 'Satzklammer'],
    timeLimit: 30,
  },
  {
    id: 'A1-SR-0005',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Tagesablauf',
    difficulty: 'MEDIUM',
    type: 'SENTENCE_ORDER',
    question: 'Bringe die Satzglieder in die korrekte Reihenfolge:',
    words: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    correctOrder: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    correctAnswer: ['Am Morgen', 'frühstücke', 'ich', 'um sieben Uhr.'],
    explanation: 'Wenn die Zeitangabe an Position 1 steht, folgt das Verb an Position 2 und danach das Subjekt.',
    tags: ['Inversion', 'Tagesablauf'],
    timeLimit: 25,
  },
  {
    id: 'A1-SR-0006',
    level: 'A1',
    gameType: 'SATZ_RENNEN',
    category: 'Einkaufen',
    difficulty: 'EASY',
    type: 'SENTENCE_ORDER',
    question: 'Bilde einen Satz beim Einkaufen:',
    words: ['Ich', 'zwei Kilo Äpfel', 'möchte', 'bitte.'],
    correctOrder: ['Ich', 'möchte', 'bitte', 'zwei Kilo Äpfel.'],
    correctAnswer: ['Ich', 'möchte', 'bitte', 'zwei Kilo Äpfel.'],
    explanation: '"möchte" steht an Position 2.',
    tags: ['Einkaufen', 'Höflichkeit'],
    timeLimit: 25,
  },

  // =========================================================================
  // 🧠 A1: WORTSCHATZ-DUELL
  // =========================================================================
  {
    id: 'A1-WD-0001',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Möbel / Nomen',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'der Tisch',
    focusWord: 'der Tisch',
    question: 'Welcher Artikel und welche Übersetzung gehören zu diesem Wort?',
    options: ['der Tisch (Table)', 'die Tisch (Chair)', 'das Tisch (Bed)', 'die Tische (Cupboard)'],
    correctAnswer: 'der Tisch (Table)',
    explanation: '"Tisch" ist maskulin: der Tisch.',
    tags: ['Artikel', 'Möbel'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0002',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Obst & Gemüse',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Apple (تفاحة)',
    focusWord: 'Apple (تفاحة)',
    question: 'Wie heißt das gesuchte Wort auf Deutsch?',
    options: ['der Apfel', 'die Birne', 'die Banane', 'die Orange'],
    correctAnswer: 'der Apfel',
    explanation: 'Apple heißt "der Apfel".',
    tags: ['Essen', 'Obst'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0003',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Kleidung',
    difficulty: 'MEDIUM',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Hose',
    focusWord: 'die Hose',
    question: 'Was bedeutet "die Hose"?',
    options: ['Trousers / Pants', 'Shirt / T-Shirt', 'Jacket / Coat', 'Shoes'],
    correctAnswer: 'Trousers / Pants',
    explanation: '"Die Hose" bezeichnet das Kleidungsstück für die Beine.',
    tags: ['Kleidung', 'Wortschatz'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0004',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Farben',
    difficulty: 'EASY',
    type: 'VOCABULARY_REVERSE',
    sourceWord: 'Red (أحمر)',
    focusWord: 'Red (أحmer)',
    question: 'Wie heißt die Farbe "Red" auf Deutsch?',
    options: ['rot', 'blau', 'gelb', 'grün'],
    correctAnswer: 'rot',
    explanation: 'Red = rot.',
    tags: ['Farben', 'Adjektive'],
    timeLimit: 12,
  },
  {
    id: 'A1-WD-0005',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Körperteile',
    difficulty: 'HARD',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'das Auge',
    focusWord: 'das Auge',
    question: 'Welcher Plural und welche Bedeutung gehören zu "das Auge"?',
    options: ['das Auge (Eye) -> die Augen', 'der Auge (Ear) -> die Augen', 'die Auge (Hand) -> die Augen', 'das Auge (Mouth) -> die Äuger'],
    correctAnswer: 'das Auge (Eye) -> die Augen',
    explanation: 'Auge ist neutral: das Auge, Plural: die Augen.',
    tags: ['Körper', 'Plural'],
    timeLimit: 15,
  },
  {
    id: 'A1-WD-0006',
    level: 'A1',
    gameType: 'WORTSCHATZ_DUELL',
    category: 'Familie',
    difficulty: 'EASY',
    type: 'VOCABULARY_TRANSLATION',
    sourceWord: 'die Schwester',
    focusWord: 'die Schwester',
    question: 'Was bedeutet "die Schwester"?',
    options: ['Sister', 'Brother', 'Mother', 'Daughter'],
    correctAnswer: 'Sister',
    explanation: 'Die Schwester = Sister.',
    tags: ['Familie', 'Personen'],
    timeLimit: 12,
  },

  // =========================================================================
  // 🕵️ A1: WAS BIN ICH?
  // =========================================================================
  {
    id: 'A1-WB-0001',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Tiere',
    difficulty: 'EASY',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Tier anhand der Hinweise:',
    clues: [
      'Hinweis 1: Ich habe vier Beine und ein weiches Fell.',
      'Hinweis 2: Ich belle und passe auf das Haus auf.',
      'Hinweis 3: Ich bin der beste Freund des Menschen.',
    ],
    options: ['Der Hund', 'Die Katze', 'Das Pferd', 'Der Elefant'],
    correctAnswer: 'Der Hund',
    explanation: 'Der Hund bellt und hat vier Beine.',
    tags: ['Tiere', 'Deduction'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0002',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Gegenstände',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate den gesuchten Alltagsgegenstand:',
    clues: [
      'Hinweis 1: Ich stehe meistens im Wohnzimmer oder Schlafzimmer.',
      'Hinweis 2: Man kann mich ein- und ausschalten.',
      'Hinweis 3: Ich mache Licht, wenn es dunkel wird.',
    ],
    options: ['Die Lampe', 'Der Stuhl', 'Der Kühlschrank', 'Das Bett'],
    correctAnswer: 'Die Lampe',
    explanation: 'Die Lampe spendet Licht und wird ein- und ausgeschaltet.',
    tags: ['Wohnen', 'Alltag'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0003',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Lebensmittel',
    difficulty: 'HARD',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Lebensmittel:',
    clues: [
      'Hinweis 1: Man kauft mich frisch in der Bäckerei.',
      'Hinweis 2: Ich habe eine knusprige Kruste.',
      'Hinweis 3: Deutsche essen mich gerne mit Butter und Käse.',
    ],
    options: ['Das Brot', 'Die Suppe', 'Der Apfel', 'Die Schokolade'],
    correctAnswer: 'Das Brot',
    explanation: 'Das Brot kauft man in der Bäckerei und es hat eine Kruste.',
    tags: ['Essen', 'Kultur'],
    timeLimit: 24,
  },
  {
    id: 'A1-WB-0004',
    level: 'A1',
    gameType: 'WAS_BIN_ICH',
    category: 'Verkehrsmittel',
    difficulty: 'MEDIUM',
    type: 'CLUE_GUESS',
    question: 'Errate das gesuchte Verkehrsmittel:',
    clues: [
      'Hinweis 1: Ich habe zwei Räder, aber keinen Motor.',
      'Hinweis 2: Man muss in die Pedale treten, um vorwärts zu fahren.',
      'Hinweis 3: In Deutschland fahren viele Menschen mit mir zur Arbeit oder Schule.',
    ],
    options: ['Das Fahrrad', 'Das Auto', 'Der Bus', 'Das Flugzeug'],
    correctAnswer: 'Das Fahrrad',
    explanation: 'Das Fahrrad hat 2 Räder und Pedale.',
    tags: ['Verkehr', 'Mobilität'],
    timeLimit: 24,
  },

  // =========================================================================
  // ⚔️ A1: TEAM BATTLE
  // =========================================================================
  {
    id: 'A1-TB-0001',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Farben & Natur',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welche Farbe hat eine reife Banane?',
    options: ['Gelb', 'Rot', 'Blau', 'Schwarz'],
    correctAnswer: 'Gelb',
    explanation: 'Reife Bananen sind gelb.',
    tags: ['Farben', 'Natur'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0002',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Wochentage',
    difficulty: 'EASY',
    type: 'MULTIPLE_CHOICE',
    question: 'Welcher Wochentag kommt direkt nach dem Dienstag?',
    options: ['Mittwoch', 'Donnerstag', 'Montag', 'Freitag'],
    correctAnswer: 'Mittwoch',
    explanation: 'Montag -> Dienstag -> Mittwoch.',
    tags: ['Zeit', 'Kalender'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0003',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Länder & Sprachen',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Was spricht man in Deutschland, Österreich und der Schweiz?',
    options: ['Deutsch', 'Englisch', 'Spanisch', 'Französisch'],
    correctAnswer: 'Deutsch',
    explanation: 'Deutsch ist Amtssprache in den DACH-Ländern.',
    tags: ['Landeskunde', 'Sprachen'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0004',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Verben mit Akkusativ',
    difficulty: 'HARD',
    type: 'MULTIPLE_CHOICE',
    question: 'Ich brauche ___ Stift zum Schreiben.',
    options: ['einen', 'ein', 'eine', 'einem'],
    correctAnswer: 'einen',
    explanation: '"Der Stift" steht im Akkusativ maskulin: "einen Stift".',
    tags: ['Grammatik', 'Akkusativ'],
    timeLimit: 15,
  },
  {
    id: 'A1-TB-0005',
    level: 'A1',
    gameType: 'TEAM_BATTLE',
    category: 'Monate & Jahreszeiten',
    difficulty: 'MEDIUM',
    type: 'MULTIPLE_CHOICE',
    question: 'Welcher Monat ist der erste Monat im Kalenderjahr?',
    options: ['Januar', 'Dezember', 'Februar', 'März'],
    correctAnswer: 'Januar',
    explanation: 'Das Jahr beginnt mit dem Monat Januar.',
    tags: ['Zeit', 'Monate'],
    timeLimit: 15,
  },
];
